-- ══════════════════════════════════════════════════════════════
-- Migration 013: Tier 1 Curriculum Library (Location-Independent)
-- 120 tasks + 40 primers that work at ANY location worldwide.
-- All marked is_library=true, location_dependency='independent'.
-- ══════════════════════════════════════════════════════════════

-- ── PRIMERS ──────────────────────────────────────────────────
-- 40 primers organized by subject domain

-- Science & Nature primers (8)
INSERT INTO public.primers (title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency) VALUES
('What Is an Ecosystem?', '{"text":"An ecosystem is a community of living things (plants, animals, insects) interacting with each other and their physical environment (soil, water, air, sunlight). Every ecosystem has producers (plants), consumers (animals), and decomposers (fungi, bacteria). Even a small patch of ground under your feet is its own tiny ecosystem!","items":["Producers make their own food from sunlight","Consumers eat other living things","Decomposers break down dead material"]}', 'science_nature', 2, 6, true, 'independent'),
('The Scientific Observation Method', '{"text":"Scientists observe the world carefully before making conclusions. Good observation uses ALL your senses: sight, hearing, smell, and touch (be careful with taste!). Write down exactly what you notice — not what you think or feel, but what you actually see. The difference between observation and inference is important: ''The bark is rough and gray'' is an observation. ''The tree is old'' is an inference.","items":["Use all your senses","Record exactly what you notice","Separate observations from guesses","Look for patterns"]}', 'science_nature', 2, 8, true, 'independent'),
('How Weather Works', '{"text":"Weather is the condition of the atmosphere at a specific time and place. It includes temperature, humidity, wind, clouds, and precipitation. Meteorologists measure weather using instruments: thermometers (temperature), anemometers (wind speed), barometers (air pressure), and rain gauges (precipitation). You can observe weather patterns without any instruments — clouds are nature''s weather forecast!","items":["Cumulus clouds = fair weather","Stratus clouds = overcast, possible drizzle","Cumulonimbus clouds = thunderstorms coming","Cirrus clouds = weather change in 24 hours"]}', 'science_nature', 3, 8, true, 'independent'),
('Classification: Sorting the Living World', '{"text":"Scientists classify living things into groups based on shared characteristics. The main kingdoms are: Animals, Plants, Fungi, and Bacteria. Within each kingdom, organisms are grouped into smaller and smaller categories. You can classify things you find outdoors too — by color, size, texture, number of legs, type of leaf, or how they move.","items":["Kingdom → Phylum → Class → Order → Family → Genus → Species","Look for shared features to group things","Start with big differences, then find smaller ones"]}', 'science_nature', 3, 7, true, 'independent'),
('Forces and Motion Around You', '{"text":"Everything that moves is affected by forces. Gravity pulls things down. Friction slows things down. A push or pull can start, stop, or change the direction of motion. When you walk, you push against the ground (action) and the ground pushes you forward (reaction). Forces are everywhere — you just need to look for them!","items":["Gravity: pulls everything toward Earth","Friction: resists sliding motion","Push/Pull: changes speed or direction","Balanced forces: object stays still or moves at constant speed"]}', 'science_nature', 3, 8, true, 'independent'),
('The Water Cycle', '{"text":"Water moves in a continuous cycle between the Earth''s surface and the atmosphere. The sun heats water in oceans, lakes, and rivers, causing it to evaporate into water vapor. As vapor rises and cools, it condenses into tiny droplets forming clouds. When droplets combine and grow heavy enough, they fall as precipitation (rain, snow, sleet, or hail). The water then flows through streams and rivers back to larger bodies of water, and the cycle continues.","items":["Evaporation: liquid to gas","Condensation: gas to liquid (clouds)","Precipitation: water falls from clouds","Collection: water gathers in bodies of water"]}', 'science_nature', 3, 8, true, 'independent'),
('Biodiversity: Why Variety Matters', '{"text":"Biodiversity means the variety of different living things in an area. A healthy ecosystem has high biodiversity — many different species of plants, animals, insects, and microorganisms all playing different roles. When biodiversity decreases, ecosystems become fragile. You can measure biodiversity by counting how many different species you find in a small area.","items":["More species = more resilient ecosystem","Each species plays a role (pollinator, predator, decomposer)","Biodiversity can be measured with simple quadrat surveys","Even urban areas have surprising biodiversity"]}', 'science_nature', 4, 10, true, 'independent'),
('Energy Transfer in Nature', '{"text":"Energy flows through ecosystems in food chains and food webs. The sun provides energy to plants (producers). Herbivores eat plants and get some of that energy. Carnivores eat herbivores and get some of that energy. At each step, energy is lost as heat. This is why there are fewer top predators than producers in any ecosystem.","items":["Sun → Producers → Primary consumers → Secondary consumers → Decomposers","Only about 10% of energy transfers to the next level","Food webs show how multiple food chains connect","Decomposers recycle nutrients back to the soil"]}', 'science_nature', 5, 10, true, 'independent'),

-- Math primers (8)
('Estimation Strategies', '{"text":"Estimation is making a smart guess about a number before measuring exactly. Good estimators use benchmarks — things they already know the size of. Your hand span is about 15-20 cm. Your arm span is close to your height. A normal walking step is about 0.6-0.8 meters. A doorway is about 2 meters tall. Use these benchmarks to estimate other measurements!","items":["Use benchmarks you know (hand span, arm length, step)","Round numbers to make mental math easier","Estimate BEFORE measuring to build number sense","Being within 20% is usually a good estimate"]}', 'math_real_world', 2, 6, true, 'independent'),
('Measurement Units', '{"text":"We measure different things with different units. Length uses meters (m) and centimeters (cm). Weight uses kilograms (kg) and grams (g). Volume uses liters (L) and milliliters (mL). Temperature uses degrees Celsius (°C) or Fahrenheit (°F). Choosing the right unit matters — you wouldn''t measure a building in millimeters!","items":["1 meter = 100 centimeters","1 kilometer = 1000 meters","1 kilogram = 1000 grams","Always include the unit with your number"]}', 'math_real_world', 2, 6, true, 'independent'),
('Shapes in the Real World', '{"text":"Geometry is everywhere! Buildings use rectangles and triangles for strength. Wheels and coins are circles. Honeycombs are hexagons. Nature loves spirals (shells, hurricanes, galaxies). When you look at any structure, you can break it down into basic shapes: triangles, rectangles, circles, and their 3D versions (pyramids, prisms, spheres, cylinders).","items":["Triangle: strongest shape in construction","Rectangle: most common in buildings","Circle: wheels, pipes, domes","Hexagon: honeycombs, nuts and bolts"]}', 'math_real_world', 2, 7, true, 'independent'),
('Ratios and Proportions', '{"text":"A ratio compares two quantities. If there are 3 trees for every 1 bench in a park, the ratio is 3:1. Proportions are equal ratios — if you double the area, you''d expect double the trees. Ratios help us understand relationships between things we can count and measure in the real world.","items":["Ratio: comparing two numbers (3:1, 2:5)","Proportion: two equal ratios","Scale: a ratio between a model and real life","Rate: a ratio with different units (km per hour)"]}', 'math_real_world', 4, 8, true, 'independent'),
('Data Collection Basics', '{"text":"Good data starts with good questions. Before collecting data, decide: What am I measuring? How will I record it? How many measurements do I need? Use tally marks for counting, tables for organizing, and graphs for visualizing. Always label your data with units and categories.","items":["Define your question clearly","Choose consistent measurement methods","Record every observation — don''t skip any","Look for patterns after you have enough data"]}', 'math_real_world', 3, 8, true, 'independent'),
('Angles and Degrees', '{"text":"Angles measure how much something turns. A full turn is 360°. A right angle (like a corner of a book) is 90°. A straight line is 180°. You can estimate angles by comparing to these benchmarks. Angles appear everywhere — in rooftops, tree branches, shadows, and the hands of a clock.","items":["Acute angle: less than 90°","Right angle: exactly 90°","Obtuse angle: between 90° and 180°","Straight angle: exactly 180°"]}', 'math_real_world', 3, 8, true, 'independent'),
('Area and Perimeter', '{"text":"Perimeter is the distance around the outside of a shape — like walking around the edge of a field. Area is the space inside a shape — like how much grass is in the field. For rectangles: perimeter = 2 × (length + width) and area = length × width. For irregular shapes, you can estimate area by counting squares on a grid.","items":["Perimeter = distance around the edge","Area = space inside the shape","Rectangle area = length × width","Irregular shapes: estimate using a grid"]}', 'math_real_world', 3, 8, true, 'independent'),
('Probability in Everyday Life', '{"text":"Probability is how likely something is to happen. It ranges from 0 (impossible) to 1 (certain). You can also express it as a percentage: 50% means it happens about half the time. You encounter probability every day — weather forecasts, games, traffic patterns. Collecting real data helps you estimate probabilities.","items":["0% = impossible, 100% = certain","50% = equally likely either way","More data = better probability estimates","Expected vs actual outcomes often differ in small samples"]}', 'math_real_world', 5, 10, true, 'independent'),

-- Geography & Maps primers (5)
('Reading a Compass', '{"text":"A compass always points north because of Earth''s magnetic field. The four cardinal directions are North (N), South (S), East (E), and West (W). Between them are intercardinal directions: Northeast (NE), Southeast (SE), Southwest (SW), and Northwest (NW). To find north without a compass: in the Northern Hemisphere, the sun rises in the east and sets in the west. At noon, shadows point north.","items":["N is always at the top of most maps","Clockwise from N: NE, E, SE, S, SW, W, NW","Sun rises in the East, sets in the West","Shadows at noon point North (in Northern Hemisphere)"]}', 'geography_maps', 2, 7, true, 'independent'),
('Map Scale and Distance', '{"text":"Maps show real places at a reduced size. The scale tells you how map distance relates to real distance. A scale of 1:1000 means 1 cm on the map = 1000 cm (10 meters) in real life. You can use the scale bar on a map to estimate real-world distances. Satellite maps (like Google Maps) show scale bars that change as you zoom in and out.","items":["Scale bar converts map distance to real distance","1:1000 means 1 unit on map = 1000 units in reality","Larger scale = more detail, smaller area","Smaller scale = less detail, larger area"]}', 'geography_maps', 3, 8, true, 'independent'),
('Latitude, Longitude, and GPS', '{"text":"Every point on Earth can be described with two numbers: latitude (how far north or south of the equator) and longitude (how far east or west of the Prime Meridian). GPS satellites use these coordinates to pinpoint your location within a few meters. Your phone uses GPS to navigate and to play findamine!","items":["Latitude: 0° at equator, 90° at poles","Longitude: 0° at Prime Meridian (Greenwich, England)","GPS uses signals from 4+ satellites","Coordinates are written as (latitude, longitude)"]}', 'geography_maps', 4, 10, true, 'independent'),
('Terrain and Topography', '{"text":"Topography describes the shape of the land — hills, valleys, plains, mountains, and slopes. Topographic maps use contour lines to show elevation. Lines close together mean steep terrain; lines far apart mean flat terrain. Understanding topography helps you predict where water flows, what plants grow, and how difficult a trail will be.","items":["Contour lines connect points of equal elevation","Close lines = steep slope","Far apart lines = gentle slope","Water flows perpendicular to contour lines (downhill)"]}', 'geography_maps', 5, 10, true, 'independent'),
('Human Geography: How People Shape Places', '{"text":"Human geography studies how people interact with their environment. Why are cities located where they are? (Usually near water, at crossroads, or where resources are abundant.) How does land use change over time? (Farmland becomes suburbs; warehouses become apartments.) Observing the built environment tells you a story about the people who shaped it.","items":["Settlement patterns follow resources and transportation","Land use changes reflect economic and social shifts","Infrastructure reveals community priorities","Public spaces reflect cultural values"]}', 'geography_maps', 5, 10, true, 'independent'),

-- Critical Thinking primers (8)
('Observation vs. Inference', '{"text":"An observation is something you directly see, hear, smell, or measure. An inference is a conclusion you draw from observations. ''The sidewalk is wet'' is an observation. ''It rained recently'' is an inference (maybe someone watered the plants!). Good thinkers keep these separate and gather multiple observations before making inferences.","items":["Observation: what your senses tell you directly","Inference: a conclusion based on observations","Multiple observations make stronger inferences","Always ask: could there be another explanation?"]}', 'critical_thinking', 2, 8, true, 'independent'),
('Asking Good Questions', '{"text":"Good questions lead to deeper understanding. Open-ended questions (How? Why? What if?) are more powerful than closed questions (yes/no). A question like ''Why is this building taller than the others?'' leads to more learning than ''Is this building tall?'' Practice turning any observation into a question.","items":["Open questions start with How, Why, What if","Closed questions can be answered with yes/no","Follow-up questions dig deeper","There are no stupid questions — only unasked ones"]}', 'critical_thinking', 2, 8, true, 'independent'),
('Pattern Recognition', '{"text":"Our brains are pattern-finding machines. Patterns appear in nature (spirals, symmetry, branching), in numbers (sequences, ratios), and in human behavior (routines, traffic flow). Recognizing patterns helps you make predictions and solve problems. But be careful — sometimes we see patterns that aren''t really there!","items":["Look for repetition, symmetry, and sequences","Patterns help us predict what comes next","Not all patterns are meaningful (coincidence exists)","Test your pattern by looking for exceptions"]}', 'critical_thinking', 2, 8, true, 'independent'),
('Cause and Effect', '{"text":"Every event has causes (what made it happen) and effects (what happened because of it). A tree fell (effect) because of strong winds (cause). But causes can be complex — maybe the tree was already weakened by disease. Look for chains of cause and effect, and ask: is this the ONLY cause, or are there multiple factors?","items":["One cause can have multiple effects","One effect can have multiple causes","Correlation does not equal causation","Look for the chain: cause → effect → new cause → new effect"]}', 'critical_thinking', 3, 9, true, 'independent'),
('Compare and Contrast', '{"text":"Comparing means finding similarities; contrasting means finding differences. This skill helps you understand things more deeply. When you compare two trees, two buildings, or two paths, you notice details you''d miss looking at just one. Use a Venn diagram (overlapping circles) to organize similarities and differences.","items":["Compare: how are they similar?","Contrast: how are they different?","Use categories to organize (size, color, age, purpose)","Venn diagrams help visualize overlap"]}', 'critical_thinking', 2, 7, true, 'independent'),
('Evidence-Based Reasoning', '{"text":"A claim is a statement you believe is true. Evidence is the data or observations that support your claim. Reasoning explains how the evidence supports the claim. Strong arguments have all three: Claim + Evidence + Reasoning (CER). ''This area gets a lot of foot traffic (claim) because the grass is worn down to dirt in a path (evidence), which shows many people walk the same route repeatedly (reasoning).''","items":["Claim: what you believe is true","Evidence: observable facts that support it","Reasoning: explains the connection","Stronger evidence = stronger argument"]}', 'critical_thinking', 4, 10, true, 'independent'),
('Perspective Taking', '{"text":"Different people see the same situation differently based on their experiences, needs, and values. A park might look like a play space to a child, a peaceful retreat to an adult, a work site to a groundskeeper, and a habitat to an ecologist. Considering multiple perspectives helps you understand complex issues and make better decisions.","items":["Everyone sees the world through their own lens","Ask: who else is affected by this?","Stakeholders: people with interest in an issue","Understanding perspectives ≠ agreeing with them"]}', 'critical_thinking', 4, 10, true, 'independent'),
('Systems Thinking', '{"text":"A system is a group of connected parts that work together. A school is a system (students, teachers, buildings, rules). A park is a system (plants, animals, water, visitors, maintenance). When one part of a system changes, it affects other parts. Systems thinkers ask: how do these parts connect? What happens if one part changes?","items":["Systems have interconnected parts","Changing one part affects others","Feedback loops: effects circle back to causes","Unintended consequences come from not seeing the whole system"]}', 'critical_thinking', 5, 12, true, 'independent'),

-- Reading & Writing primers (6)
('Descriptive Writing', '{"text":"Descriptive writing paints a picture with words. Use sensory details — what you see, hear, smell, feel, and (sometimes) taste. Instead of ''The tree was big,'' try ''The oak tree''s trunk was wider than two people could wrap their arms around, and its branches spread across the sky like a green umbrella.'' Specific details make writing come alive.","items":["Use all five senses","Replace vague words with specific ones","Show, don''t tell (describe actions and details)","Use comparisons (similes and metaphors)"]}', 'reading_writing', 2, 8, true, 'independent'),
('Haiku and Short Poetry', '{"text":"A haiku is a three-line poem from Japan. Line 1 has 5 syllables, line 2 has 7 syllables, and line 3 has 5 syllables. Haiku traditionally capture a moment in nature. Example: ''Morning dew glistens / on spider silk stretched between / two sleeping branches'' (5-7-5). The constraint of the form forces you to choose every word carefully.","items":["Line 1: 5 syllables","Line 2: 7 syllables","Line 3: 5 syllables","Capture one specific moment or image"]}', 'reading_writing', 3, 12, true, 'independent'),
('Narrative Writing', '{"text":"Every story has characters, a setting, a problem (conflict), and a solution (resolution). When you write about real places, you become both the character and the narrator. Good narrative writing includes: what happened (plot), how you felt (emotions), what you noticed (sensory details), and what you learned (reflection).","items":["Setting: where and when","Characters: who is involved","Conflict: the problem or challenge","Resolution: how it was solved or what was learned"]}', 'reading_writing', 3, 8, true, 'independent'),
('Reading Signs, Plaques, and Labels', '{"text":"The world is full of text to read — signs, plaques, labels, instructions, memorials, and informational displays. These texts are written for specific purposes: to inform, to warn, to commemorate, to direct. When you read a sign, ask: Who wrote this? For whom? What is its purpose? Is the information current?","items":["Informational signs: teach you something","Warning signs: keep you safe","Directional signs: help you navigate","Memorial plaques: honor people or events"]}', 'reading_writing', 2, 6, true, 'independent'),
('Persuasive Writing', '{"text":"Persuasive writing tries to convince the reader of something. It uses: a clear position (thesis), supporting evidence, logical reasoning, and sometimes emotional appeals. When observing the real world, you might form opinions about how things should be — persuasive writing lets you express and defend those opinions with evidence you''ve gathered.","items":["State your position clearly","Support with evidence and examples","Address counterarguments","End with a call to action"]}', 'reading_writing', 5, 12, true, 'independent'),
('Vocabulary in Context', '{"text":"When you encounter unfamiliar words on signs, plaques, or in clue text, use context clues to figure out the meaning. Look at the words around it, think about what makes sense, and consider the subject matter. For example, if a nature sign says ''deciduous trees shed their foliage in autumn,'' you can figure out that ''foliage'' means leaves from the context.","items":["Context clues: surrounding words give hints","Root words: parts of words you recognize","Word families: related words share meanings","When in doubt, try substituting a synonym"]}', 'reading_writing', 3, 8, true, 'independent'),

-- History & Community primers (5)
('Reading a Timeline', '{"text":"A timeline shows events in chronological order — earliest on the left, most recent on the right. Timelines help you see how long ago things happened, how events relate to each other, and the pace of change. When you visit historical places, you can create your own timeline of what happened there.","items":["Events are placed in order from oldest to newest","The spacing between events shows how much time passed","Parallel timelines show what was happening elsewhere","Timelines can cover days, years, centuries, or millennia"]}', 'history_community', 2, 8, true, 'independent'),
('Architectural Clues', '{"text":"Buildings tell stories about the people who built them. Old buildings might have ornate details carved by hand. Modern buildings use glass and steel. The style of a building can tell you roughly when it was built and what it was used for. Look for: materials (stone, brick, wood, concrete), decorations, window shapes, and roof styles.","items":["Materials tell you about available resources and era","Decorations reflect cultural values and wealth","Windows reveal construction technology of the time","Additions and changes show the building''s evolving story"]}', 'history_community', 3, 10, true, 'independent'),
('Community Infrastructure', '{"text":"Infrastructure is the basic systems a community needs to function: roads, water pipes, electrical lines, sewers, bridges, and public buildings. Most infrastructure is invisible — underground or inside walls. But you can find clues: manhole covers, fire hydrants, utility poles, storm drains. These systems represent enormous community investment and planning.","items":["Transportation: roads, sidewalks, bridges, transit","Utilities: water, sewer, electricity, internet","Public services: schools, libraries, fire stations","Green infrastructure: parks, trees, drainage"]}', 'history_community', 3, 8, true, 'independent'),
('Oral History and Memory', '{"text":"Not all history is written in books. Oral history is the practice of recording people''s memories, stories, and experiences. Every place has stories that only the people who were there can tell. When you visit a place, imagine the stories that have happened there — and consider whose stories are remembered and whose are forgotten.","items":["Primary sources: firsthand accounts from people who were there","Secondary sources: written by someone who studied the event","Oral traditions: stories passed down through generations","Every place has multiple stories depending on who tells them"]}', 'history_community', 4, 10, true, 'independent'),
('Public Art and Memorials', '{"text":"Communities choose to display art and build memorials that reflect their values and history. Public art can celebrate, provoke thought, beautify, or commemorate. When you encounter public art, ask: Who created this? When? Why was it placed here? Who or what does it honor? What message does it send to the community?","items":["Memorials honor people or events","Sculptures can be abstract or representational","Murals often tell community stories","Art placement is a deliberate choice"]}', 'history_community', 3, 10, true, 'independent');

-- ── TASKS: Science & Nature (25) ─────────────────────────────

INSERT INTO public.tasks (title, description, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency) VALUES
-- Observation tasks
('Species Count', 'Count different species in your immediate area', 'science_nature', 'numeric_entry', '{"question":"Look around you carefully. How many DIFFERENT types of plants can you see within 10 meters? Count each species only once, not each individual plant.","unit":"species","hints":["Look at ground level — small plants count too","Check for mosses, grasses, and wildflowers","Trees and shrubs are separate species"]}', 2, 6, 1, true, 'independent'),
('Sound Map', 'Record and classify sounds around you', 'science_nature', 'data_collection', '{"question":"Sit quietly for 60 seconds. Record every sound you hear. Classify each as: Natural (N), Human (H), or Mechanical (M). How many of each type did you hear?","hints":["Close your eyes to focus on hearing","Wind, birds, and insects are natural","Voices and footsteps are human","Cars, machines, and phones are mechanical"]}', 2, 8, 2, true, 'independent'),
('Cloud Identification', 'Identify the cloud type overhead', 'science_nature', 'multiple_choice', '{"question":"Look at the sky. What type of clouds do you see right now?","options":["Cumulus (puffy, like cotton balls)","Stratus (flat, gray blanket)","Cirrus (thin, wispy, high up)","Cumulonimbus (tall, dark, storm clouds)","Clear sky (no clouds)"],"correct_answer":"","hints":["Cumulus clouds are individual and puffy","Stratus clouds cover the whole sky like a sheet","Cirrus clouds look like thin white streaks very high up","Cumulonimbus are very tall and often dark at the bottom"]}', 3, 8, 2, true, 'independent'),
('Shadow Length Measurement', 'Measure and record shadow data', 'science_nature', 'numeric_entry', '{"question":"Find a vertical object (pole, post, stick) and measure its shadow length in centimeters. Then measure the object''s height. What is the ratio of shadow length to object height?","unit":"ratio","hints":["Shadow length changes throughout the day","At noon, shadows are shortest","Use a tape measure or estimate with your arm span","Divide shadow length by object height for the ratio"]}', 3, 8, 2, true, 'independent'),
('Leaf Classification', 'Classify leaves by their characteristics', 'science_nature', 'sorting_ordering', '{"question":"Find 4 different leaves near you. Sort them by size from smallest to largest. Then classify each leaf shape.","items":["Simple leaf (one blade)","Compound leaf (multiple leaflets)","Needle-shaped (conifers)","Heart-shaped or round"],"hints":["Simple leaves have one continuous blade","Compound leaves have multiple small leaflets on one stem","Needle leaves are thin and pointed","Look at both the shape and edge pattern"]}', 2, 6, 2, true, 'independent'),
('Temperature Check', 'Measure temperature in sun vs shade', 'science_nature', 'numeric_entry', '{"question":"If you have a thermometer (or phone weather app), record the temperature. Estimate: is it warmer in the sun or shade at your location? By how many degrees do you think they differ?","unit":"°C or °F difference","hints":["Direct sunlight heats surfaces significantly","Shade temperature is closer to official air temperature","Dark surfaces absorb more heat","Wind reduces the felt temperature difference"]}', 3, 8, 2, true, 'independent'),
('Erosion Evidence Hunt', 'Find and document signs of erosion', 'science_nature', 'photo_observation', '{"question":"Find evidence of erosion within 20 meters of you. Take a photo and describe: What type of erosion is it (water, wind, ice, or human)? What evidence tells you?","hints":["Look for exposed roots, worn paths, gullies","Smooth rounded rocks suggest water erosion","Undercut banks show water flow erosion","Bare patches on hills suggest rain erosion"]}', 3, 8, 2, true, 'independent'),
('Pollinator Watch', 'Observe and count pollinators', 'science_nature', 'data_collection', '{"question":"Watch any flowering plant for 3 minutes. Count every insect or animal that visits. Record: how many visitors? What types (bee, butterfly, fly, beetle, bird, other)?","hints":["Sit still and be patient — movement scares pollinators","Bees are fuzzy; flies have large eyes and short antennae","Butterflies land with wings closed; moths with wings open","Some flowers attract specific pollinators"]}', 3, 8, 2, true, 'independent'),
('Symbiosis Spotter', 'Identify symbiotic relationships in nature', 'science_nature', 'short_text', '{"question":"Look for an example of two different species interacting near you. Describe what you see: which species? How do they interact? Is it mutualism (both benefit), commensalism (one benefits, other unaffected), or parasitism (one benefits, other harmed)?","correct_answer":null,"hints":["Lichen on rocks = mutualism (fungus + algae)","Birds eating insects off animals = mutualism","Moss on a tree = commensalism (moss benefits, tree unaffected)","Vines strangling a tree = parasitism"]}', 5, 10, 3, true, 'independent'),
('Micro-habitat Investigation', 'Study a tiny ecosystem up close', 'science_nature', 'creative_writing', '{"question":"Find a micro-habitat: under a rock, in a crack, at the base of a tree, or in a puddle. Observe it closely for 2 minutes. Write a detailed description of this tiny world — what lives there, what conditions exist, and how the organisms might depend on each other.","hints":["Get low — use your phone camera to zoom in","Note moisture level, light, temperature","Count different organisms you see","Think about what each organism needs to survive"]}', 4, 10, 3, true, 'independent'),
-- More science tasks
('Decomposition Detective', 'Find and analyze decomposing material', 'science_nature', 'photo_observation', '{"question":"Find something that is decomposing (a fallen leaf, rotting wood, decaying fruit). Take a photo. What stage of decomposition is it in? What organisms are helping break it down?","hints":["Early decomposition: color change, softening","Middle: visible fungi, insect activity","Late: crumbling, soil-like texture","Decomposers include fungi, bacteria, insects, and worms"]}', 3, 8, 2, true, 'independent'),
('Animal Sign Tracker', 'Find evidence of animals without seeing them', 'science_nature', 'short_text', '{"question":"Without seeing an actual animal, find 3 signs that animals are or were present near you. What signs did you find? What animal do you think left each sign?","correct_answer":null,"hints":["Tracks or footprints in mud or dust","Nests, burrows, or webs","Droppings or pellets","Chewed leaves, bark damage, or feathers"]}', 2, 7, 2, true, 'independent'),
('Soil Comparison', 'Compare soil samples from two spots', 'science_nature', 'data_collection', '{"question":"Examine soil from two different spots near you (e.g., under a tree vs. open ground). Compare: color, texture (sandy, silty, clay), moisture, and any living things you find. Which spot has healthier soil?","hints":["Dark soil usually has more organic matter","Sandy soil feels gritty; clay feels smooth and sticky","Healthy soil has worms, roots, and a fresh earthy smell","Compacted soil (hard, no life) is less healthy"]}', 3, 8, 3, true, 'independent'),
('Plant Adaptation Survey', 'Identify how plants adapt to their environment', 'science_nature', 'multiple_choice', '{"question":"Look at the plants near you. Which adaptation is MOST visible in the plants at your current location?","options":["Thick waxy leaves (conserve water)","Broad thin leaves (maximize sunlight)","Thorns or spines (defense)","Deep or spreading roots (visible above ground)","Flexible stems (wind resistance)"],"correct_answer":"","hints":["Dry areas: thick leaves, spines, water storage","Shady areas: large, thin leaves","Windy areas: low growth, flexible stems","Each adaptation solves an environmental challenge"]}', 4, 9, 2, true, 'independent'),
('Food Web Sketch', 'Draw a food web from organisms you observe', 'science_nature', 'sketch_draw', '{"question":"Observe the organisms at your location. Sketch a simple food web showing at least 3 producers and 2 consumers you can actually see or have evidence of. Draw arrows showing energy flow (from food source → consumer).","hints":["Producers: any green plants, algae, grass","Primary consumers: insects, snails, herbivorous birds","Secondary consumers: spiders, lizards, predatory birds","Decomposers: fungi, worms (draw them at the bottom)"]}', 4, 9, 3, true, 'independent'),
('Weather Forecast Challenge', 'Predict weather using natural signs', 'science_nature', 'short_text', '{"question":"Using ONLY natural observations (no phone!), predict the weather for the next 6 hours. What clues are you using? Consider: cloud type and movement, wind direction and speed, air humidity, animal behavior, and sky color.","correct_answer":null,"hints":["Red sky in morning = rain likely; red sky at evening = fair weather","Increasing clouds from west = weather change coming","Birds flying low = low pressure (rain likely)","Calm after gusty wind often means a storm front passing"]}', 5, 12, 3, true, 'independent'),
('Biodiversity Quadrat Survey', 'Measure biodiversity in a square meter', 'science_nature', 'data_collection', '{"question":"Mark out a 1m × 1m square on the ground (use sticks, rope, or just estimate). Count every DIFFERENT species you can find inside it — plants, insects, fungi, anything alive. Record each species and how many individuals you see.","hints":["Look at different layers: ground, low plants, tall plants","Check under leaves and on stems for insects","Include mosses, lichens, and fungi","More species = higher biodiversity"]}', 5, 12, 3, true, 'independent'),
('UV and Shade Analysis', 'Analyze sun exposure patterns', 'science_nature', 'data_collection', '{"question":"Observe the light and shadow patterns at your location. What percentage of the ground is in shade vs. direct sunlight right now? Sketch or describe the shadow pattern and predict how it will change in 2 hours.","hints":["Shadows move as the sun moves across the sky","In the Northern Hemisphere, shadows shift from west to east","Trees and buildings create different shadow patterns","Morning shadows are long; midday shadows are short"]}', 4, 10, 3, true, 'independent'),
('Rock and Mineral ID', 'Identify rock types at your location', 'science_nature', 'multiple_choice', '{"question":"Find a rock or stone near you. Based on its appearance, what type do you think it is?","options":["Igneous (glassy, small crystals, from volcanic activity)","Sedimentary (layers, fossils possible, from compressed sediment)","Metamorphic (folded bands, shiny minerals, from heat/pressure)","Concrete or asphalt (human-made, not a natural rock)","I''m not sure — describe what you see"],"correct_answer":"","hints":["Igneous: often dark colored, sometimes has visible crystals","Sedimentary: look for layers, often lighter colored","Metamorphic: often has wavy bands or shiny flecks","Scratch test: limestone (sedimentary) scratches easily; granite (igneous) does not"]}', 4, 10, 2, true, 'independent'),
('Ecosystem Health Assessment', 'Rate the health of the ecosystem around you', 'science_nature', 'data_collection', '{"question":"Assess the health of the ecosystem at your location. Rate each factor 1-5 (1=poor, 5=excellent): Plant diversity, Animal signs present, Soil quality, Water availability, Human impact level (5=minimal impact). Total your score out of 25.","hints":["Diverse plants suggest healthy soil and water","Multiple animal signs = functioning food web","Dark, crumbly soil with organisms = healthy","Litter, erosion, and invasive species lower the score"]}', 5, 12, 3, true, 'independent'),
-- Additional science (5 more to reach 25)
('Texture Collection', 'Find and describe 5 different textures', 'science_nature', 'data_collection', '{"question":"Find 5 different natural textures within reach. For each one, record: what it is, how it feels, and one word that describes the texture (rough, smooth, bumpy, furry, slimy, etc.).","hints":["Tree bark, leaves, rocks, soil, petals all have different textures","Compare rough vs. smooth surfaces","Wet and dry versions of the same material feel different","Texture can help identify species"]}', 1, 5, 1, true, 'independent'),
('Living vs Non-Living Sort', 'Classify objects as living or non-living', 'science_nature', 'sorting_ordering', '{"question":"Look around you. Find examples to sort into categories.","items":["Living (or once living)","Non-living natural (rock, water, soil)","Human-made"],"hints":["Living things grow, reproduce, need energy","Dead leaves were once living","Rocks and water are natural but never alive","Plastic, metal, and concrete are human-made"]}', 1, 4, 1, true, 'independent'),
('Insect Count', 'Count and classify insects for 2 minutes', 'science_nature', 'numeric_entry', '{"question":"Observe one small area (about 1 meter square) for 2 minutes. How many insects did you see? Include ants, beetles, flies, spiders (technically arachnids), and any other small creatures.","unit":"insects","hints":["Look on leaves, under edges, on the ground","Ants often travel in lines — follow the trail","Check flowers for bees and butterflies","Early morning and late afternoon are peak insect times"]}', 1, 6, 1, true, 'independent'),
('Nature Color Palette', 'Find specific colors in nature', 'science_nature', 'photo_observation', '{"question":"Nature has every color. Take a photo that includes at least 5 different colors found in nature (not human-made objects). Name each color and what natural object displays it.","hints":["Green: leaves and stems","Brown: bark, soil, dead leaves","Blue: sky, some flowers, water reflections","Yellow: flowers, autumn leaves, sunlight","Red, orange, purple: flowers, berries, autumn leaves"]}', 1, 5, 1, true, 'independent'),
('Habitat Requirements', 'Identify what organisms need at this location', 'science_nature', 'short_text', '{"question":"Choose one living organism you can see. Describe its habitat requirements: What does it need to survive at this location? Consider: food/nutrients, water, shelter, space, sunlight, and any specific conditions.","correct_answer":null,"hints":["Plants need: sunlight, water, nutrients from soil, space","Animals need: food, water, shelter, space","Think about WHY this organism lives HERE specifically","What would happen if one requirement was removed?"]}', 3, 8, 2, true, 'independent'),

-- ── TASKS: Math in the Real World (25) ───────────────────────

('Estimation Challenge', 'Estimate distances using body measurements', 'math_real_world', 'numeric_entry', '{"question":"Estimate the distance from where you are standing to the nearest large object (tree, building, pole) in meters. Then walk to it counting your steps. Convert steps to meters (1 step ≈ 0.7m). How close was your estimate?","unit":"meters","hints":["Average adult step is about 0.7 meters","Child step is about 0.5 meters","Count your steps carefully","Estimate FIRST, then measure"]}', 2, 6, 1, true, 'independent'),
('Height Estimation', 'Estimate the height of a tall object', 'math_real_world', 'numeric_entry', '{"question":"Pick the tallest object near you (tree, building, pole). Estimate its height in meters using this trick: have a friend stand next to it (or use yourself). How many of that person''s height fits into the object''s height? Multiply.","unit":"meters","hints":["Average adult is about 1.7 meters tall","A door is about 2 meters tall","A two-story building is about 6-8 meters","Compare to things you know the height of"]}', 2, 7, 2, true, 'independent'),
('Shape Scavenger Hunt', 'Find geometric shapes in the environment', 'math_real_world', 'data_collection', '{"question":"In 3 minutes, find as many different geometric shapes as you can. Record what shape and where you found it. Aim for at least 8 different shapes.","hints":["Circles: wheels, clocks, manhole covers, signs","Rectangles: windows, doors, bricks, screens","Triangles: roof peaks, signs, support structures","Hexagons: nuts, bolts, honeycomb patterns"]}', 2, 6, 1, true, 'independent'),
('Symmetry Spotter', 'Find examples of symmetry', 'math_real_world', 'photo_observation', '{"question":"Find 3 examples of symmetry near you. Take a photo of the best one. Is it line symmetry (mirror image) or rotational symmetry (looks the same when rotated)?","hints":["Leaves often have line symmetry down the center","Flowers often have rotational symmetry","Buildings frequently have vertical line symmetry","Snowflakes have 6-fold rotational symmetry"]}', 2, 7, 2, true, 'independent'),
('Fraction Finder', 'Find real-world fractions', 'math_real_world', 'short_text', '{"question":"Find something near you that can be divided into fractions. What fraction of it is one color vs another? Or what fraction is in shade vs sun? Describe your fraction and what it represents.","correct_answer":null,"hints":["A bench that is 1/3 in shade and 2/3 in sun","A garden that is 3/4 flowers and 1/4 vegetables","A parking lot that is 2/5 full","Look for natural divisions"]}', 3, 6, 2, true, 'independent'),
('Angle Hunt', 'Find and estimate angles in the environment', 'math_real_world', 'data_collection', '{"question":"Find 5 different angles in your surroundings. For each, record: where you found it, estimate the angle in degrees, and classify it (acute <90°, right =90°, obtuse >90°, straight =180°).","hints":["Building corners are usually 90° (right angles)","Tree branches form various angles with the trunk","Stairs create specific angles","A clock at 3:00 shows a 90° angle"]}', 3, 8, 2, true, 'independent'),
('Perimeter Walk', 'Measure the perimeter of an area by walking', 'math_real_world', 'numeric_entry', '{"question":"Choose a defined area near you (a garden bed, basketball court, parking space, etc.). Walk around its perimeter counting your steps. Convert to meters (1 step ≈ 0.7m). What is the approximate perimeter?","unit":"meters","hints":["Walk at a consistent pace for accurate counting","Count each side separately","For irregular shapes, follow the edge closely","Perimeter = total distance around the edge"]}', 3, 7, 2, true, 'independent'),
('Area Estimation', 'Estimate the area of an irregular space', 'math_real_world', 'numeric_entry', '{"question":"Estimate the area of an irregular shape near you (a puddle, shadow, garden bed, or worn patch of ground). Use the grid method: imagine 1m × 1m squares covering it. Count full squares and half-squares.","unit":"square meters","hints":["Count full squares inside the shape","Count partial squares — if more than half inside, count as 1","Area = number of squares","For very irregular shapes, break into smaller regular shapes"]}', 4, 8, 3, true, 'independent'),
('Pattern Sequence', 'Identify and extend a pattern', 'math_real_world', 'short_text', '{"question":"Find a repeating pattern in your environment (bricks, tiles, fence posts, tree spacing, etc.). Describe the pattern and predict what the next 3 elements would be. What is the rule?","correct_answer":null,"hints":["Look at colors, shapes, sizes, or spacing","Brickwork often has ABABAB patterns","Fence posts have regular spacing","Nature has patterns too — leaf arrangement, bark ridges"]}', 2, 6, 2, true, 'independent'),
('Scale Drawing Challenge', 'Create a scale drawing of something you see', 'math_real_world', 'sketch_draw', '{"question":"Choose a simple object or area near you. Create a scale drawing on your paper. Write your scale (e.g., 1 cm = 1 m). Include measurements and labels.","hints":["Pick a simple shape first","Measure the real dimensions","Decide on a scale that fits your paper","Label every measurement in your drawing"]}', 4, 8, 3, true, 'independent'),
('Ratio and Proportion', 'Find ratios in the real world', 'math_real_world', 'numeric_entry', '{"question":"Count two types of objects near you (e.g., deciduous vs. evergreen trees, or parked cars vs. empty spaces). What is the ratio? Express it in simplest form.","unit":"ratio (e.g., 3:2)","hints":["Count each type carefully","Write as a:b then simplify","Find the greatest common factor","Ratios help compare without knowing totals"]}', 4, 8, 2, true, 'independent'),
('Speed Calculation', 'Measure walking speed', 'math_real_world', 'numeric_entry', '{"question":"Mark a distance of 20 meters (about 28 steps). Time yourself walking it at normal pace. Calculate your walking speed in meters per second (speed = distance ÷ time). Then convert to km/h (multiply by 3.6).","unit":"km/h","hints":["Average walking speed is 4-5 km/h","20 meters at normal pace takes about 15-20 seconds","Speed = distance ÷ time","To convert m/s to km/h: multiply by 3.6"]}', 5, 10, 2, true, 'independent'),
('Percentage Problems', 'Calculate percentages from real observations', 'math_real_world', 'numeric_entry', '{"question":"Look at the ground surface within 5 meters of you. Estimate what percentage is: paved/concrete, grass/vegetation, bare soil, and other. Your percentages should add up to 100%.","unit":"percent","hints":["Divide the area mentally into 10 equal sections","Count how many sections each surface covers","Each section = 10%","Check: all percentages must add to 100%"]}', 4, 8, 2, true, 'independent'),
('Volume Estimation', 'Estimate the volume of an object', 'math_real_world', 'numeric_entry', '{"question":"Find a 3D object near you (trash can, planter, mailbox, boulder). Estimate its volume in cubic centimeters or cubic meters. What shape does it most resemble (cylinder, rectangular prism, sphere)?","unit":"cubic cm or cubic m","hints":["Cylinder: V = π × r² × h","Rectangular prism: V = l × w × h","Sphere: V = 4/3 × π × r³","Break complex shapes into simpler ones"]}', 5, 10, 3, true, 'independent'),
('Data Collection and Graphing', 'Collect data and describe how to graph it', 'math_real_world', 'data_collection', '{"question":"Choose something to count or measure that varies (e.g., height of plants, number of people per minute, colors of vehicles). Collect at least 10 data points. Describe what type of graph would best display your data and why (bar, line, pie, scatter).","hints":["Bar graph: comparing categories","Line graph: showing change over time","Pie chart: showing parts of a whole","Scatter plot: showing relationship between two variables"]}', 5, 10, 3, true, 'independent'),
('Mental Math Race', 'Solve real-world math problems', 'math_real_world', 'numeric_entry', '{"question":"Look at a rectangular surface near you (sign, window, section of wall). Estimate its length and width in centimeters. Calculate the area mentally. Now calculate: how many sticky notes (7.6 cm × 7.6 cm) would it take to cover this surface?","unit":"sticky notes","hints":["Estimate length and width first","Area = length × width","Sticky note area = 7.6 × 7.6 ≈ 58 sq cm","Divide total area by sticky note area"]}', 4, 8, 3, true, 'independent'),
('Fibonacci in Nature', 'Find Fibonacci numbers in natural objects', 'math_real_world', 'photo_observation', '{"question":"The Fibonacci sequence (1, 1, 2, 3, 5, 8, 13, 21...) appears frequently in nature. Find a flower, pinecone, or spiral and count the petals, scales, or spiral arms. Is the number in the Fibonacci sequence? Take a photo.","hints":["Daisies often have 13, 21, or 34 petals","Pinecones have 8 and 13 spirals","Sunflower seeds spiral in 34 and 55","Lilies have 3 petals, buttercups have 5"]}', 5, 12, 3, true, 'independent'),
('Counting and Multiplication', 'Use multiplication to count large groups', 'math_real_world', 'numeric_entry', '{"question":"Find a large group of similar objects (bricks in a wall, tiles on a floor, leaves on a branch). Instead of counting every one, count the rows and columns (or sections) and multiply to estimate the total.","unit":"objects","hints":["Count one row, then count how many rows","Multiply: total ≈ items per row × number of rows","This works for grids, arrays, and regular patterns","For irregular groups, divide into sections and add"]}', 2, 5, 1, true, 'independent'),
('Money Math', 'Calculate costs from real-world prices', 'math_real_world', 'numeric_entry', '{"question":"If you can see any prices (on a menu, sign, or vending machine), pick two items. Calculate: the total for both, the difference between them, and how much change you would get from $20.","unit":"dollars","hints":["Add prices carefully, lining up decimal points","Subtract the smaller from the larger for difference","Change = amount paid − total cost","Round to estimate, then calculate exactly"]}', 2, 6, 2, true, 'independent'),
('Coordinate Grid Walk', 'Navigate using a coordinate system', 'math_real_world', 'short_text', '{"question":"Create a simple coordinate grid. Starting from where you stand (0,0), walk 5 steps north (+y) and 3 steps east (+x). What are your coordinates? Now describe how to get back to (0,0) using coordinate directions.","correct_answer":null,"hints":["North = +y direction","East = +x direction","Your position after the walk is (3, 5)","To return: go 3 steps west and 5 steps south = (-3, -5)"]}', 4, 8, 2, true, 'independent'),
('Time and Rate', 'Calculate rates from observations', 'math_real_world', 'numeric_entry', '{"question":"Count how many people walk past a point in exactly 2 minutes. Calculate the rate in people per minute. Predict: how many people would pass in one hour at this rate?","unit":"people per hour","hints":["Rate = count ÷ time","People per minute = count ÷ 2","People per hour = rate × 60","This assumes the rate stays constant (it may not)"]}', 4, 8, 2, true, 'independent'),
('Weight Estimation', 'Estimate the weight of natural objects', 'math_real_world', 'sorting_ordering', '{"question":"Find 5 natural objects you can hold (rock, stick, pinecone, leaf, etc.). Sort them by estimated weight from lightest to heaviest.","items":["Lightest","Light","Medium","Heavy","Heaviest"],"hints":["Hold one in each hand to compare","A small rock feels heavier than a stick of the same size","Wet objects are heavier than dry ones","Density matters: same size but different weight = different density"]}', 1, 5, 1, true, 'independent'),
('Graph Interpretation', 'Read a graph from collected data', 'math_real_world', 'multiple_choice', '{"question":"You counted 3 red things, 7 green things, 2 blue things, and 5 brown things near you. If you made a bar graph, which statement would be true?","options":["Green has the tallest bar","Red and blue together equal brown","There are 17 things total","Brown is the most common color"],"correct_answer":"Green has the tallest bar","hints":["Count the totals: 3+7+2+5=17","Green (7) is the largest number","Red+Blue = 3+2 = 5 = Brown","The tallest bar represents the largest value"]}', 2, 5, 1, true, 'independent'),
('Decimal Measurement', 'Measure precisely using decimals', 'math_real_world', 'numeric_entry', '{"question":"Find something small enough to measure with your hand. Using your phone or a ruler, measure its length as precisely as possible in centimeters, including decimals (e.g., 7.3 cm). What did you measure and how long is it?","unit":"cm","hints":["Line up the 0 mark carefully","Read between the marks for decimals","Estimate the last decimal place","Record to one decimal place"]}', 3, 6, 2, true, 'independent'),

-- ── TASKS: Geography & Maps (15) ─────────────────────────────

('Cardinal Directions', 'Identify cardinal directions without a compass', 'geography_maps', 'multiple_choice', '{"question":"Without using your phone, determine which direction is NORTH. How did you figure it out?","options":["Used the sun position (east in morning, west in evening)","Found a shadow pointing roughly north (at midday)","Noticed moss growing on the north side of something","Used a landmark I already know the direction of","I''m not sure — I need help"],"correct_answer":"","hints":["At noon, the sun is roughly south (in Northern Hemisphere)","Shadows at noon point roughly north","Satellite dishes often point south","Use any known landmark as reference"]}', 2, 7, 1, true, 'independent'),
('Map Your Path', 'Draw a map of the route you just walked', 'geography_maps', 'sketch_draw', '{"question":"Draw a simple map of the path you took to get to this location. Include: your starting point, any turns, landmarks along the way, and your current position. Add a compass rose (N/S/E/W) and an approximate scale.","hints":["Start with the overall shape of your route","Mark important landmarks (buildings, intersections)","Draw the compass rose in the corner","Scale: estimate total distance and fit it to your paper"]}', 3, 8, 2, true, 'independent'),
('Elevation Change', 'Estimate elevation change along a path', 'geography_maps', 'short_text', '{"question":"Look at the terrain around you. Are you on flat ground, a slope, a hilltop, or in a valley? Describe the elevation change you can see in all four directions. Which direction goes uphill? Which goes downhill?","correct_answer":null,"hints":["Look for water flow direction (water flows downhill)","Stairs and ramps indicate elevation change","Buildings may be at different ground levels","Trees and vegetation patterns can indicate slope"]}', 3, 8, 2, true, 'independent'),
('Landmark Description', 'Describe a landmark for someone who cannot see it', 'geography_maps', 'audio_response', '{"question":"Choose the most prominent landmark visible from where you stand. Record a description that would help someone who has never been here find it. Include: direction, distance, size, color, shape, and any identifying features.","hints":["Start with direction and distance","Describe size relative to other objects","Mention color, shape, and distinctive features","Think about what makes it unique"]}', 2, 7, 2, true, 'independent'),
('Distance Estimation', 'Estimate distance to visible landmarks', 'geography_maps', 'numeric_entry', '{"question":"Pick an object you can see but cannot easily walk to (across a field, down a road, on a hill). Estimate the distance to it in meters. What method did you use?","unit":"meters","hints":["100m ≈ length of a football field","If you can clearly see someone''s face: < 50m","If you can see a person but not details: 100-200m","If a person looks small: > 300m"]}', 3, 8, 2, true, 'independent'),
('Land Use Classification', 'Classify how land is used around you', 'geography_maps', 'data_collection', '{"question":"Looking in all directions from where you stand, classify the land use you can see. Estimate what percentage of visible area is: Residential, Commercial, Recreational/Park, Agricultural, Natural/Wild, Transportation (roads, parking).","hints":["Residential: houses, apartments","Commercial: shops, offices, restaurants","Recreational: parks, playgrounds, sports fields","Transportation: roads, sidewalks, parking lots"]}', 4, 10, 2, true, 'independent'),
('Wayfinding Without GPS', 'Navigate to a described location using only directions', 'geography_maps', 'short_text', '{"question":"Without looking at any map or GPS, describe the route from your current location to the nearest source of drinking water (fountain, store, etc.). Use cardinal directions, distances, and landmarks in your description.","correct_answer":null,"hints":["Start with the direction: ''Head north...''","Use landmarks: ''Pass the large tree on your left...''","Include distance: ''Walk about 100 meters...''","Include turns: ''Turn east at the intersection''"]}', 3, 8, 2, true, 'independent'),
('Map Symbol Design', 'Create map symbols for your location', 'geography_maps', 'sketch_draw', '{"question":"Design 5 simple map symbols for features at your location. Each symbol should be small, clear, and instantly recognizable. Draw each symbol and label what it represents.","hints":["Good symbols are simple and distinctive","Use shapes, lines, and dots","Standard symbols: P for parking, cross for medical","Your symbols should make sense without the label"]}', 3, 8, 2, true, 'independent'),
('Border and Boundary ID', 'Identify boundaries in your environment', 'geography_maps', 'data_collection', '{"question":"Boundaries are everywhere. Find 5 different types of boundaries near you: physical (fence, wall), painted (lines, zones), natural (river, hedge), implied (change in surface), or legal (property markers). Record each one.","hints":["Fences and walls are obvious boundaries","Painted lines on roads create lanes and zones","A change from grass to pavement is a boundary","Some boundaries are invisible but understood (personal space)"]}', 3, 8, 2, true, 'independent'),
('Human Migration Patterns', 'Observe how people move through a space', 'geography_maps', 'data_collection', '{"question":"Watch the area for 5 minutes. Draw arrows showing the main paths people take. Where do paths converge? Where do people stop? What features attract or repel foot traffic?","hints":["Worn grass shows where people actually walk (vs. designed paths)","Entrances, benches, and shade attract people","Barriers redirect foot traffic","Rush times show different patterns than quiet times"]}', 5, 12, 3, true, 'independent'),
('Compass Bearing Challenge', 'Use bearings to describe directions precisely', 'geography_maps', 'numeric_entry', '{"question":"Using your phone compass (or estimating from sun position), what is the bearing in degrees from where you stand to the most visible landmark? Bearings go from 0° (north) clockwise to 359°.","unit":"degrees","hints":["North = 0° (or 360°)","East = 90°","South = 180°","West = 270°"]}', 5, 12, 3, true, 'independent'),
('Satellite vs Ground View', 'Compare what you see with a satellite view', 'geography_maps', 'short_text', '{"question":"Imagine you are looking down at your location from a satellite. Describe what you think it would look like from directly above. What shapes, colors, and patterns would be visible? What would you NOT be able to see from above?","correct_answer":null,"hints":["Trees look like green circles/blobs from above","Buildings show their roof shape","Roads appear as gray lines or rectangles","You can''t see signs, doors, or anything under cover"]}', 3, 8, 2, true, 'independent'),
('Cultural Landscape Reading', 'Identify how culture shapes the landscape', 'geography_maps', 'team_debate', '{"question":"Look at your surroundings. What can you learn about the community''s values and priorities from how this space is designed? Consider: What is prioritized (cars vs. pedestrians)? What is maintained? What languages appear on signs? Discuss with your team.","hints":["Wide sidewalks and bike lanes = pedestrian-friendly values","Public art and gardens = aesthetic priorities","Sign languages reflect the community''s diversity","What''s missing can be as telling as what''s present"]}', 6, 12, 3, true, 'independent'),
('GPS Coordinate Recording', 'Record and understand GPS coordinates', 'geography_maps', 'numeric_entry', '{"question":"Using your phone, find your exact GPS coordinates (latitude and longitude). Record both to 4 decimal places. Which number is latitude and which is longitude? What do the numbers tell you about where you are on Earth?","unit":"coordinates","hints":["Latitude first, longitude second","Positive latitude = Northern Hemisphere","Negative longitude = Western Hemisphere","4 decimal places = accurate to about 11 meters"]}', 5, 12, 2, true, 'independent'),
('Route Optimization', 'Find the most efficient route between points', 'geography_maps', 'short_text', '{"question":"You need to visit 4 specific spots visible from here and return to this point. Describe the most efficient route (shortest total distance). Why is this route better than alternatives?","correct_answer":null,"hints":["Avoid backtracking — visit points in a loop","The nearest-neighbor approach: always go to the closest unvisited point","Sometimes a slightly longer leg saves distance overall","This is a version of the famous ''Traveling Salesman Problem''"]}', 6, 12, 3, true, 'independent'),

-- ── TASKS: Critical Thinking (25) ────────────────────────────

('What Changed Here?', 'Observe and infer recent changes', 'critical_thinking', 'short_text', '{"question":"Something at this location has changed recently (within the last day or week). Find evidence of the change and explain what you think happened. What clues told you?","correct_answer":null,"hints":["Fresh dirt or new plants suggest recent gardening","Wet ground on a dry day means recent watering","Tire tracks or footprints show recent activity","New signs, paint, or construction materials indicate work"]}', 2, 8, 2, true, 'independent'),
('Observation Challenge: 30 Seconds', 'Rapid observation test', 'critical_thinking', 'numeric_entry', '{"question":"Close your eyes for 10 seconds. Open them and look around for exactly 30 seconds. Close your eyes again. How many distinct objects can you remember seeing? List them mentally, then enter your count.","unit":"objects","hints":["Focus on categories: natural, built, moving, still","Look systematically: left to right, near to far","Colors and shapes are easier to remember","Practice improves observation skills"]}', 2, 8, 1, true, 'independent'),
('Mystery Object', 'Use deduction to identify a hidden purpose', 'critical_thinking', 'short_text', '{"question":"Find an object near you whose purpose is not immediately obvious (a valve, a bracket, a marking, a pipe, etc.). Describe it in detail. Based on your observations, what do you think its purpose is? What evidence supports your answer?","correct_answer":null,"hints":["Look at material, shape, location, and connections","Infrastructure often has non-obvious components","Markings may indicate function (color codes, labels)","Consider: what problem does this solve?"]}', 3, 10, 2, true, 'independent'),
('Design Detective', 'Analyze why something was designed the way it was', 'critical_thinking', 'short_text', '{"question":"Choose a designed object or space near you (bench, path, sign, planter, etc.). Why was it designed this specific way? What problem does the design solve? What trade-offs were made? How could it be improved?","correct_answer":null,"hints":["Consider: who uses this? How often? In what weather?","Materials were chosen for a reason (cost, durability, look)","Placement was intentional — why here?","What would you change and why?"]}', 4, 12, 3, true, 'independent'),
('Two Truths and a Lie', 'Write observations where one is false', 'critical_thinking', 'creative_writing', '{"question":"Write three statements about what you can see from this spot. Two must be true observations and one must be a believable but false statement. Can your teammates figure out which one is the lie?","hints":["Make the lie plausible — close to truth","Base all three on real observable things","The best lies include real details with one wrong element","After sharing, explain which was the lie and why"]}', 3, 10, 2, true, 'independent'),
('Evidence Gathering', 'Collect evidence to support a claim', 'critical_thinking', 'data_collection', '{"question":"Claim: ''This location gets more foot traffic in one direction than another.'' Gather evidence for or against this claim. Observe for 3 minutes and record what you see. Does the evidence support, refute, or partially support the claim?","hints":["Count people in each direction","Look for worn paths, signs of heavy use","Consider time of day — patterns change","Evidence might be mixed — that''s okay"]}', 4, 10, 2, true, 'independent'),
('Before and After', 'Imagine this place at a different time', 'critical_thinking', 'creative_writing', '{"question":"Imagine this exact spot 100 years ago. What do you think it looked like? What clues at the current location help you guess? Now imagine it 100 years from now. Write 2-3 sentences for each time period.","hints":["Old trees may have been here 100 years ago","The land''s shape doesn''t change quickly","Building styles suggest construction era","Technology and materials will change in the future"]}', 4, 10, 3, true, 'independent'),
('Bias Check', 'Identify bias in your environment', 'critical_thinking', 'short_text', '{"question":"Look at the signs, art, names, and design choices in your environment. Whose perspective is represented? Whose might be missing? What assumptions do these choices reflect?","correct_answer":null,"hints":["Language choices on signs reflect assumptions about visitors","Statues and memorials honor certain people/events","Design choices (stairs vs ramps) show who was considered","What groups might feel unwelcome or unrepresented?"]}', 6, 12, 4, true, 'independent'),
('Cause Chain', 'Trace a chain of cause and effect', 'critical_thinking', 'sorting_ordering', '{"question":"Find an effect in your environment (a puddle, a crack, a worn spot, a plant growing in an unusual place). Create a chain of at least 4 causes that led to this effect. Put them in order from original cause to final effect.","items":["Original cause (earliest)","Second cause","Third cause","Final effect (what you observe)"],"hints":["Work backwards: what caused what you see?","Then what caused THAT?","Keep asking ''why?'' at least 3 times","Natural and human causes often interact"]}', 4, 10, 3, true, 'independent'),
('Risk Assessment', 'Evaluate safety at a location', 'critical_thinking', 'data_collection', '{"question":"Conduct a quick safety assessment of your immediate area. Rate each factor 1-5 (1=unsafe, 5=very safe): Ground surface condition, Visibility (can you see and be seen?), Traffic proximity, Tripping hazards, Weather protection. What is the total safety score out of 25?","hints":["Uneven surfaces are tripping hazards","Well-lit, open areas are generally safer","Distance from traffic matters","Nearby shelter from weather adds safety"]}', 3, 8, 2, true, 'independent'),
('Logical Deduction', 'Use clues to solve a logical puzzle', 'critical_thinking', 'multiple_choice', '{"question":"Look at the nearest building from where you are. Based ONLY on what you can observe from outside (no prior knowledge), what is its primary use?","options":["Residential (people live here)","Educational (classes/learning)","Commercial (business/shopping)","Recreational (sports/entertainment)","Industrial/Utility (manufacturing/services)"],"correct_answer":"","hints":["Window patterns suggest use (many small = residential, few large = commercial)","Signage gives direct clues","Entrance design indicates public vs private","Parking patterns suggest use type"]}', 3, 8, 2, true, 'independent'),
('What If?', 'Hypothesize about changing a variable', 'critical_thinking', 'team_debate', '{"question":"Pick one feature of your current location and imagine removing it (a tree, a path, a building, a water feature). How would the space change? What would happen to the people, animals, and plants that use this space? Discuss with your team.","hints":["Think about direct effects AND indirect effects","Who or what depends on this feature?","Would people behave differently?","Would the ecosystem change?"]}', 4, 12, 3, true, 'independent'),
('Trustworthy Sources', 'Evaluate the reliability of information', 'critical_thinking', 'short_text', '{"question":"Find a sign or plaque with factual information at your location. How trustworthy is this source? Consider: Who created it? When? Is it official or informal? Could the information be outdated? Is there any way to verify it?","correct_answer":null,"hints":["Government and institution signs tend to be more reliable","Date on the sign tells you if information might be outdated","Permanent signs are usually more vetted than temporary ones","Cross-reference with another source if possible"]}', 5, 12, 3, true, 'independent'),
('Analogy Building', 'Create analogies from observations', 'critical_thinking', 'creative_writing', '{"question":"Create 3 analogies based on what you see. An analogy compares two different things that share a key feature. Example: ''The tree''s root system is like the internet — both are networks that connect and share resources underground/invisibly.''","hints":["Look for structures that resemble other things","Think about function, not just appearance","''X is like Y because both...''","Good analogies reveal something non-obvious about both things"]}', 5, 12, 3, true, 'independent'),
('Prioritization Exercise', 'Rank the importance of features', 'critical_thinking', 'sorting_ordering', '{"question":"If this location had to be redesigned with a smaller budget, which 5 features would you keep and which would you remove? Rank the features from most essential to least essential.","items":["Most essential (keep no matter what)","Very important","Somewhat important","Nice to have","Would remove first"],"hints":["Essential = serves a safety or primary function","Consider who uses each feature most","Some features serve multiple purposes","Sometimes the least visible features are most important"]}', 5, 12, 3, true, 'independent'),
('Spot the Difference', 'Observe detailed differences between similar things', 'critical_thinking', 'data_collection', '{"question":"Find two similar objects near you (two trees, two benches, two signs, etc.). List at least 5 differences between them. Look carefully — the differences might be subtle!","hints":["Compare size, color, texture, age, condition","Look for wear patterns, damage, repairs","Check orientation and surroundings","Even mass-produced items develop unique characteristics"]}', 2, 7, 1, true, 'independent'),
('Problem Identification', 'Find a problem that needs solving', 'critical_thinking', 'short_text', '{"question":"Observe your surroundings carefully. Identify one problem that exists here — something that could be improved, fixed, or redesigned. Describe the problem and propose a realistic solution.","correct_answer":null,"hints":["Accessibility issues (can everyone use this space?)","Environmental issues (litter, erosion, water waste)","Design issues (confusing paths, poor signage)","Safety issues (poor lighting, tripping hazards)"]}', 3, 10, 2, true, 'independent'),
('Estimation Confidence', 'Practice calibrating your confidence', 'critical_thinking', 'data_collection', '{"question":"Make 5 estimation questions about things you can see (height of X, distance to Y, age of Z, number of W). For each, write: your estimate, your confidence (1-10), then try to find the actual answer. How well-calibrated is your confidence?","hints":["If you say confidence 8/10, you should be right about 80% of the time","Most people are overconfident — that''s normal","Practice improves calibration","Being uncertain is honest, not weak"]}', 5, 12, 3, true, 'independent'),
('Inference Chain', 'Make layered inferences from a single observation', 'critical_thinking', 'short_text', '{"question":"Find one small detail in your environment. Make 3 inferences from it, each building on the last. Example: ''The paint is peeling (observation) → This wall is old or poorly maintained (inference 1) → This might be a low-priority area for the owner (inference 2) → Budget constraints may affect this whole building (inference 3).''","correct_answer":null,"hints":["Start with a very specific observation","Each inference should logically follow from the previous one","Mark where you''re less certain","The further from observation, the weaker the inference"]}', 5, 12, 3, true, 'independent'),
('Venn Diagram Challenge', 'Compare three things using a Venn diagram', 'critical_thinking', 'sketch_draw', '{"question":"Choose 3 objects or features near you. Draw a Venn diagram (3 overlapping circles) and fill in: what is unique to each, what each pair shares, and what all three share.","hints":["Label each circle with the object name","Things only in ONE circle are unique","Overlapping areas show shared properties","The center (all 3 overlap) is hardest but most interesting"]}', 4, 10, 3, true, 'independent'),
-- 5 more critical thinking to reach 25
('Perspective Shift', 'Describe a place from an unusual perspective', 'critical_thinking', 'creative_writing', '{"question":"Describe your current location from the perspective of an ant walking across the ground. What obstacles are mountains? What seems dangerous? What would be shelter? Write 3-4 sentences.","hints":["Think about scale — everything is giant to an ant","Cracks become canyons, puddles become lakes","Food crumbs are valuable resources","Temperature, moisture, and vibrations matter more than visual details"]}', 2, 7, 2, true, 'independent'),
('Ethical Dilemma', 'Consider competing values', 'critical_thinking', 'team_debate', '{"question":"Should this outdoor space prioritize nature preservation (leaving it wild), human recreation (building facilities), or education (adding signs and trails)? There is no right answer — but each team member should defend a different position with evidence from what you observe.","hints":["Preservation: natural habitats, biodiversity, ecosystem health","Recreation: benches, paths, play equipment, restrooms","Education: interpretive signs, guided trails, research areas","Can you find compromises that serve multiple values?"]}', 6, 12, 4, true, 'independent'),
('Correlation Spotter', 'Find correlations in your environment', 'critical_thinking', 'short_text', '{"question":"Find two things in your environment that seem to be correlated (they appear together or change together). Describe the correlation. Then ask: is this causation (one causes the other) or just correlation (they happen to co-occur)?","correct_answer":null,"hints":["More shade often correlates with cooler temperature (causation)","Busy areas often correlate with litter (correlation, not direct causation)","Newer buildings often correlate with wider sidewalks (city planning, not causation)","Always ask: could a third factor explain both?"]}', 6, 12, 4, true, 'independent'),
('Assumption Check', 'Identify assumptions you are making', 'critical_thinking', 'short_text', '{"question":"Make 3 observations about this location. For each observation, identify ONE assumption you''re making. Example: ''This path is well-maintained'' assumes someone is responsible for maintenance. What if your assumption is wrong?","correct_answer":null,"hints":["Assumptions are things we take for granted","We assume signs are accurate — are they?","We assume structures are permanent — will they be?","Questioning assumptions opens new understanding"]}', 6, 12, 4, true, 'independent'),
('Classification Challenge', 'Create your own classification system', 'critical_thinking', 'data_collection', '{"question":"Find at least 10 objects near you. Create your own classification system to sort them into groups. What categories did you choose? Why? Could someone else using your system sort them the same way?","hints":["There''s no single right way to classify","Categories should be clear and non-overlapping","Good systems: few categories, every item fits somewhere","Test: would a stranger sort them the same way?"]}', 3, 8, 2, true, 'independent'),

-- ── TASKS: Reading & Writing (20) ────────────────────────────

('Sensory Description', 'Write using all five senses', 'reading_writing', 'creative_writing', '{"question":"Write a paragraph describing this exact spot using ALL five senses. What do you see? Hear? Smell? Feel (touch and temperature)? Could you taste anything (describe the air — dusty? fresh? salty?). Make a reader feel like they are standing here.","hints":["Start with the most dominant sense","Use specific words, not general ones","''The rough bark scratched my palm'' vs ''the tree was rough''","Include unexpected details that surprise the reader"]}', 3, 10, 2, true, 'independent'),
('Haiku Challenge', 'Write a haiku about this moment', 'reading_writing', 'creative_writing', '{"question":"Write a haiku (5-7-5 syllables) about something you observe RIGHT NOW. Focus on one specific image or moment, not a general description. Remember: capture a single vivid moment.","hints":["Line 1: 5 syllables (set the scene)","Line 2: 7 syllables (expand the image)","Line 3: 5 syllables (surprise or insight)","Example: ''Ant carries a crumb / across the cracked gray concrete / small strength, endless path''"]}', 3, 12, 2, true, 'independent'),
('Dialogue Writing', 'Write a conversation between two objects', 'reading_writing', 'creative_writing', '{"question":"Choose two objects near you (a tree and a bench, a rock and a flower, a sign and a streetlight). Write a short dialogue (4-6 lines) between them. What would they talk about? What do they ''experience'' differently?","hints":["Think about what each object ''witnesses'' every day","Use their physical qualities as personality traits","A bench might be tired from people sitting on it","A tree might talk about the weather changing"]}', 3, 8, 2, true, 'independent'),
('Sign Analysis', 'Read and analyze a real sign or plaque', 'reading_writing', 'short_text', '{"question":"Find a sign or plaque near you. Write down exactly what it says. Then answer: Who is the intended audience? What is the purpose (inform, warn, direct, persuade, commemorate)? Is it effective at its purpose?","correct_answer":null,"hints":["Copy the text exactly as written","Consider font size, color, and placement","Who walks past this sign most often?","Could the message be misunderstood?"]}', 3, 8, 2, true, 'independent'),
('Story Starter', 'Write the opening of a story set here', 'reading_writing', 'creative_writing', '{"question":"Write the opening paragraph (3-5 sentences) of a story set EXACTLY where you are right now. Include: a character, the setting (use real details you can see), and a hint of conflict or mystery. Make the reader want to know what happens next.","hints":["Use real details from your surroundings","Create a character by describing one action","Hint at a problem without solving it","End with something that raises a question"]}', 3, 10, 2, true, 'independent'),
('Vocabulary Scavenger Hunt', 'Find real-world examples of vocabulary words', 'reading_writing', 'data_collection', '{"question":"Find real-world examples of these vocabulary concepts near you: something SYMMETRICAL, something WEATHERED, something PARALLEL, something VIBRANT, and something FRAGILE. Describe each one.","hints":["Symmetrical: same on both sides","Weathered: worn by weather over time","Parallel: two lines or edges that never meet","Vibrant: bright and eye-catching","Fragile: easily broken or damaged"]}', 3, 8, 2, true, 'independent'),
('Letter to a Visitor', 'Write a letter describing this place', 'reading_writing', 'creative_writing', '{"question":"Write a short letter (5-8 sentences) to someone who has never visited this location. Describe what makes it interesting, what they should look for, and one thing that surprised you about it. Use descriptive language.","hints":["Start with a greeting and your overall impression","Include specific sensory details","Mention something unexpected or unique","End with a recommendation or invitation"]}', 3, 8, 2, true, 'independent'),
('Instruction Writing', 'Write clear instructions for a task', 'reading_writing', 'creative_writing', '{"question":"Choose a simple action at your location (crossing a street, using a water fountain, finding a specific object). Write step-by-step instructions that someone could follow with their eyes closed (until they need to see). Be precise!","hints":["Number each step","Use command verbs (walk, turn, reach, press)","Include distances and directions","Test by reading aloud — could someone follow these?"]}', 3, 8, 2, true, 'independent'),
('Caption Writer', 'Write captions for photos', 'reading_writing', 'short_text', '{"question":"Look at your surroundings as if you were a photographer for a magazine. Write 3 different captions for the same scene: one informational (news), one emotional (poetry), and one humorous (comedy). Each should be 1-2 sentences.","correct_answer":null,"hints":["Informational: who, what, where, when","Emotional: focus on feeling and atmosphere","Humorous: find something ironic or unexpected","Same scene, three completely different moods"]}', 4, 10, 2, true, 'independent'),
('Metaphor Creation', 'Find metaphors in the real world', 'reading_writing', 'creative_writing', '{"question":"Create 3 metaphors based on what you observe. A metaphor says something IS something else: ''The road is a river of light'' or ''The old building is a tired giant.'' Find something in your environment that reminds you of something completely different.","hints":["Look for shapes, movements, and textures","What does this remind you of from a different context?","The best metaphors surprise but feel true","Avoid clichés — find fresh comparisons"]}', 5, 12, 3, true, 'independent'),
('News Report', 'Write a news report about this location', 'reading_writing', 'creative_writing', '{"question":"Write a short news report (who, what, where, when, why) about something happening at your location right now. It can be something ordinary reported as if it is breaking news. Include a headline.","hints":["Start with a dramatic headline","Answer the 5 W''s in the first paragraph","Quote an ''eyewitness'' (make it up or interview a friend)","Keep it factual but make the ordinary sound extraordinary"]}', 4, 10, 2, true, 'independent'),
('Word Collection', 'Collect interesting words from your environment', 'reading_writing', 'data_collection', '{"question":"Find and record 10 interesting words from signs, labels, plaques, or anything written in your environment. For 3 of them, look up or figure out the meaning from context. Can you use all 3 in one sentence?","hints":["Look everywhere — signs, labels, graffiti, plaques","Scientific names on plant labels count","Building names often have interesting origins","Try to figure out meaning before looking it up"]}', 3, 8, 1, true, 'independent'),
('Persuasive Speech', 'Give a persuasive speech about this place', 'reading_writing', 'audio_response', '{"question":"Record a 30-60 second persuasive speech about why someone should visit this exact location. Include: what makes it special, what you can learn here, and a call to action (''You should come here because...'').","hints":["Start with a hook — an interesting fact or question","Give 2-3 specific reasons","Use enthusiastic but genuine tone","End with a clear call to action"]}', 4, 10, 2, true, 'independent'),
('Found Poetry', 'Create a poem from found words', 'reading_writing', 'creative_writing', '{"question":"Collect words and phrases from signs, labels, and text visible at your location. Rearrange them into a poem (at least 6 lines). You can add small connecting words (the, is, and, of) but most words should be ''found.''","hints":["Walk around and write down interesting words","Look for words with rhythm or emotional resonance","Rearrange until it sounds like poetry","Found poetry reveals hidden meaning in ordinary text"]}', 5, 12, 3, true, 'independent'),
('Comparative Description', 'Compare this place to another', 'reading_writing', 'creative_writing', '{"question":"Write a paragraph comparing this location to somewhere else you know well (your bedroom, a different park, a place from a movie or book). Use at least 3 specific comparison points. How are they similar? How are they different?","hints":["Compare specific features (sound, light, size, mood)","Use comparison words (like, unlike, whereas, both)","One unexpected similarity is more interesting than three obvious ones","Why does the comparison matter?"]}', 4, 10, 2, true, 'independent'),
('Comic Strip', 'Create a comic strip about this place', 'reading_writing', 'sketch_draw', '{"question":"Draw a 4-panel comic strip about something that might happen at this location. Include at least one speech bubble and one thought bubble. The humor or story should relate to the real features of the place.","hints":["Panel 1: set the scene","Panel 2: introduce a problem or funny situation","Panel 3: make it worse or add a twist","Panel 4: resolution or punchline"]}', 2, 8, 2, true, 'independent'),
('Onomatopoeia Collection', 'Find and write sound words', 'reading_writing', 'data_collection', '{"question":"Onomatopoeia are words that sound like what they describe (buzz, splash, crunch). Listen carefully and write 8 onomatopoeia words for sounds at your location. Include at least 3 you invented yourself for sounds that don''t have standard words.","hints":["Standard examples: rustle, chirp, hum, drip, swoosh","What sound does wind in leaves make? Invent a word!","What about footsteps on gravel? On concrete?","The best invented words SOUND like the sound"]}', 3, 8, 2, true, 'independent'),
('Review Writing', 'Write a review of this location', 'reading_writing', 'creative_writing', '{"question":"Write a 5-star review of this location as if for a travel website. Include: overall rating (1-5 stars), what you liked best, what could be improved, and who you would recommend it to. Be honest but constructive.","hints":["Start with your star rating and one-line summary","Mention specific features (not just ''it was nice'')","Suggestions for improvement show critical thinking","Who would enjoy this most? Who might not?"]}', 4, 10, 2, true, 'independent'),
('Acrostic Poem', 'Write an acrostic poem using a location word', 'reading_writing', 'creative_writing', '{"question":"Choose a word related to your location (the name of a feature, a feeling, or a nature word). Write an acrostic poem where each line starts with the next letter of your chosen word. Each line should be an observation from your current spot.","hints":["Pick a word with 4-7 letters","Each line should relate to what you see, hear, or feel","Example with TREE: T-Towering over the path / R-Roots grip the dark earth...","Short words are easier to start with"]}', 3, 8, 2, true, 'independent'),
('Summary Writing', 'Summarize a place in exactly 50 words', 'reading_writing', 'creative_writing', '{"question":"Describe your current location in EXACTLY 50 words — no more, no less. Count carefully! This forces you to choose every word deliberately. What is most essential to include?","hints":["Write freely first, then count and edit","Cut unnecessary words (very, really, just)","Replace vague words with specific ones","Every word must earn its place"]}', 4, 12, 3, true, 'independent'),

-- ── TASKS: History & Community (10) ──────────────────────────

('Building Age Detective', 'Estimate when a building was constructed', 'history_community', 'numeric_entry', '{"question":"Look at the nearest building. Estimate the year it was built based on architectural clues: materials, style, condition, and any dates you can find. What clues did you use?","unit":"year","hints":["Stone and brick suggest older construction","Glass and steel suggest modern construction","Look for date stones, cornerstone inscriptions","Window shapes changed over decades"]}', 3, 10, 2, true, 'independent'),
('Community Asset Map', 'Map community resources in the area', 'history_community', 'data_collection', '{"question":"From where you stand, identify all the community assets (resources) you can see or know are nearby: parks, libraries, schools, stores, transit stops, churches, clinics, etc. List at least 5 with their approximate distance and direction.","hints":["Community assets serve public needs","Include natural assets (rivers, gardens, open spaces)","Consider accessibility — who can reach these?","Some assets are visible; others you know are nearby"]}', 4, 10, 2, true, 'independent'),
('Infrastructure Scavenger Hunt', 'Find hidden infrastructure', 'history_community', 'data_collection', '{"question":"Find and document at least 5 pieces of community infrastructure that most people walk past without noticing: manhole covers, fire hydrants, utility poles, storm drains, survey markers, bollards, etc. For each, describe its purpose.","hints":["Look down — manhole covers, grates, survey markers","Look up — utility poles, wires, cameras, lights","Look at edges — bollards, curb cuts, drainage","Color-coded markings often indicate underground utilities"]}', 3, 8, 2, true, 'independent'),
('Then and Now', 'Imagine this place at different time periods', 'history_community', 'creative_writing', '{"question":"Pick the oldest-looking feature near you. Write a brief timeline: What was this place like when that feature was new? What has changed around it? What has stayed the same? Include at least 3 time periods.","hints":["Start with the feature when it was brand new","Middle period: what changed around it?","Now: how does the old feature fit with the modern surroundings?","Consider what people who used it originally would think of it now"]}', 4, 10, 3, true, 'independent'),
('Public Space Analysis', 'Evaluate how a public space serves its community', 'history_community', 'team_debate', '{"question":"Is this public space designed well for the community it serves? Evaluate: accessibility (ADA compliance), inclusivity (who is welcome?), safety (lighting, visibility), maintenance, and usefulness. Rate each 1-5 and discuss as a team.","hints":["Check for ramps, wide paths, accessible seating","Is there shade? Water? Restrooms?","Would all ages feel welcome here?","What time of day does this space work best?"]}', 5, 12, 3, true, 'independent'),
('Architectural Styles', 'Identify architectural features', 'history_community', 'multiple_choice', '{"question":"Look at the buildings near you. Which architectural characteristic is most prominent?","options":["Symmetry (balanced, same on both sides)","Ornate details (carved stone, decorative trim)","Minimalist (simple shapes, few decorations)","Mixed materials (brick + glass, stone + steel)","Functional (designed for use, not beauty)"],"correct_answer":"","hints":["Older buildings tend to have more ornamental detail","Modern buildings often emphasize function","Materials reflect the era and region","Look at windows, rooflines, and entrances for style clues"]}', 3, 10, 2, true, 'independent'),
('Transportation Survey', 'Study how people get around', 'history_community', 'data_collection', '{"question":"In 5 minutes, count how many people pass by and how they are traveling: walking, cycling, driving, public transit, scooter/skateboard, wheelchair, other. What percentage uses each mode? What does this tell you about the community?","hints":["Record each person and their mode","Calculate percentages after counting","More walkers suggests walkable neighborhood","Infrastructure shapes transportation choices"]}', 4, 10, 2, true, 'independent'),
('Memorial Analysis', 'Study a memorial, statue, or plaque', 'history_community', 'short_text', '{"question":"Find a memorial, statue, monument, or commemorative plaque near you (even a small one). Who or what does it honor? When was it placed? Who placed it? What values does it represent? What story does it tell — and what does it leave out?","correct_answer":null,"hints":["Read all text carefully — front and back","Note the materials and craftsmanship","Consider who chose to create this and why","Ask: whose perspective is represented? Whose isn''t?"]}', 5, 12, 3, true, 'independent'),
('Accessibility Audit', 'Evaluate physical accessibility', 'history_community', 'data_collection', '{"question":"Evaluate the accessibility of your current location for someone using a wheelchair. Check: ground surface (smooth?), slope (too steep?), width (wide enough?), obstacles, ramps/curb cuts, seating options. Rate overall accessibility 1-10 with notes.","hints":["Wheelchairs need minimum 36 inches (90 cm) width","Ramps should be 1:12 slope or gentler","Gravel, grass, and uneven surfaces are barriers","Door handles, heights of controls, and seating matter too"]}', 4, 12, 2, true, 'independent'),
('Community Interview', 'Prepare questions for a community member', 'history_community', 'creative_writing', '{"question":"If you could interview someone who has lived near this location for 30+ years, what 5 questions would you ask them? Write questions that would reveal how this place has changed and what has stayed the same.","hints":["Open-ended questions get better stories","Ask about specific features (''When was this park built?'')","Ask about feelings (''What do you love most about this area?'')","Ask about change (''What''s the biggest change you''ve seen?'')"]}', 4, 10, 2, true, 'independent');

-- Verify counts
-- SELECT subject_domain, count(*) FROM tasks WHERE is_library = true AND location_dependency = 'independent' GROUP BY subject_domain;
-- Expected: science_nature=25, math_real_world=25, geography_maps=15, critical_thinking=25, reading_writing=20, history_community=10
-- Total: 120 tasks, 40 primers
