-- ══════════════════════════════════════════════════════════════
-- Migration 014: Tier 2 Curriculum Library (Location-Type Dependent)
-- 80 tasks + 30 primers that require a TYPE of location
-- (park, water, mountain, etc.) but work at any instance.
-- ══════════════════════════════════════════════════════════════

-- ── PRIMERS (30) ─────────────────────────────────────────────

-- Park primers (4)
INSERT INTO public.primers (title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type) VALUES
('Park Ecosystems', '{"text":"Parks are designed ecosystems where humans manage nature. They include planted areas (maintained by people), wild areas (nature manages itself), and transitional zones. Even a small city park has microhabitats: sunny open grass, shady tree canopy, flower beds, pond edges, and the soil underneath.","items":["Maintained areas: mowed grass, planted flowers, trimmed hedges","Wild areas: unmowed edges, fallen logs, leaf litter","Edge habitats: where two zones meet (most biodiversity)","Underground: roots, worms, fungi, insects"]}', 'science_nature', 2, 8, true, 'type_dependent', 'park'),
('Park Design and Planning', '{"text":"Parks don''t just happen — they are carefully designed. Landscape architects plan parks considering: who will use it (children, adults, dogs, athletes), what activities to support (play, rest, sports, nature), how to manage water drainage, and how to create beauty across all seasons. Every bench, path, and tree was a deliberate choice.","items":["Zone planning: active areas separated from quiet areas","Sight lines: designers control what you see as you walk","Drainage: parks often manage stormwater","Seasonal interest: plants chosen to bloom in different months"]}', 'geography_maps', 3, 10, true, 'type_dependent', 'park'),
('Playground Physics', '{"text":"Playgrounds are physics laboratories! Swings demonstrate pendulum motion. Slides show gravity and friction. See-saws illustrate levers and balance. Merry-go-rounds show centripetal force. Climbing structures demonstrate potential and kinetic energy. Every piece of equipment uses forces, motion, and energy in ways you can observe and measure.","items":["Swings: pendulum motion (gravity pulls you back to center)","Slides: gravity accelerates you; friction slows you","See-saw: lever principle (balance point, torque)","Spinning: centripetal force keeps you on; you feel pushed outward"]}', 'science_nature', 3, 8, true, 'type_dependent', 'park'),
('Urban Wildlife in Parks', '{"text":"City parks are critical habitat for urban wildlife. Birds, squirrels, insects, and even foxes, coyotes, and deer use parks as corridors between green spaces. Parks provide food (seeds, insects, berries), water (ponds, sprinklers), shelter (trees, bushes, structures), and nesting sites. The wildlife you see depends on the park''s size, vegetation, and connectivity to other green spaces.","items":["Larger parks support more species","Connected green corridors help animals move through cities","Native plants support more wildlife than exotic species","Dawn and dusk are the best times to spot urban wildlife"]}', 'science_nature', 3, 10, true, 'type_dependent', 'park'),

-- Water feature primers (4)
('Water Properties', '{"text":"Water is remarkable. It''s the only common substance that exists as solid (ice), liquid (water), and gas (steam/vapor) at Earth''s normal temperatures. It dissolves more substances than any other liquid (the ''universal solvent''). It expands when it freezes (which is why ice floats and pipes burst). And it has high surface tension, which lets insects walk on it.","items":["Three states: solid (ice), liquid (water), gas (vapor)","Universal solvent: dissolves many substances","Expands when freezing: ice is less dense than water","Surface tension: water molecules stick together at the surface"]}', 'science_nature', 2, 8, true, 'type_dependent', 'water'),
('River and Stream Dynamics', '{"text":"Moving water shapes the land. On the outside of a curve, water flows fast and erodes the bank. On the inside, water flows slow and deposits sediment. Over time, rivers create meanders, floodplains, and deltas. The speed, volume, and sediment load of water determine how much erosion and deposition occurs.","items":["Erosion: water removes soil and rock","Deposition: water drops sediment as it slows","Outside of bend: fast water, erosion","Inside of bend: slow water, deposition (sand bars)"]}', 'science_nature', 4, 10, true, 'type_dependent', 'water'),
('Water Quality Indicators', '{"text":"You can assess water quality without a lab. Clarity (can you see the bottom?), color (green = algae bloom), smell (rotten eggs = low oxygen), foam (could be pollution), and the organisms present all indicate quality. Certain insects (mayfly larvae, stonefly larvae) only live in clean water — they are ''indicator species.''","items":["Clear water: generally healthier","Green/brown water: excess nutrients (eutrophication)","Diverse aquatic insects: sign of good quality","Foam, oil sheen, or strong odor: potential pollution"]}', 'science_nature', 5, 12, true, 'type_dependent', 'water'),
('Watersheds and Drainage', '{"text":"A watershed is an area of land where all water drains to the same point (a river, lake, or ocean). You are always in a watershed. Rain that falls on your location flows downhill, joining streams that join rivers. Understanding watersheds helps explain flooding, water quality, and why what happens upstream affects everything downstream.","items":["Every point on land is in a watershed","Water flows downhill following the land''s shape","Ridges and hills form watershed boundaries","Urban surfaces (concrete, roofs) speed up water flow"]}', 'geography_maps', 5, 12, true, 'type_dependent', 'water'),

-- Mountain/trail primers (4)
('Geology and Rock Formation', '{"text":"Mountains tell the story of Earth''s history. Some formed from volcanic activity (igneous rock). Others from ancient sea floors compressed and pushed up (sedimentary rock). Still others from existing rock transformed by heat and pressure (metamorphic rock). Every rock you see has a story that might be millions of years old.","items":["Igneous: from cooled magma/lava (granite, basalt)","Sedimentary: from compressed layers (limestone, sandstone)","Metamorphic: from heat/pressure changing existing rock (marble, slate)","Mountain building: plate tectonics push rock upward"]}', 'science_nature', 4, 12, true, 'type_dependent', 'mountain'),
('Trail Ecology', '{"text":"Trails create their own ecology. The compacted soil of the trail itself has little life. But the edges (ecotones) are rich with plants adapted to partial shade and occasional disturbance. Trail width, erosion, and vegetation change show how many people use the trail and how it''s maintained. Switchbacks reduce erosion on steep slopes.","items":["Trail surface: compacted, few organisms","Trail edges: diverse plants, insect habitat","Switchbacks: zigzag pattern reduces erosion on slopes","Trail braiding: multiple parallel paths indicate poor drainage"]}', 'science_nature', 4, 10, true, 'type_dependent', 'trail'),
('Elevation and Climate', '{"text":"Temperature drops about 6.5°C for every 1000 meters of elevation gain. This means a mountain can have completely different ecosystems at different heights: forest at the base, alpine meadow in the middle, and bare rock with snow at the top. These elevation zones are similar to latitude zones — going up a mountain is like traveling toward the poles.","items":["Temperature decreases ~6.5°C per 1000m elevation","Vegetation zones change with altitude","Treeline: the elevation above which trees cannot grow","Wind speed increases with elevation"]}', 'science_nature', 5, 12, true, 'type_dependent', 'mountain'),
('Leave No Trace', '{"text":"The Leave No Trace principles help protect natural areas for future visitors. Plan ahead, travel on durable surfaces, dispose of waste properly, leave what you find, minimize campfire impacts, respect wildlife, and be considerate of other visitors. These principles ensure that the next person experiences the same beauty you did.","items":["Plan ahead and prepare","Travel on durable surfaces (stay on trails)","Pack it in, pack it out (carry out all trash)","Leave what you find (don''t pick flowers or move rocks)","Respect wildlife (observe from a distance)"]}', 'science_nature', 2, 12, true, 'type_dependent', 'trail'),

-- Urban/street primers (3)
('Urban Planning Basics', '{"text":"Cities are designed systems. Streets form a grid or radial pattern. Buildings are zoned for residential, commercial, or industrial use. Public spaces (parks, plazas, sidewalks) connect everything. Urban planners balance many competing needs: traffic flow, housing, business, recreation, and environmental quality.","items":["Grid patterns: easy navigation, equal-sized blocks","Radial patterns: centered on a point, like spokes of a wheel","Zoning: separating (or mixing) different land uses","Density: how many people and buildings per area"]}', 'geography_maps', 5, 12, true, 'type_dependent', 'urban'),
('Reading the Built Environment', '{"text":"Every building, sign, and street tells a story. Construction materials reveal the era. Business types reflect the economy. Signage languages show the community''s diversity. The condition of infrastructure shows investment priorities. You can ''read'' a neighborhood like a book — every detail is a sentence.","items":["Materials: wood (old), brick (older), concrete (mid-century), glass/steel (modern)","Businesses: reflect community needs and income levels","Signs: language, style, and condition tell stories","Maintenance: shows where resources are invested"]}', 'history_community', 5, 12, true, 'type_dependent', 'urban'),
('Traffic Engineering', '{"text":"Traffic flow is engineered with math and psychology. Traffic lights are timed to optimize flow. Speed limits consider road width, visibility, and pedestrian activity. Crosswalks, medians, and roundabouts are designed to manage conflicts between cars, bikes, and pedestrians. Even the paint colors on roads follow international standards.","items":["Signal timing: calculated using traffic volume data","Speed limits: based on road design and safety research","Roundabouts: reduce severe accidents by slowing all traffic","Road markings: white separates same-direction; yellow separates opposite"]}', 'math_real_world', 6, 12, true, 'type_dependent', 'urban'),

-- Farm/garden primers (3)
('Soil Science Basics', '{"text":"Healthy soil is alive. One teaspoon of soil contains more microorganisms than there are people on Earth. Soil forms in layers (horizons): topsoil (dark, nutrient-rich), subsoil (lighter, fewer nutrients), and bedrock. Good agricultural soil has a balance of sand (drainage), silt (nutrients), and clay (water retention) — called loam.","items":["Topsoil: dark, nutrient-rich, most organisms","Subsoil: lighter colored, fewer nutrients","Sand: large particles, drains quickly","Clay: tiny particles, holds water and nutrients","Loam: the ideal mix for growing plants"]}', 'science_nature', 3, 10, true, 'type_dependent', 'farm'),
('Plant Growth and Seasons', '{"text":"Plants respond to day length (photoperiod), temperature, and water availability. In temperate climates, plants grow actively in spring and summer, slow in autumn, and go dormant in winter. Some plants (annuals) complete their life cycle in one season. Others (perennials) return year after year. Understanding these cycles helps farmers and gardeners plan.","items":["Germination: seed sprouts into a seedling","Vegetative growth: stems and leaves expand","Flowering: plant produces flowers for reproduction","Fruiting: flowers develop into fruits with seeds","Dormancy: plant rests through unfavorable conditions"]}', 'science_nature', 2, 8, true, 'type_dependent', 'farm'),
('Pollination and Food Production', '{"text":"About 75% of flowering plants and 35% of food crops depend on animal pollinators. Bees are the most important pollinators, but butterflies, moths, birds, bats, and even wind play roles. Without pollination, we would lose most fruits, vegetables, and nuts. A garden or farm is a great place to observe pollination in action.","items":["Bees: most effective pollinators, visit many flower types","Butterflies: prefer flat, open flowers with landing pads","Wind: pollinates grasses, corn, wheat, and many trees","Self-pollination: some plants pollinate themselves"]}', 'science_nature', 3, 8, true, 'type_dependent', 'farm'),

-- Forest primers (3)
('Forest Layers', '{"text":"A forest has distinct vertical layers, each with its own community of life. The canopy (treetops) gets the most sunlight. The understory (smaller trees and tall shrubs) gets filtered light. The shrub layer lives in shade. The herb layer (ground plants, ferns) gets very little direct sun. The forest floor (decomposing material) is its own dark, moist world.","items":["Canopy: tallest trees, most sunlight, birds and squirrels","Understory: shorter trees, filtered light, shade-tolerant species","Shrub layer: bushes, young trees, many birds and insects","Herb layer: ferns, wildflowers, mosses","Forest floor: decomposing leaves, fungi, insects, worms"]}', 'science_nature', 3, 10, true, 'type_dependent', 'forest'),
('Tree Identification', '{"text":"You can identify trees using: leaf shape (needles vs. broad, simple vs. compound), bark texture and color, overall shape (conical, rounded, spreading), fruit or seeds, and habitat. A field guide helps, but you can learn the 10 most common trees in your area quickly. Knowing tree species helps you understand the ecosystem.","items":["Broadleaf: flat, wide leaves (oak, maple, birch)","Needleleaf: thin needles or scales (pine, spruce, cedar)","Simple leaf: one blade per stem","Compound leaf: multiple leaflets per stem","Bark: smooth (birch), deeply furrowed (oak), peeling (sycamore)"]}', 'science_nature', 2, 8, true, 'type_dependent', 'forest'),
('Decomposition and Nutrient Cycling', '{"text":"In a forest, nothing is wasted. Dead leaves, branches, and organisms are broken down by fungi, bacteria, insects, and worms into nutrients that return to the soil. This process (decomposition) can take weeks for a leaf or decades for a fallen tree. A rotting log is one of the most biodiverse habitats in a forest.","items":["Fungi: primary decomposers, break down tough materials like wood","Bacteria: decompose soft material quickly","Insects: beetles, ants, termites physically break material apart","Worms: mix decomposed material into soil","A rotting log supports hundreds of species"]}', 'science_nature', 3, 10, true, 'type_dependent', 'forest'),

-- Historic site primers (2)
('Reading Historic Buildings', '{"text":"Historic buildings are primary sources — they tell you about the technology, values, aesthetics, and economy of the time they were built. Look for: construction materials (what was available?), architectural style (what was fashionable?), size and grandeur (who was wealthy?), modifications (how has use changed?), and preservation efforts (what does the community value?).","items":["Materials: local stone, imported marble, mass-produced brick","Style: Colonial, Victorian, Art Deco, Mid-Century Modern","Modifications: additions, removed features, changed windows","Plaques and markers: community''s chosen narrative"]}', 'history_community', 4, 12, true, 'type_dependent', 'historic'),
('Primary vs. Secondary Sources', '{"text":"At historic sites, you encounter primary sources (original objects, buildings, inscriptions from the time period) and secondary sources (modern signs, guided descriptions, interpretive displays). Primary sources give direct evidence; secondary sources provide interpretation. Good historians use both but distinguish between them.","items":["Primary: original building, inscription, artifact","Secondary: modern interpretive sign, audio guide","Primary sources can be misinterpreted","Secondary sources reflect the interpreter''s perspective"]}', 'history_community', 5, 12, true, 'type_dependent', 'historic'),

-- Field/open space primers (3)
('Weather Observation Station', '{"text":"Open fields are natural weather observation stations. With a clear view of the sky, you can observe cloud patterns, wind behavior, temperature differences (sun vs. shade), and precipitation. Meteorologists use open spaces for weather stations because buildings and trees distort readings. You can be your own weather station with just your senses.","items":["Cloud cover: estimate in eighths (oktas)","Wind direction: face the wind — it''s coming FROM that direction","Temperature: sun vs. shade can differ by 10-20°F","Visibility: how far can you see? Haze reduces visibility"]}', 'science_nature', 3, 10, true, 'type_dependent', 'field'),
('Open Space Ecology', '{"text":"Open fields and meadows have their own unique ecology. Without tree canopy, ground plants get full sun and must tolerate wind and temperature extremes. Grasses dominate because they grow from the base (so grazing doesn''t kill them) and their roots hold soil. Open spaces are critical for ground-nesting birds, butterflies, and wildflowers.","items":["Grasses: grow from base, tolerate mowing and grazing","Wildflowers: adapted to full sun, attract pollinators","Ground nesters: some birds need open ground for nests","Succession: without maintenance, fields become forest over time"]}', 'science_nature', 3, 10, true, 'type_dependent', 'field'),
('Sound Propagation', '{"text":"Sound travels differently in open spaces vs. enclosed areas. In a field, sound waves spread freely in all directions and fade with distance. There are no walls to create echoes. Wind carries sound farther downwind and reduces it upwind. Temperature inversions (warm air over cold) can trap sound near the ground, making distant sounds surprisingly audible.","items":["Sound intensity decreases with distance (inverse square law)","Wind carries sound downwind","Temperature affects sound speed (faster in warm air)","No reflective surfaces = no echo in open fields"]}', 'science_nature', 5, 12, true, 'type_dependent', 'field');

-- ── TASKS: Park (12) ─────────────────────────────────────────

INSERT INTO public.tasks (title, description, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type) VALUES
('Park Ecosystem Map', 'Map the different zones of this park', 'science_nature', 'sketch_draw', '{"question":"Sketch a simple map of this park showing its different ecosystem zones: maintained lawn, flower beds, tree canopy, water features, wild/unmaintained areas, and paved surfaces. Label each zone.","hints":["Use different colors or patterns for each zone","Show the relative size of each zone","Mark where zones transition","Note which zone has the most biodiversity"]}', 3, 8, 2, true, 'type_dependent', 'park'),
('Bench Biomechanics', 'Analyze the physics of park furniture', 'science_nature', 'data_collection', '{"question":"Find a bench. Measure or estimate: seat height (cm), seat depth, back angle, material type, and sun exposure. Is this bench designed for comfort? Rate it 1-10. What would you change?","hints":["Ideal seat height is about 45 cm for adults","Angle of back affects comfort for long sitting","Material affects temperature (metal gets hot/cold)","Sun exposure matters for usability"]}', 4, 10, 2, true, 'type_dependent', 'park'),
('Park Visitor Count', 'Collect data on park usage', 'math_real_world', 'data_collection', '{"question":"For exactly 5 minutes, count all park visitors you can see. Categorize: alone/couple/group, walking/sitting/exercising/playing. Calculate percentages. What is this park''s primary use right now?","hints":["Tally each person in categories","Calculate: category count ÷ total × 100 = %","Time of day affects usage patterns","Compare weekday vs weekend if you can return"]}', 3, 8, 2, true, 'type_dependent', 'park'),
('Shade Coverage Analysis', 'Calculate the percentage of shaded area', 'math_real_world', 'numeric_entry', '{"question":"Estimate what percentage of this park''s total area is currently in shade. Consider tree canopy, building shadows, and structures. How will this change in 3 hours?","unit":"percent","hints":["Morning: long shadows from the east","Noon: minimal shade (directly overhead sun)","Afternoon: long shadows from the west","Large trees provide the most shade"]}', 4, 8, 2, true, 'type_dependent', 'park'),
('Path Network Analysis', 'Map and analyze the park''s path system', 'geography_maps', 'sketch_draw', '{"question":"Draw the network of paths in this park. Mark: main paths (wide, paved), secondary paths (narrow), and desire lines (worn shortcuts through grass). Are the designed paths efficient, or do people create their own?","hints":["Desire lines show where designers got it wrong","Intersections are decision points for walkers","Dead-end paths are frustrating for users","Loops are more enjoyable than out-and-back paths"]}', 4, 10, 2, true, 'type_dependent', 'park'),
('Playground Force Investigation', 'Investigate forces on playground equipment', 'science_nature', 'data_collection', '{"question":"Choose a piece of playground equipment. Identify all the forces acting on someone using it: gravity, friction, tension, normal force, centripetal force, air resistance. Describe how each force affects the motion.","hints":["Swing: gravity + tension in chains","Slide: gravity + friction + normal force","Merry-go-round: centripetal force + friction","Climbing: gravity + friction + muscle force"]}', 4, 10, 3, true, 'type_dependent', 'park'),
('Tree Census', 'Count and classify trees in a park section', 'science_nature', 'data_collection', '{"question":"Choose a section of the park. Count every tree and classify each as: deciduous (loses leaves) or evergreen, young (trunk < 15cm diameter) or mature. What is the deciduous-to-evergreen ratio?","hints":["Deciduous: broad leaves that drop in fall","Evergreen: keeps leaves/needles year-round","Young trees have thin trunks and few branches","Mature trees have thick trunks and full canopies"]}', 3, 8, 2, true, 'type_dependent', 'park'),
('Park Accessibility Rating', 'Evaluate the park for all users', 'history_community', 'data_collection', '{"question":"Rate this park''s accessibility for: wheelchair users, elderly visitors, young children, visually impaired visitors, and people with sensory sensitivities. Rate each group 1-5. What improvements would you recommend?","hints":["Check path surfaces, widths, and slopes","Are there accessible restrooms, water fountains?","Is playground equipment accessible?","Are there quiet areas for sensory-sensitive visitors?"]}', 4, 12, 2, true, 'type_dependent', 'park'),
('Nature Sounds vs. Human Sounds', 'Compare natural and human-generated sounds', 'science_nature', 'data_collection', '{"question":"Sit quietly for 2 minutes. Record every sound and classify as NATURE (birds, wind, water, insects) or HUMAN (traffic, voices, machines, music). What is the nature-to-human sound ratio? Is this park a good nature escape?","hints":["Close your eyes to focus on hearing","Some sounds are ambiguous (dog barking = human/animal?)","Wind in leaves is a nature sound; wind in flags is human-influenced","The ratio reveals how ''natural'' this park really is"]}', 2, 8, 2, true, 'type_dependent', 'park'),
('Park Geometry Challenge', 'Find geometric shapes in park features', 'math_real_world', 'data_collection', '{"question":"Find examples of at least 8 different geometric shapes in this park. For each, name the shape, where you found it, and estimate one measurement (side length, radius, or angle).","hints":["Circles: tree trunk cross-sections, fountains, clocks","Rectangles: benches, signs, pavers","Triangles: roof peaks, support braces","Hexagons: paver patterns, gazebo shapes"]}', 2, 7, 1, true, 'type_dependent', 'park'),
('Seasonal Changes Observation', 'Document seasonal indicators', 'science_nature', 'photo_observation', '{"question":"What season clues can you find in this park? Take a photo showing the strongest seasonal indicator and describe 3 additional signs of the current season you can observe.","hints":["Spring: new buds, flowers, baby animals, wet ground","Summer: full canopy, dry grass, active insects, long days","Autumn: color change, falling leaves, shorter days, cooler air","Winter: bare branches, dormant grass, frost, low sun angle"]}', 2, 8, 1, true, 'type_dependent', 'park'),
('Park Design Critique', 'Evaluate park design choices', 'critical_thinking', 'team_debate', '{"question":"If you could redesign this park with the same budget, what would you change? Each team member argues for a different priority: more nature/habitat, more play equipment, more seating/accessibility, or more sports facilities. Which improvements matter most?","hints":["Consider who currently uses the park most","What''s missing that would serve more people?","Nature and recreation can conflict — how to balance?","Good design serves multiple purposes simultaneously"]}', 5, 12, 3, true, 'type_dependent', 'park'),

-- ── TASKS: Water (10) ────────────────────────────────────────

('Water Flow Speed', 'Measure water flow using a natural float', 'science_nature', 'numeric_entry', '{"question":"Drop a leaf or small stick into the water. Time how long it takes to travel a measured distance (5 meters or 10 steps along the bank). Calculate the flow speed in meters per second.","unit":"m/s","hints":["Mark your start and end points clearly","Use a lightweight object that floats well","Time from when it passes the start mark","Speed = distance ÷ time"]}', 3, 8, 2, true, 'type_dependent', 'water'),
('Erosion and Deposition', 'Identify where water erodes and deposits', 'science_nature', 'photo_observation', '{"question":"Find a spot where water is eroding the bank or shore AND a spot where sediment is being deposited. Take a photo of each. Explain what causes erosion at one spot and deposition at the other.","hints":["Erosion: undercut banks, exposed roots, steep edges","Deposition: sand bars, gentle slopes, accumulated sediment","Outside of curves: erosion; inside of curves: deposition","Fast water erodes; slow water deposits"]}', 4, 10, 2, true, 'type_dependent', 'water'),
('Water Clarity Test', 'Measure water clarity', 'science_nature', 'numeric_entry', '{"question":"How clear is the water? Wade to the edge (safely) and see how deep you can see the bottom clearly. Or drop a white object to measure visibility depth. Record in centimeters.","unit":"cm visibility","hints":["Clear water: you can see bottom at 1+ meters","Turbid water: visibility less than 30 cm","Algae bloom: green color reduces visibility","After rain: sediment reduces clarity temporarily"]}', 3, 8, 2, true, 'type_dependent', 'water'),
('Aquatic Life Survey', 'Identify organisms in or near water', 'science_nature', 'data_collection', '{"question":"Survey the water and its immediate edges for 5 minutes. Record every living thing you find: fish, insects, amphibians, birds, plants, algae. Classify each as aquatic (lives in water), semi-aquatic (lives in both), or terrestrial visitor (just visiting).","hints":["Look at the surface film for water striders, beetles","Check under rocks at the water''s edge for larvae","Watch for birds fishing or wading","Algae and aquatic plants are organisms too"]}', 3, 10, 2, true, 'type_dependent', 'water'),
('Water Temperature and Location', 'Compare water temperature at different spots', 'science_nature', 'data_collection', '{"question":"If you can safely touch the water, compare the temperature (by feel) at 3 different spots: in the sun vs. shade, shallow vs. deep edge, moving vs. still water. Which is warmest? Coldest? Why?","hints":["Shallow water warms faster in sun","Deep water stays cooler","Moving water mixes temperatures","Shaded areas stay cooler throughout the day"]}', 3, 8, 2, true, 'type_dependent', 'water'),
('Watershed Direction', 'Determine which direction water drains', 'geography_maps', 'short_text', '{"question":"Look at the land around this water feature. Which direction does water drain INTO this water body? Trace the path a raindrop would take from the highest point you can see to this water. Where does the water go AFTER this point?","correct_answer":null,"hints":["Water always flows downhill","Look for gutters, storm drains, and ditches that feed in","Larger water bodies collect from many small streams","Eventually all freshwater reaches the ocean"]}', 4, 10, 2, true, 'type_dependent', 'water'),
('Water Sound Map', 'Map the sounds of water', 'reading_writing', 'creative_writing', '{"question":"Water makes many different sounds. Walk along the water feature and listen. Write 5 onomatopoeia words (sound words) for the different water sounds you hear. Then write a short paragraph using all 5 words to describe the soundscape.","hints":["Rushing: fast-moving water over rocks","Dripping: individual drops falling","Lapping: gentle waves hitting a shore","Gurgling: water moving through narrow spaces","Splashing: sudden disturbance of the surface"]}', 3, 8, 2, true, 'type_dependent', 'water'),
('Riparian Zone Analysis', 'Study the zone where land meets water', 'science_nature', 'data_collection', '{"question":"The riparian zone is where land meets water. Walk 10 meters perpendicular from the water''s edge. Record how the vegetation changes from water to dry land: what plants grow at the water''s edge? At 5 meters? At 10 meters? Why does it change?","hints":["Water-loving plants grow at the edge","Transitional plants grow a few meters from water","Upland plants grow farther from water","Root depth and water tolerance determine what grows where"]}', 5, 12, 3, true, 'type_dependent', 'water'),
('Bridge Engineering', 'Analyze bridge or crossing design', 'math_real_world', 'short_text', '{"question":"If there is a bridge, dock, or crossing structure at this water feature, analyze its engineering. What type of structure is it (beam, arch, suspension, pontoon)? Why was this type chosen? Estimate its span length and width.","correct_answer":null,"hints":["Beam bridges: simplest, for short spans","Arch bridges: curved, supports weight through compression","Suspension: cables support the deck from above","The span length, load, and materials determine the design"]}', 5, 12, 3, true, 'type_dependent', 'water'),
('Water Reflection Challenge', 'Observe and sketch water reflections', 'reading_writing', 'sketch_draw', '{"question":"Find a calm section of water with visible reflections. Sketch what you see reflected in the water. How does the reflection differ from the real scene? (colors, clarity, movement, distortion)","hints":["Reflections are vertically flipped","Colors appear darker in reflections","Ripples distort reflections","The angle of viewing changes what you can see reflected"]}', 3, 8, 2, true, 'type_dependent', 'water'),

-- ── TASKS: Mountain/Trail (10) ───────────────────────────────

('Rock Type Identification', 'Identify rock types along the trail', 'science_nature', 'data_collection', '{"question":"Collect observations of 5 different rocks along the trail (don''t remove them — just observe). For each: color, texture, hardness (can you scratch it?), crystal size, and your best guess at rock type (igneous, sedimentary, metamorphic).","hints":["Igneous: often dark, sometimes glassy or with crystals","Sedimentary: often layered, may contain fossils","Metamorphic: often has bands or folded layers, may be shiny","Scratch test: harder rocks scratch softer ones"]}', 4, 10, 2, true, 'type_dependent', 'mountain'),
('Elevation Profile Sketch', 'Draw the elevation profile of your hike', 'geography_maps', 'sketch_draw', '{"question":"As you walk, sketch an elevation profile (a side-view showing ups and downs). Mark your x-axis as distance walked and y-axis as elevation change. Include key landmarks at their positions on the profile.","hints":["Start at zero on both axes","Mark uphills as rising lines, downhills as falling","Flat sections are horizontal lines","Steeper slopes = steeper lines on the profile"]}', 5, 12, 3, true, 'type_dependent', 'trail'),
('Trail Erosion Assessment', 'Assess erosion along the trail', 'science_nature', 'data_collection', '{"question":"Walk 100 meters of trail. Rate erosion severity at 5 points: none (0), minor (1), moderate (2), or severe (3). What type of erosion? (water channeling, widening, gullying, root exposure). Calculate the average erosion score.","hints":["Water channeling: trail becomes a stream bed in rain","Widening: people walk beside the trail to avoid mud","Gullying: deep channels cut into the trail","Root exposure: soil washed away revealing tree roots"]}', 4, 10, 2, true, 'type_dependent', 'trail'),
('Vegetation Zone Change', 'Observe how plants change with elevation', 'science_nature', 'data_collection', '{"question":"If you''re on a trail with elevation change, observe plant communities at 3 different points: low, middle, and high. What species dominate at each? How do plant sizes and types change with elevation?","hints":["Lower elevations: larger trees, more species","Higher elevations: smaller, hardier plants","Treeline: the elevation where trees stop growing","Wind exposure increases with elevation"]}', 5, 12, 3, true, 'type_dependent', 'mountain'),
('Trail Distance Estimation', 'Estimate trail distances', 'math_real_world', 'numeric_entry', '{"question":"Estimate how far you have walked on this trail in meters. Count your steps for 50 meters (use markers or estimate), then count total steps from the start. Calculate total distance.","unit":"meters","hints":["Count steps for a known distance to calibrate","Uphill steps are shorter than flat steps","Average hiking step: 0.6-0.8 meters","Multiply: total steps × step length"]}', 3, 8, 2, true, 'type_dependent', 'trail'),
('Wildlife Sign Search', 'Find evidence of mountain wildlife', 'science_nature', 'data_collection', '{"question":"Search a 50-meter section of trail for wildlife signs. Record everything: tracks, droppings, nests, feathers, chewed bark, burrows, webs, sounds. For each sign, identify what animal likely left it.","hints":["Look on the trail surface for tracks (best after rain)","Check tree trunks for claw marks or pecked holes","Listen for bird calls and identify species if possible","Dawn and dusk show more wildlife activity"]}', 3, 10, 2, true, 'type_dependent', 'trail'),
('Slope Angle Estimation', 'Estimate the steepness of terrain', 'math_real_world', 'numeric_entry', '{"question":"Estimate the slope angle (in degrees) of the steepest section of trail you can see. A flat surface is 0°. A vertical cliff is 90°. Most comfortable hiking slopes are 5-15°. Very steep trails are 25-35°.","unit":"degrees","hints":["5°: barely noticeable slope","15°: moderate uphill, you feel it","25°: steep, you lean forward","35°+: very steep, may need hands","Use your phone''s level app to check"]}', 4, 10, 2, true, 'type_dependent', 'trail'),
('Switchback Count and Analysis', 'Analyze switchback trail design', 'math_real_world', 'numeric_entry', '{"question":"If the trail has switchbacks (zigzag turns on a hillside), count them on a section. Estimate: the straight-line distance up the hill vs. the trail distance with switchbacks. By what factor does the trail multiply the distance?","unit":"multiplier","hints":["Switchbacks reduce steepness by increasing distance","A 2× multiplier means the trail is twice as long as straight up","Steeper hills need more switchbacks","The grade (steepness) of each switchback segment should be consistent"]}', 5, 10, 3, true, 'type_dependent', 'trail'),
('Nature Journaling', 'Create a detailed nature journal entry', 'reading_writing', 'creative_writing', '{"question":"Write a nature journal entry for this moment on the trail. Include: date, time, weather, location description, 3 detailed observations (plants, animals, geology), one sketch, and one question you want to investigate further.","hints":["Date and time establish context","Weather affects what you observe","Detailed observations use measurements and specifics","Good questions start with ''Why'' or ''How''"]}', 3, 10, 2, true, 'type_dependent', 'trail'),
('Terrain Navigation', 'Navigate using terrain features', 'geography_maps', 'short_text', '{"question":"Without looking at a map or GPS, describe your location using ONLY terrain features: ''I am on a south-facing slope, 50m below the ridgeline, near a stream junction, in a conifer forest.'' Use at least 4 terrain features in your description.","correct_answer":null,"hints":["Aspect: which direction does the slope face?","Position: top, middle, or bottom of slope?","Water: near a stream, lake, or dry?","Vegetation: what type of plants dominate?"]}', 5, 12, 3, true, 'type_dependent', 'trail'),

-- ── TASKS: Urban (10) ────────────────────────────────────────

('Building Material Survey', 'Catalog construction materials', 'history_community', 'data_collection', '{"question":"Look at 5 nearby buildings. For each, record the primary construction material (brick, concrete, glass, wood, stone, steel) and estimate the building''s age based on material and style. Do you see a pattern between material and age?","hints":["Wood: often oldest (but can be new)","Brick: common in 1800s-1950s","Concrete block: 1950s-1990s","Glass and steel: modern (1990s+)"]}', 4, 12, 2, true, 'type_dependent', 'urban'),
('Pedestrian Flow Analysis', 'Map how people move through a space', 'math_real_world', 'data_collection', '{"question":"Observe a busy area for 5 minutes. Draw arrows showing the main pedestrian flows. Count people per minute in the busiest direction. Where do paths converge? Where do people pause or stop?","hints":["Entrances create convergence points","People naturally take the shortest path","Bottlenecks slow flow (narrow sidewalks, doors)","''Desire lines'' in grass show preferred routes"]}', 4, 10, 2, true, 'type_dependent', 'urban'),
('Street Tree Assessment', 'Evaluate urban trees and their benefits', 'science_nature', 'data_collection', '{"question":"Survey 5 street trees. For each: species (if known), estimated height, trunk diameter, health condition (1-5), and what benefits it provides (shade, beauty, air quality, habitat, stormwater management).","hints":["Healthy trees: full canopy, no dead branches, intact bark","Trunk diameter at chest height (DBH) indicates age","Each large tree removes ~22 kg of CO2 per year","One large tree provides shade worth ~$100/year in energy savings"]}', 4, 10, 2, true, 'type_dependent', 'urban'),
('Signage Audit', 'Catalog all visible signs', 'reading_writing', 'data_collection', '{"question":"In your immediate view, count and classify every sign: commercial (business names/ads), regulatory (rules/laws), directional (wayfinding), informational (facts/history), and safety (warnings). Which category dominates? What does this tell you about this space?","hints":["Don''t forget small signs (hours, rules, labels)","Digital signs count","Graffiti and stickers are informal signs","Sign density reflects commercial activity level"]}', 3, 10, 2, true, 'type_dependent', 'urban'),
('Noise Level Estimation', 'Rate noise levels at different spots', 'science_nature', 'data_collection', '{"question":"Rate the noise level at 3 different spots within 100m on a scale of 1-10 (1=whisper quiet, 10=painfully loud). Identify the primary noise source at each spot. How does distance from traffic affect noise?","hints":["Normal conversation: ~60 dB (about 5/10)","Busy traffic: ~70-80 dB (about 7/10)","Quiet park: ~40 dB (about 3/10)","Every doubling of distance reduces noise by ~6 dB"]}', 4, 10, 2, true, 'type_dependent', 'urban'),
('Urban Heat Island Observation', 'Compare temperatures across surfaces', 'science_nature', 'data_collection', '{"question":"Touch (carefully) 4 different surfaces in the sun: dark asphalt, light concrete, grass, and metal. Rank them from hottest to coldest. Why does the color and material matter for temperature?","hints":["Dark surfaces absorb more solar radiation","Metal conducts heat quickly","Grass stays cool through transpiration (evaporating water)","Light-colored surfaces reflect more sunlight"]}', 3, 8, 2, true, 'type_dependent', 'urban'),
('Architectural Detail Hunt', 'Find specific architectural elements', 'history_community', 'data_collection', '{"question":"Find examples of these architectural elements near you: an arch, a column, a cornice (decorative ledge at roofline), a keystone (wedge at top of an arch), and a lintel (horizontal support above a door/window). Describe where you found each.","hints":["Arches: doorways, windows, bridges","Columns: building entrances, porches","Cornices: look at the roofline where wall meets roof","Lintels: the flat or slightly curved piece above a window"]}', 5, 12, 2, true, 'type_dependent', 'urban'),
('Business Zone Analysis', 'Classify businesses in the area', 'geography_maps', 'data_collection', '{"question":"List all businesses you can see from this spot. Classify each: essential services (grocery, medical), food/dining, retail/shopping, professional services, entertainment, or other. What does the mix tell you about this neighborhood?","hints":["Essential services = residential area nearby","Many restaurants = entertainment district or office area","Professional services = business district","The mix reflects the neighborhood''s character"]}', 5, 12, 2, true, 'type_dependent', 'urban'),
('Utility Infrastructure Map', 'Map visible utility infrastructure', 'history_community', 'sketch_draw', '{"question":"Draw a map showing all visible utility infrastructure: power lines, utility poles, fire hydrants, manholes, storm drains, traffic signals, and streetlights within your view. What pattern do you notice?","hints":["Utility poles follow roads","Fire hydrants are spaced every ~100m on main streets","Storm drains are at low points (often corners)","Manhole covers often align along underground routes"]}', 4, 10, 2, true, 'type_dependent', 'urban'),
('Green Space Ratio', 'Calculate the green vs gray ratio', 'math_real_world', 'numeric_entry', '{"question":"From where you stand, estimate the ratio of green space (trees, grass, gardens) to gray space (roads, buildings, concrete, asphalt). Express as a percentage of green space. Is this a healthy ratio for an urban area?","unit":"percent green","hints":["WHO recommends at least 9 sq m of green space per person","More green = better air quality, mental health, cooling","Most cities aim for 20-30% green space","Include vertical green (trees, green walls) in your estimate"]}', 4, 10, 2, true, 'type_dependent', 'urban'),

-- ── TASKS: Farm/Garden (8) ───────────────────────────────────

('Plant Growth Stage ID', 'Identify growth stages of plants', 'science_nature', 'multiple_choice', '{"question":"Find a plant and identify its current growth stage.","options":["Seedling (just sprouted, very small)","Vegetative (growing stems and leaves, no flowers)","Flowering (producing flowers)","Fruiting (flowers becoming fruit/seeds)","Dormant (not actively growing, may look dead)"],"correct_answer":"","hints":["Seedlings: small, often just two initial leaves","Vegetative: lots of new green growth","Flowering: blossoms visible","Fruiting: swollen flower base, developing fruit/seeds","Dormant: no new growth, often in winter"]}', 2, 8, 1, true, 'type_dependent', 'farm'),
('Soil Texture Test', 'Determine soil type by feel', 'science_nature', 'multiple_choice', '{"question":"Pick up a small handful of moist soil. Squeeze it. Try to roll it into a ribbon between your fingers. What type of soil is it?","options":["Sandy (gritty, falls apart, won''t form a ribbon)","Silty (smooth like flour, forms a short ribbon)","Clay (sticky, smooth, forms a long thin ribbon)","Loam (crumbly, holds together but breaks easily)","Rocky (mostly small stones with some soil)"],"correct_answer":"","hints":["Sandy: individual grains visible, feels gritty","Silty: feels like flour or talcum powder","Clay: shiny when rubbed, very sticky when wet","Loam: the ideal garden soil — a mix of all three"]}', 3, 8, 2, true, 'type_dependent', 'farm'),
('Row Spacing Mathematics', 'Calculate planting efficiency', 'math_real_world', 'numeric_entry', '{"question":"Measure the spacing between rows of plants (or between individual plants). If a garden bed is 3m × 10m, how many plants could fit at this spacing? Calculate: area ÷ (row spacing × plant spacing).","unit":"plants","hints":["Measure row spacing in centimeters","Measure plant-to-plant spacing within a row","Convert to meters if needed","Total = (bed length ÷ row spacing) × (bed width ÷ plant spacing)"]}', 4, 8, 2, true, 'type_dependent', 'farm'),
('Pollinator Count', 'Count pollinators visiting flowers', 'science_nature', 'data_collection', '{"question":"Watch a flowering plant or garden bed for 5 minutes. Count every pollinator visit. Record: type of pollinator (bee, butterfly, fly, beetle, hummingbird, other), which flower it visited, and how long it stayed.","hints":["Bees: fuzzy bodies, carry pollen on legs","Butterflies: large wings, long proboscis (tongue)","Hover flies: look like bees but hover in place","Different flowers attract different pollinators"]}', 2, 8, 2, true, 'type_dependent', 'farm'),
('Compost Investigation', 'Examine decomposition in compost or mulch', 'science_nature', 'data_collection', '{"question":"Find a compost pile, mulch bed, or decaying plant material. Examine it closely. Record: temperature (warm?), moisture level, organisms visible, stage of decomposition, and smell. What organisms are doing the work?","hints":["Warm compost = active decomposition","White threads (mycelium) = fungi at work","Small insects and worms = mechanical decomposition","Earthy smell = healthy decomposition; sour smell = too wet"]}', 3, 10, 2, true, 'type_dependent', 'farm'),
('Water Usage Estimation', 'Calculate water needs for a garden', 'math_real_world', 'numeric_entry', '{"question":"Estimate how much water this garden/farm area needs per week. Measure the area, then calculate: most gardens need about 2.5 cm (1 inch) of water per week. Convert to liters: 1 cm of water over 1 sq meter = 10 liters.","unit":"liters per week","hints":["Measure length × width for area in sq meters","2.5 cm per week is a common garden need","Liters = area (sq m) × 2.5 × 10","Drip irrigation uses less water than sprinklers"]}', 5, 10, 3, true, 'type_dependent', 'farm'),
('Crop Diversity Assessment', 'Evaluate diversity of planted crops', 'science_nature', 'data_collection', '{"question":"Count how many DIFFERENT types of plants are being grown in this garden/farm area. Classify each as: leafy green, root vegetable, fruit/berry, herb, flower, grain, or other. Is this garden diverse or monoculture?","hints":["Monoculture: one crop over large area (common in farms)","Polyculture: many crops mixed together (common in gardens)","Companion planting: certain plants help each other","Greater diversity = more resilient against pests"]}', 3, 8, 2, true, 'type_dependent', 'farm'),
('Pest and Beneficial Insect ID', 'Distinguish pests from beneficial insects', 'science_nature', 'data_collection', '{"question":"Search the garden for 5 minutes. Find and classify insects as: beneficial (pollinators, predators of pests), pest (eating/damaging plants), or neutral (neither helping nor harming). Record each with a description.","hints":["Beneficial: ladybugs eat aphids, bees pollinate, spiders eat pests","Pests: aphids, caterpillars eating leaves, whiteflies","Neutral: many beetles and flies are just passing through","The same insect can be beneficial in one context and pest in another"]}', 3, 10, 2, true, 'type_dependent', 'farm'),

-- ── TASKS: Forest (10) ───────────────────────────────────────

('Canopy Cover Estimation', 'Estimate the percentage of canopy cover', 'science_nature', 'numeric_entry', '{"question":"Look straight up. Estimate what percentage of the sky is blocked by tree canopy. Then check from 4 more spots 10m apart. Average your 5 readings. Is this a dense or open forest?","unit":"percent","hints":["0-25% = open forest or woodland","25-50% = moderate canopy","50-75% = dense forest","75-100% = very dense, old-growth-like canopy"]}', 3, 10, 2, true, 'type_dependent', 'forest'),
('Tree Girth and Age', 'Estimate tree age from trunk diameter', 'math_real_world', 'numeric_entry', '{"question":"Find the largest tree nearby. Measure its circumference at chest height (DBH) using your arms, a rope, or estimation. Calculate diameter (circumference ÷ π). Estimate age: most temperate trees grow about 2.5 cm (1 inch) in diameter per year.","unit":"years (estimated)","hints":["Wrap your arms around the tree — average arm span ≈ height","Circumference ÷ 3.14 = diameter","Diameter (cm) ÷ 2.5 ≈ age in years (rough estimate)","Fast-growing species are younger; slow-growing are older"]}', 4, 10, 2, true, 'type_dependent', 'forest'),
('Forest Floor Investigation', 'Study what lives on the forest floor', 'science_nature', 'data_collection', '{"question":"Carefully examine a 50cm × 50cm area of forest floor. Gently move leaf litter aside. Record everything you find: organisms (insects, worms, fungi), decomposition stages, root networks, and moisture level.","hints":["Go layer by layer: fresh leaves → old leaves → humus → soil","Fungi may be visible as white threads or small mushrooms","Isopods (roly-polies), millipedes, and beetles are common","The forest floor is the recycling center of the ecosystem"]}', 3, 10, 2, true, 'type_dependent', 'forest'),
('Light Gap Analysis', 'Study how light reaches the forest floor', 'science_nature', 'data_collection', '{"question":"Find a ''light gap'' (where sunlight reaches the forest floor through a break in the canopy). Compare: What plants grow IN the light gap vs. in the deep shade 5 meters away? How does the light gap affect the forest community?","hints":["Light gaps form when a tree falls or loses a branch","Fast-growing, sun-loving plants colonize gaps first","Shade-tolerant species grow in the dark areas","Light gaps are important for forest regeneration"]}', 4, 10, 3, true, 'type_dependent', 'forest'),
('Fallen Log Ecosystem', 'Survey organisms on a fallen log', 'science_nature', 'data_collection', '{"question":"Find a fallen log in various stages of decay. Survey it for life: fungi, moss, lichen, insects, larvae, plants growing on it, animal signs. Count the number of different species. A single log can support over 100 species!","hints":["Check the underside for moisture-loving organisms","Look for woodpecker holes and insect tunnels","Moss and lichen on the top surface indicate long decay","The more decayed, the more species usually present"]}', 3, 10, 2, true, 'type_dependent', 'forest'),
('Forest Sound Mapping', 'Map sounds at different heights', 'science_nature', 'data_collection', '{"question":"Stand still and listen for 2 minutes. Map sounds by HEIGHT: ground level (rustling, insects), mid-level (bird calls, wind in bushes), and canopy level (wind in treetops, high bird songs). What is the ''vertical soundtrack'' of this forest?","hints":["Ground: leaf rustling, insect buzzing, small animal movement","Mid-level: most bird songs, wind through branches","Canopy: wind in treetops, woodpecker drumming, hawk calls","Different species occupy different sound ''zones''"]}', 3, 10, 2, true, 'type_dependent', 'forest'),
('Bark Texture Collection', 'Compare bark textures across species', 'science_nature', 'data_collection', '{"question":"Find 5 trees with different bark textures. For each: describe the texture (smooth, rough, peeling, furrowed, scaly), color, pattern, and any organisms living on the bark (moss, lichen, insects). Can you identify the tree species from bark alone?","hints":["Birch: white, peeling horizontally","Oak: deeply furrowed, gray-brown","Pine: scaly plates, reddish-brown","Beech: smooth, gray, almost like skin"]}', 3, 8, 2, true, 'type_dependent', 'forest'),
('Forest Density Measurement', 'Measure tree density in an area', 'math_real_world', 'numeric_entry', '{"question":"Mark out a 10m × 10m area (estimate with steps). Count every tree with a trunk diameter > 5cm within that area. This gives you trees per 100 square meters. Multiply by 100 for trees per hectare.","unit":"trees per hectare","hints":["10 steps ≈ 7-8 meters (adjust for your step length)","Count only trees, not shrubs","Include both living and dead standing trees","Typical forest: 200-500 trees per hectare"]}', 5, 12, 3, true, 'type_dependent', 'forest'),
('Moss and Lichen Survey', 'Study epiphytes on trees', 'science_nature', 'photo_observation', '{"question":"Find a tree with visible moss or lichen. Take a photo. Which side of the tree has the most growth? Is it the north side? (This is a common myth — test it!) What conditions does moss prefer, and does your observation match?","hints":["Moss prefers moisture, shade, and cool surfaces","The ''north side'' myth varies by location and conditions","Check multiple trees to see if there''s a pattern","Lichen can grow on either side — it''s very tough"]}', 3, 10, 2, true, 'type_dependent', 'forest'),
('Leaf Litter Depth', 'Measure leaf litter depth across locations', 'science_nature', 'data_collection', '{"question":"Measure leaf litter depth at 5 different spots (under a tree, between trees, on a path, near water, on a slope). Use a stick pushed down to the soil surface. Record each depth in centimeters. Where is it deepest? Why?","hints":["Under deciduous trees: deepest in late autumn","On slopes: litter washes downhill","On paths: minimal litter due to foot traffic","Near water: litter may wash away or accumulate"]}', 3, 8, 2, true, 'type_dependent', 'forest');

-- Verify counts
-- SELECT location_type, count(*) FROM tasks WHERE is_library = true AND location_dependency = 'type_dependent' GROUP BY location_type;
-- Expected: park=12, water=10, mountain/trail=10, urban=10, farm=8, forest=10
-- Total: 80 tasks (some trail tasks tagged as 'mountain' or 'trail'), 30 primers
