-- ══════════════════════════════════════════════════════════════
-- Migration 022: Library expansion — 60 new primer+task pairs
--
-- 10 per subject domain × 6 domains = 60 pairs
-- Mixed grade bands (K-2, 3-5, 6-8, 9-12)
-- Mixed challenge types and difficulties
-- All marked is_library=true with full metadata
-- ══════════════════════════════════════════════════════════════

DO $$
DECLARE
  u_owner UUID;
  p UUID; t UUID; -- primer and task temp IDs
BEGIN
  SELECT id INTO u_owner FROM public.users WHERE email = 'mark.keith@gmail.com' LIMIT 1;
  IF u_owner IS NULL THEN
    SELECT id INTO u_owner FROM public.users WHERE role = 'admin' LIMIT 1;
  END IF;

  -- ═══════════════════════════════════════════════════════════
  -- SCIENCE & NATURE (10 pairs)
  -- ═══════════════════════════════════════════════════════════

  -- SN-1: Plant Parts (K-2, easy, photo_observation)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Parts of a Plant', '{"text":"Every plant has parts that help it survive. Roots drink water from the soil. Stems carry water up to the leaves. Leaves use sunlight to make food. Flowers make seeds so new plants can grow.","items":["Roots: underground, drink water","Stems: carry water and nutrients up","Leaves: make food from sunlight","Flowers: make seeds for new plants"]}', 'science_nature', 0, 2, true, 'independent', 'any', 2, ARRAY['plants','botany','life_science','parts'], ARRAY['nature_detective','young_scientist'], ARRAY['Identify the four main parts of a plant','Explain what each plant part does'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Find the Plant Parts', 'science_nature', 'photo_observation', '{"question":"Find a plant near you. Take a photo that shows at least 3 of its parts: roots (if visible), stem, leaves, or flowers. Point to each part in your photo and name it.","hints":["Look for a plant growing in soil or a crack","The stem is the part that holds the plant up","Leaves are usually green and flat","Not all plants have flowers — that is okay!"]}', 0, 2, 1, true, 'independent', 'any', 2, ARRAY['plants','botany','observation','life_science'], ARRAY['nature_detective','young_scientist'], ARRAY['Identify plant parts in the real world'], 5, u_owner);

  -- SN-2: Animal Habitats (K-2, easy, multiple_choice)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Where Animals Live', '{"text":"A habitat is an animal''s home. It gives animals food, water, shelter, and space. Different animals need different habitats. A fish needs water. A bird needs trees. A worm needs soil. When you look around outside, you are standing in somebody''s habitat!","items":["Habitat = an animal''s home with everything it needs","Pond habitat: frogs, fish, dragonflies","Tree habitat: birds, squirrels, insects","Underground habitat: worms, ants, moles"]}', 'science_nature', 0, 2, true, 'independent', 'any', 2, ARRAY['animals','habitats','ecology','homes'], ARRAY['nature_detective','young_scientist'], ARRAY['Define what a habitat is','Name animals that live in different habitats'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Habitat Match', 'science_nature', 'multiple_choice', '{"question":"Look around where you are standing right now. What type of habitat is this?","options":["Grassland (open area with mostly grass)","Forest (lots of trees and shade)","Urban (buildings, sidewalks, roads)","Wetland (near water, muddy ground)","Desert (dry, sandy, few plants)"],"correct_answer":"","hints":["Look at what covers the ground — grass? concrete? trees?","Is there water nearby?","Are there more buildings or more plants?","Any answer that matches what you see is correct!"]}', 0, 2, 1, true, 'independent', 'any', 2, ARRAY['animals','habitats','ecology'], ARRAY['nature_detective'], ARRAY['Classify a real-world habitat'], 3, u_owner);

  -- SN-3: Water Cycle (3-5, medium, sketch_draw)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'The Water Cycle', '{"text":"Water moves in a never-ending cycle. The sun heats water in oceans, lakes, and rivers, turning it into water vapor (evaporation). The vapor rises and cools into clouds (condensation). When clouds get heavy, water falls as rain or snow (precipitation). The water flows back to oceans through rivers and underground, and the cycle starts again.","items":["Evaporation: liquid → gas (sun heats water)","Condensation: gas → liquid (clouds form)","Precipitation: rain, snow, sleet, hail","Collection: water gathers in oceans, lakes, rivers"]}', 'science_nature', 3, 5, true, 'independent', 'any', 5, ARRAY['water_cycle','evaporation','condensation','precipitation','earth_science'], ARRAY['nature_detective','field_scientist'], ARRAY['Describe the four stages of the water cycle','Explain how the sun drives the water cycle'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Draw the Water Cycle', 'science_nature', 'sketch_draw', '{"question":"Draw the water cycle happening at your location right now. Include: the sun, a body of water (or wet ground), arrows showing evaporation going UP, a cloud forming, precipitation coming DOWN, and water flowing along the ground. Label all 4 stages.","hints":["Start with the sun at the top — it powers everything","Draw arrows going UP from water (evaporation)","Draw a cloud where vapor collects (condensation)","Draw rain/snow coming DOWN (precipitation)"]}', 3, 5, 2, true, 'independent', 'any', 5, ARRAY['water_cycle','diagram','earth_science'], ARRAY['nature_detective','field_scientist'], ARRAY['Diagram the water cycle with labels'], 8, u_owner);

  -- SN-4: Soil Layers (3-5, medium, data_collection)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'What Is Soil Made Of?', '{"text":"Soil is not just dirt — it is a complex mixture of minerals, organic matter (dead plants and animals), water, and air. The top layer (topsoil) is dark and rich with nutrients. Below that is subsoil (lighter, more clay). Below that is bedrock. Different locations have different soil compositions, which affects what can grow there.","items":["Topsoil: dark, rich, full of life","Subsoil: lighter color, more clay and minerals","Bedrock: solid rock underneath","Soil takes hundreds of years to form"]}', 'science_nature', 3, 5, true, 'independent', 'any', 5, ARRAY['soil','geology','earth_science','layers'], ARRAY['nature_detective','field_scientist'], ARRAY['Identify the components of soil','Describe soil layers'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Soil Sample Analysis', 'science_nature', 'data_collection', '{"question":"Collect a small handful of soil from the surface. Record: (1) Color (dark brown, light brown, red, gray), (2) Texture (sandy/gritty, smooth/clay, crumbly/loam), (3) Moisture (dry, damp, wet), (4) Visible organisms (worms, insects, roots — count them), (5) Smell (earthy, musty, none). Based on your data, is this good growing soil?","hints":["Dark soil usually has more organic matter — better for plants","Sandy soil drains fast; clay soil holds water","More organisms = healthier soil","Earthy smell means active decomposition — healthy!"]}', 3, 5, 2, true, 'independent', 'any', 5, ARRAY['soil','data','earth_science','observation'], ARRAY['field_scientist'], ARRAY['Collect and analyze soil data','Assess soil quality from observations'], 8, u_owner);

  -- SN-5: Photosynthesis (6-8, medium, short_text)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Photosynthesis: Nature''s Solar Panels', '{"text":"Plants are the original solar energy technology. Through photosynthesis, they capture sunlight and convert carbon dioxide and water into glucose (sugar) and oxygen. The chemical equation: 6CO2 + 6H2O + light energy → C6H12O6 + 6O2. This process happens in chloroplasts — tiny organelles in leaf cells that contain chlorophyll, the green pigment that absorbs light.","items":["Inputs: CO2 + H2O + sunlight","Outputs: glucose (food) + O2 (oxygen we breathe)","Happens in: chloroplasts (in leaf cells)","Chlorophyll: green pigment that absorbs light"]}', 'science_nature', 6, 8, true, 'independent', 'any', 6, ARRAY['photosynthesis','plants','energy','biology','chemistry'], ARRAY['nature_detective','field_scientist'], ARRAY['Explain the inputs and outputs of photosynthesis','Describe the role of chlorophyll'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Photosynthesis in Action', 'science_nature', 'short_text', '{"question":"Find a green plant and a non-green surface near each other (a rock, concrete, bare soil). Touch both. Which is cooler? Explain why using your knowledge of photosynthesis. Include: where the energy goes, what the plant produces, and why the non-green surface feels different.","correct_answer":null,"hints":["Plants use sunlight energy for photosynthesis instead of heating up","Non-green surfaces absorb sunlight as heat","The plant converts light energy into chemical energy (glucose)","Evaporation from leaves (transpiration) also cools plants"]}', 6, 8, 3, true, 'independent', 'any', 6, ARRAY['photosynthesis','energy_transfer','temperature'], ARRAY['field_scientist'], ARRAY['Apply photosynthesis concepts to real-world observations'], 5, u_owner);

  -- SN-6: Ecosystems and Energy Flow (6-8, hard, sketch_draw)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Energy Flow in Ecosystems', '{"text":"Energy flows through ecosystems in one direction: sun → producers → consumers → decomposers. At each level (trophic level), about 90% of energy is lost as heat. This is why food chains rarely have more than 4-5 levels. A food web shows all the interconnected food chains in an ecosystem.","items":["Producers (plants): convert sunlight to chemical energy","Primary consumers (herbivores): eat plants","Secondary consumers (carnivores): eat herbivores","Decomposers: break down dead organisms, recycle nutrients","Only ~10% of energy transfers between levels"]}', 'science_nature', 6, 8, true, 'independent', 'any', 7, ARRAY['ecosystems','food_web','energy','trophic_levels','ecology'], ARRAY['nature_detective','field_scientist'], ARRAY['Explain the 10% rule of energy transfer','Construct a food web from field observations'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Build a Food Web', 'science_nature', 'sketch_draw', '{"question":"Observe the organisms at your location for 3 minutes. Sketch a food web showing at least 3 producers and 2 consumers you can actually see or find evidence of. Draw arrows showing the direction of energy flow (from eaten → eater). Include one decomposer.","hints":["Producers: any green plants, algae, grass, moss","Primary consumers: insects, snails, seed-eating birds","Secondary consumers: spiders, lizards, predatory birds","Decomposers: fungi on wood, worms in soil — draw them at the bottom"]}', 6, 8, 3, true, 'independent', 'any', 7, ARRAY['food_web','ecosystem','observation','energy_flow'], ARRAY['field_scientist'], ARRAY['Construct a food web from direct observation'], 8, u_owner);

  -- SN-7: Weather vs Climate (3-5, easy, multiple_choice)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Weather vs Climate', '{"text":"Weather is what is happening in the atmosphere RIGHT NOW — sunny, rainy, windy, cold. Climate is the average weather pattern over many years. You can have a cold day in a warm climate! Weather changes daily; climate changes slowly over decades. Meteorologists study weather; climatologists study climate.","items":["Weather: today''s conditions (changes daily)","Climate: long-term average (changes over decades)","A cold day does NOT mean the climate is cold","Climate determines what plants and animals live in an area"]}', 'science_nature', 3, 5, true, 'independent', 'any', 3, ARRAY['weather','climate','atmosphere','earth_science'], ARRAY['field_scientist','explorer'], ARRAY['Distinguish between weather and climate'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Weather or Climate?', 'science_nature', 'multiple_choice', '{"question":"It is raining right now at your location. Is rain an example of WEATHER or CLIMATE?","options":["Weather — it describes what is happening right now","Climate — it describes the long-term pattern","Both — rain is always weather AND climate","Neither — rain is just water"],"correct_answer":"Weather — it describes what is happening right now","hints":["Think about the time scale: is this about today or about many years?","Weather changes day to day","Climate is the average over 30+ years","Today''s rain is a single weather event"]}', 3, 5, 1, true, 'independent', 'any', 3, ARRAY['weather','climate','classification'], ARRAY['field_scientist'], ARRAY['Classify observations as weather or climate'], 3, u_owner);

  -- SN-8: Adaptation (6-8, hard, creative_writing)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Adaptation: Survival Design', '{"text":"Every organism is shaped by its environment. Adaptations are traits that help an organism survive and reproduce. Structural adaptations are physical features (thick fur, long roots, sharp claws). Behavioral adaptations are actions (migration, hibernation, camouflage behavior). Over thousands of generations, natural selection favors organisms with adaptations that fit their environment.","items":["Structural: physical features (beaks, fur, roots)","Behavioral: actions (migration, nocturnal habits)","Physiological: body processes (venom production, cold tolerance)","Adaptations take many generations to develop"]}', 'science_nature', 6, 8, true, 'independent', 'any', 8, ARRAY['adaptation','evolution','natural_selection','biology'], ARRAY['nature_detective','field_scientist'], ARRAY['Distinguish structural, behavioral, and physiological adaptations','Explain how natural selection drives adaptation'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Adaptation Story', 'science_nature', 'creative_writing', '{"question":"Choose one organism you can see (a tree, bird, insect, weed growing from a crack). Write a 5-sentence adaptation story from its perspective: What is your biggest survival challenge in this specific location? What adaptation helps you survive? How would you struggle without it? What adaptation do you wish you had? What might you look like in 10,000 years?","hints":["Think about this specific location — what challenges does it present?","A tree in a windy area might have flexible branches (structural)","An urban pigeon has adapted to eat human food (behavioral)","Weeds in sidewalk cracks tolerate poor soil (physiological)"]}', 6, 8, 4, true, 'independent', 'any', 8, ARRAY['adaptation','perspective_writing','evolution'], ARRAY['nature_detective'], ARRAY['Apply adaptation concepts through creative perspective-taking'], 8, u_owner);

  -- SN-9: Biodiversity Index (9-12, hard, data_collection)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Measuring Biodiversity', '{"text":"Biodiversity is the variety of life in an area. Scientists measure it using diversity indices. The simplest is species richness (count of different species). A more useful measure is the Shannon Diversity Index, which accounts for both richness and evenness (how equally abundant each species is). Higher diversity generally indicates a healthier ecosystem.","items":["Species richness: how many different species","Species evenness: how equally distributed they are","Shannon Index H'' = -Σ(pi × ln pi)","Higher H'' = more diverse and stable ecosystem"]}', 'science_nature', 9, 12, true, 'independent', 'any', 9, ARRAY['biodiversity','ecology','statistics','sampling','index'], ARRAY['field_scientist'], ARRAY['Calculate species richness from field data','Explain why biodiversity matters for ecosystem health'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Biodiversity Survey', 'science_nature', 'data_collection', '{"question":"Mark out a 5m × 5m area. In 5 minutes, count every different species you can identify (plants, insects, birds, fungi — even if you can not name them, describe them). Record: species name or description, and count of individuals. Calculate: (1) Species richness (total species), (2) Total individuals, (3) Most abundant species, (4) Least abundant. Is this area high or low diversity?","hints":["Use categories if you can not identify: small brown beetle, tall grass, etc.","Count individuals of each type separately","Look under rocks, on bark, in the air","A healthy area might have 10+ species in 25 sq meters"]}', 9, 12, 4, true, 'independent', 'any', 9, ARRAY['biodiversity','survey','field_methods','data'], ARRAY['field_scientist'], ARRAY['Conduct a biodiversity survey using standard methods'], 10, u_owner);

  -- SN-10: Rock Cycle (9-12, medium, sorting_ordering)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'The Rock Cycle', '{"text":"Rocks are not permanent — they transform over millions of years through the rock cycle. Igneous rocks form when magma cools (granite, basalt). Sedimentary rocks form when sediments compact (sandstone, limestone, shale). Metamorphic rocks form when heat and pressure transform existing rocks (marble from limestone, slate from shale). Any rock type can become any other through different processes.","items":["Igneous: cooled magma/lava — often crystalline or glassy","Sedimentary: compressed layers — often has fossils, visible layers","Metamorphic: transformed by heat/pressure — often banded or foliated","Weathering + erosion breaks rocks into sediments"]}', 'science_nature', 9, 12, true, 'independent', 'any', 6, ARRAY['rocks','geology','rock_cycle','earth_science'], ARRAY['field_scientist','explorer'], ARRAY['Classify rocks by formation process','Describe the transformations in the rock cycle'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Rock Classification', 'science_nature', 'sorting_ordering', '{"question":"Find 4 different rocks near you. Sort them into categories: igneous (crystalline, glassy), sedimentary (layered, grainy, fossils), or metamorphic (banded, foliated, very hard). For each rock, describe 2 physical properties that support your classification.","items":["Igneous: crystals visible, no layers, may be glassy","Sedimentary: visible layers or grains, may have fossils","Metamorphic: banded patterns, very hard, distorted layers","Unknown: describe properties and make your best guess"],"hints":["Granite (igneous) has visible crystals of quartz, feldspar, mica","Sandstone (sedimentary) feels gritty and shows layers","Marble (metamorphic) is very hard and may have swirled patterns","If a rock has layers AND is very hard, it might be metamorphic"]}', 9, 12, 3, true, 'independent', 'any', 6, ARRAY['rocks','classification','geology'], ARRAY['field_scientist'], ARRAY['Classify rocks using physical properties'], 7, u_owner);


  -- ═══════════════════════════════════════════════════════════
  -- MATH & REAL WORLD (10 pairs)
  -- ═══════════════════════════════════════════════════════════

  -- M-1: Counting and Groups (K-2, easy, numeric_entry)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Counting in Groups', '{"text":"Counting one by one takes a long time when there are many things! Smart counters make groups of 2, 5, or 10, then skip-count. If you have 4 groups of 5 leaves, that is 5, 10, 15, 20 — much faster than counting 20 leaves one by one!","items":["Count by 2s: 2, 4, 6, 8, 10...","Count by 5s: 5, 10, 15, 20, 25...","Count by 10s: 10, 20, 30, 40, 50...","Make equal groups first, then multiply"]}', 'math_real_world', 0, 2, true, 'independent', 'any', 2, ARRAY['counting','groups','skip_counting','multiplication'], ARRAY['explorer','young_scientist'], ARRAY['Use skip counting to count large groups efficiently'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Skip Counting Challenge', 'math_real_world', 'numeric_entry', '{"question":"Find a group of many similar small objects (pebbles, leaves, sticks, flowers). Make groups of 5. How many groups can you make? How many total objects? Write: ___ groups of 5 = ___ total.","unit":"total objects","hints":["Put objects into piles of 5","Count the piles: 1 pile = 5, 2 piles = 10, 3 piles = 15","If you have leftover objects that do not make a full group, count them separately","Total = (groups × 5) + leftovers"]}', 0, 2, 1, true, 'independent', 'any', 2, ARRAY['counting','groups','multiplication'], ARRAY['young_scientist'], ARRAY['Practice skip counting with real objects'], 5, u_owner);

  -- M-2: Fractions in Nature (3-5, medium, photo_observation)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Fractions Are Everywhere', '{"text":"A fraction shows part of a whole. When you cut a pizza into 8 slices and eat 3, you ate 3/8. Nature is full of fractions: a flower with 5 petals where 2 have fallen off has 3/5 remaining. A tree with 4 branches where 1 is dead has 1/4 dead branches. Fractions help us describe the world precisely.","items":["Numerator (top): how many parts you are counting","Denominator (bottom): total number of equal parts","1/2 = one half, 1/4 = one quarter, 3/4 = three quarters","You can find fractions by dividing anything into equal parts"]}', 'math_real_world', 3, 5, true, 'independent', 'any', 5, ARRAY['fractions','parts','whole','math_concepts'], ARRAY['explorer'], ARRAY['Identify fractions in real-world observations'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Fraction Photo Hunt', 'math_real_world', 'photo_observation', '{"question":"Find 3 examples of fractions in your surroundings. Take a photo of each and write the fraction. Examples: a window with 2/6 panes open, a fence with 3/10 boards painted, a flower with 4/5 petals remaining. Be creative!","hints":["Look at rows of objects — how many are one color vs another?","Check windows, doors, fence posts, tiles","Nature: petals, leaves on a branch, ripe vs unripe fruit","Even a parking lot: 3/8 spaces occupied = a fraction!"]}', 3, 5, 2, true, 'independent', 'any', 5, ARRAY['fractions','real_world','observation'], ARRAY['explorer'], ARRAY['Identify and express fractions from real-world observations'], 7, u_owner);

  -- M-3: Angles in Architecture (6-8, medium, numeric_entry)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Angles in the Built World', '{"text":"Angles are everywhere in architecture and engineering. A right angle (90°) makes structures stable — that is why walls meet floors at 90°. Acute angles (<90°) appear in rooflines and bridges. Obtuse angles (>90°) create dramatic architectural features. Even the slope of a wheelchair ramp is a carefully calculated angle (usually 4.8° or less, per ADA requirements).","items":["Right angle: 90° — walls, corners, window frames","Acute angle: <90° — rooflines, bridge supports","Obtuse angle: >90° — awnings, some modern architecture","Straight angle: 180° — flat surfaces, horizons"]}', 'math_real_world', 6, 8, true, 'type_dependent', 'urban', 5, ARRAY['angles','geometry','architecture','measurement'], ARRAY['urban_explorer'], ARRAY['Identify angle types in built structures','Estimate angle measurements'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Angle Hunter', 'math_real_world', 'numeric_entry', '{"question":"Find the steepest angle you can see in a building or structure near you (a roofline, staircase, ramp, or architectural feature). Estimate the angle in degrees. Is it acute (<90°), right (=90°), or obtuse (>90°)? Describe what you measured.","unit":"degrees","hints":["A flat surface is 0°; a vertical wall is 90°","Most rooflines are between 20° and 45°","Staircases are usually 30° to 40°","Hold your arm at the angle to estimate — straight out is 0°, straight up is 90°"]}', 6, 8, 2, true, 'type_dependent', 'urban', 5, ARRAY['angles','estimation','measurement','geometry'], ARRAY['urban_explorer'], ARRAY['Estimate angles in the real world'], 5, u_owner);

  -- M-4: Percentages IRL (6-8, medium, data_collection)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Percentages in Daily Life', '{"text":"Percentages express parts per hundred. If 7 out of 10 cars in a parking lot are white, that is 70% white. Percentages help us compare groups of different sizes. A store with 3/5 items on sale has 60% on sale. Percentages are everywhere: battery levels, test scores, weather forecasts, nutrition labels.","items":["Percentage = (part / whole) × 100","50% = half, 25% = quarter, 10% = one-tenth","To find percentage: count the part, count the whole, divide, multiply by 100","Useful for comparing groups of different sizes"]}', 'math_real_world', 6, 8, true, 'independent', 'any', 5, ARRAY['percentages','ratios','data','real_world_math'], ARRAY['explorer','urban_explorer'], ARRAY['Calculate percentages from real-world counts'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Percentage Snapshot', 'math_real_world', 'data_collection', '{"question":"Pick one category to survey from where you stand: (A) vehicle colors in a parking area, (B) types of trees (deciduous vs evergreen), (C) people wearing hats vs not, or (D) windows open vs closed on a building. Count at least 20 items. Calculate the percentage for each category. Which category is most common?","hints":["Percentage = (count in category / total count) × 100","Example: 6 red cars out of 20 total = 6/20 × 100 = 30%","All percentages should add up to 100%","Round to the nearest whole number"]}', 6, 8, 2, true, 'independent', 'any', 5, ARRAY['percentages','data_collection','calculation'], ARRAY['explorer'], ARRAY['Calculate and interpret percentages from survey data'], 8, u_owner);

  -- M-5: Ratio and Proportion (9-12, hard, numeric_entry)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Scale and Proportion', '{"text":"Scale is the ratio between a representation and the real thing. A map at 1:10,000 means 1 cm on the map = 10,000 cm (100 m) in reality. Architects use scale drawings. Model makers use scale models. Understanding scale lets you calculate real dimensions from representations and vice versa.","items":["Scale = model size : real size","1:100 means the model is 100x smaller than reality","To find real size: model size × scale factor","To find model size: real size ÷ scale factor"]}', 'math_real_world', 9, 12, true, 'independent', 'any', 7, ARRAY['ratio','proportion','scale','measurement','algebra'], ARRAY['urban_explorer','explorer'], ARRAY['Apply scale ratios to calculate real-world dimensions'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Scale Model Challenge', 'math_real_world', 'numeric_entry', '{"question":"Choose a large object you can see (a building, tree, vehicle, monument). Measure or estimate its height. Now calculate: if you built a scale model at 1:50, how tall would the model be in centimeters? Show your work: real height → convert to cm → divide by 50.","unit":"cm","hints":["First estimate the real height in meters","Convert to centimeters: meters × 100","Divide by the scale factor (50)","A 10m building at 1:50 = 1000cm ÷ 50 = 20cm model"]}', 9, 12, 3, true, 'independent', 'any', 7, ARRAY['ratio','scale','calculation','algebra'], ARRAY['urban_explorer'], ARRAY['Calculate scale model dimensions from real measurements'], 5, u_owner);

  -- M-6: Area and Perimeter (3-5, easy, numeric_entry)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Area and Perimeter', '{"text":"Perimeter is the distance around the outside of a shape — like walking around a field. Area is the space inside a shape — like how much grass covers the field. For rectangles: perimeter = 2 × (length + width) and area = length × width. Knowing these helps with everything from painting a wall to fencing a yard.","items":["Perimeter: distance AROUND the edge","Area: space INSIDE the shape","Rectangle perimeter: 2 × (L + W)","Rectangle area: L × W"]}', 'math_real_world', 3, 5, true, 'independent', 'any', 3, ARRAY['area','perimeter','geometry','measurement'], ARRAY['explorer'], ARRAY['Calculate area and perimeter of rectangular objects'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Measure a Rectangle', 'math_real_world', 'numeric_entry', '{"question":"Find a rectangular object near you (a bench, sign, window, section of sidewalk). Measure its length and width in steps or hand-spans. Calculate the perimeter (2 × length + 2 × width) and area (length × width). Write all three numbers.","unit":"square steps (area)","hints":["Use your foot or hand-span as a consistent unit","Measure each side carefully — walk heel to toe","Perimeter: add up all four sides","Area: multiply length × width"]}', 3, 5, 1, true, 'independent', 'any', 3, ARRAY['area','perimeter','measurement'], ARRAY['explorer'], ARRAY['Measure and calculate area and perimeter'], 5, u_owner);

  -- M-7: Probability (6-8, medium, team_debate)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Probability in Everyday Life', '{"text":"Probability measures how likely something is to happen, from 0 (impossible) to 1 (certain). A fair coin has 0.5 probability of heads. Weather forecasts use probability: 40% chance of rain means that in similar conditions, it rains 4 out of 10 times. Understanding probability helps you make better decisions under uncertainty.","items":["0 = impossible, 1 = certain, 0.5 = equally likely","Probability = favorable outcomes / total possible outcomes","Independent events: coin flips, dice rolls","Dependent events: drawing cards without replacement"]}', 'math_real_world', 6, 8, true, 'independent', 'any', 6, ARRAY['probability','statistics','prediction','uncertainty'], ARRAY['explorer'], ARRAY['Estimate probabilities of real-world events','Distinguish certain, likely, unlikely, and impossible events'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Probability Debate', 'math_real_world', 'team_debate', '{"question":"Debate this question: If there is a 70% chance of rain tomorrow, should an outdoor school event be canceled? Person A argues YES — 70% is too risky. Person B argues NO — there is still a 30% chance it will not rain. Person C judges based on mathematical reasoning. Consider: what is the cost of canceling vs the cost of getting rained on?","hints":["70% means 7 out of 10 similar days would have rain","Consider severity: light drizzle vs thunderstorm matters","Cost of canceling: disappointed students, wasted planning","Cost of rain: wet students, damaged equipment, safety risk"]}', 6, 8, 3, true, 'independent', 'any', 6, ARRAY['probability','decision_making','risk','debate'], ARRAY['explorer'], ARRAY['Apply probability reasoning to real-world decisions'], 5, u_owner);

  -- M-8: Statistics: Mean, Median, Mode (3-5, medium, data_collection)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Three Ways to Find the Middle', '{"text":"When you have a group of numbers, there are three ways to describe the typical value. Mean (average): add all numbers and divide by how many. Median: line up numbers from smallest to largest and find the middle one. Mode: the number that appears most often. Each tells you something different about the data.","items":["Mean: total ÷ count (affected by very high/low numbers)","Median: middle value when sorted (not affected by extremes)","Mode: most frequent value (can have no mode or multiple modes)","Example: 2, 3, 3, 5, 12 → Mean=5, Median=3, Mode=3"]}', 'math_real_world', 3, 5, true, 'independent', 'any', 5, ARRAY['statistics','mean','median','mode','data'], ARRAY['field_scientist','explorer'], ARRAY['Calculate mean, median, and mode from collected data'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Measure and Average', 'math_real_world', 'data_collection', '{"question":"Find 7 similar objects (leaves, rocks, sticks, flowers). Measure the length of each in centimeters (or hand-widths). Write down all 7 measurements. Now calculate: (1) Mean: add all 7 and divide by 7. (2) Median: sort smallest to largest, find the middle one. (3) Mode: which measurement appears most often (if any)?","hints":["Line up objects from shortest to longest for median","Mean = total of all measurements ÷ 7","The median is the 4th number when sorted (middle of 7)","If no measurement repeats, there is no mode — that is okay"]}', 3, 5, 2, true, 'independent', 'any', 5, ARRAY['statistics','mean','median','mode','measurement'], ARRAY['field_scientist'], ARRAY['Calculate mean, median, and mode from field measurements'], 8, u_owner);

  -- M-9: Volume Estimation (K-2, easy, numeric_entry)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'How Much Space?', '{"text":"Volume is how much space something takes up. A big rock takes up more space than a small rock. A puddle takes up space. Your backpack takes up space. We can compare volumes by asking: which one would need a bigger box to fit inside?","items":["Big objects have more volume than small objects","Volume = the space inside something","We can compare: is this bigger or smaller than a lunchbox?","Water fills the shape of its container"]}', 'math_real_world', 0, 2, true, 'independent', 'any', 2, ARRAY['volume','space','comparison','measurement'], ARRAY['young_scientist','explorer'], ARRAY['Compare volumes of real objects'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Volume Lineup', 'math_real_world', 'numeric_entry', '{"question":"Find 5 objects near you that are different sizes. Sort them from smallest volume (takes up least space) to largest volume (takes up most space). How many of the smallest object could fit inside the largest? Estimate!","unit":"small objects fitting in largest","hints":["Think about the space INSIDE each object","A rock, a leaf, a shoe, a backpack, a bench...","To estimate: imagine stacking the small ones inside the big one","It is okay to guess — estimation is a real math skill!"]}', 0, 2, 1, true, 'independent', 'any', 2, ARRAY['volume','estimation','comparison'], ARRAY['young_scientist'], ARRAY['Estimate volume comparisons between real objects'], 5, u_owner);

  -- M-10: Rate and Speed (9-12, hard, numeric_entry)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Rates of Change', '{"text":"A rate describes how one quantity changes relative to another. Speed is a rate: distance per unit time (km/h, m/s). Growth rate: change per year. Flow rate: volume per second. Rates let us predict: at this speed, how long until arrival? At this growth rate, how big in 5 years? Understanding rates is fundamental to physics, economics, and engineering.","items":["Rate = change in quantity / change in time","Speed = distance / time","Unit rates convert to per-one: 60 km/hr = 1 km/min","Rates can be constant (uniform motion) or variable (acceleration)"]}', 'math_real_world', 9, 12, true, 'independent', 'any', 8, ARRAY['rate','speed','algebra','physics','calculation'], ARRAY['field_scientist','explorer'], ARRAY['Calculate rates from field measurements','Apply rate concepts to predict outcomes'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Speed Calculation', 'math_real_world', 'numeric_entry', '{"question":"Measure a distance of exactly 20 meters (about 25 big steps). Walk it at normal pace and time yourself in seconds. Calculate your walking speed in m/s. Then convert to km/h (multiply by 3.6). How long would it take you to walk 1 km at this speed?","unit":"km/h","hints":["Speed = distance / time = 20m / your_seconds","To convert m/s to km/h: multiply by 3.6","Average walking speed is about 1.4 m/s = 5 km/h","Time to walk 1 km = 1000m / (your speed in m/s) seconds"]}', 9, 12, 4, true, 'independent', 'any', 8, ARRAY['speed','rate','unit_conversion','measurement'], ARRAY['field_scientist'], ARRAY['Calculate speed and convert between units'], 5, u_owner);


  -- ═══════════════════════════════════════════════════════════
  -- GEOGRAPHY & MAPS (10 pairs)
  -- ═══════════════════════════════════════════════════════════

  -- G-1: Cardinal Directions (K-2, easy, multiple_choice)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'North, South, East, West', '{"text":"There are four main directions called cardinal directions: North, South, East, and West. The sun rises in the East and sets in the West. If you face the sunrise, North is to your left and South is to your right. A compass always points North. Knowing directions helps you find your way anywhere!","items":["North: toward the North Pole (usually toward mountains in Utah)","South: toward the equator","East: where the sun rises","West: where the sun sets"]}', 'geography_maps', 0, 2, true, 'independent', 'any', 2, ARRAY['directions','cardinal','compass','navigation'], ARRAY['explorer','young_scientist'], ARRAY['Name the four cardinal directions','Use the sun to determine direction'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Find Your Directions', 'geography_maps', 'multiple_choice', '{"question":"Point to where the sun is (or would be if cloudy). If that is roughly East in the morning or West in the afternoon, point North. What is to your North?","options":["A building","Trees or plants","A road or path","Mountains or hills","Something else"],"correct_answer":"","hints":["The sun rises in the East (morning)","The sun sets in the West (afternoon)","If you face East, North is to your LEFT","Any answer is correct — just tell us what you see to the North!"]}', 0, 2, 1, true, 'independent', 'any', 2, ARRAY['directions','cardinal','observation'], ARRAY['explorer'], ARRAY['Determine cardinal directions using the sun'], 3, u_owner);

  -- G-2: Map Symbols (3-5, easy, sorting_ordering)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Reading Map Symbols', '{"text":"Maps use symbols to represent real things. A blue line means a river. A green area means a park or forest. A dotted line means a trail. A small square means a building. Map symbols save space — you can not draw every tree, so one symbol represents the whole forest. The legend (or key) explains what each symbol means.","items":["Blue: water (rivers, lakes, oceans)","Green: parks, forests, vegetation","Brown: elevation contours, dirt roads","Black: roads, buildings, text","Red: highways, important features"]}', 'geography_maps', 3, 5, true, 'independent', 'any', 3, ARRAY['maps','symbols','legend','cartography'], ARRAY['explorer'], ARRAY['Interpret standard map symbols','Use a map legend'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Create Map Symbols', 'geography_maps', 'sorting_ordering', '{"question":"Look around you and pick 4 features you can see (a tree, a building, a path, water, etc.). For each, create your own map symbol — a simple drawing that represents it. Then sort your symbols from most important for navigation to least important.","items":["Critical for navigation (roads, paths, landmarks)","Important for orientation (large buildings, water features)","Helpful context (trees, grass areas, benches)","Nice to know (decorative features, small objects)"],"hints":["Map symbols should be simple — draw them in under 5 seconds","Think about what a lost person would need most","Roads and paths are usually most important for navigation","A good symbol looks a little like the real thing"]}', 3, 5, 1, true, 'independent', 'any', 3, ARRAY['maps','symbols','design','cartography'], ARRAY['explorer'], ARRAY['Design map symbols for real features'], 7, u_owner);

  -- G-3: Latitude and Longitude (6-8, medium, numeric_entry)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'GPS Coordinates Explained', '{"text":"Every point on Earth has a unique address made of two numbers: latitude (how far north or south of the equator, 0° to 90°) and longitude (how far east or west of the Prime Meridian, 0° to 180°). Your phone''s GPS uses satellites to determine these numbers to within a few meters. Positive latitude = North; negative = South. Negative longitude = West (the Americas).","items":["Latitude: N/S position (equator = 0°)","Longitude: E/W position (Prime Meridian = 0°)","Written as: (latitude, longitude) e.g., (40.25, -111.65)","1 degree of latitude ≈ 111 km"]}', 'geography_maps', 6, 8, true, 'independent', 'any', 6, ARRAY['gps','coordinates','latitude','longitude','navigation'], ARRAY['explorer','urban_explorer'], ARRAY['Read and interpret GPS coordinates','Understand the latitude-longitude system'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'GPS Detective', 'geography_maps', 'numeric_entry', '{"question":"Open your phone''s compass or maps app and find your current GPS coordinates. Write down your latitude and longitude to 4 decimal places. Now walk exactly 50 steps North. Check your coordinates again. How much did your latitude change? Calculate: how many meters per 0.0001° of latitude?","unit":"meters per 0.0001 degree","hints":["Latitude increases as you go North","50 steps ≈ 30-40 meters for most people","The change should be in the 4th decimal place","1 degree latitude ≈ 111,000 meters, so 0.0001° ≈ 11 meters"]}', 6, 8, 3, true, 'independent', 'any', 6, ARRAY['gps','coordinates','measurement','calculation'], ARRAY['explorer'], ARRAY['Measure real-world distance in GPS coordinate units'], 5, u_owner);

  -- G-4: Topographic Maps (9-12, hard, sketch_draw)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Reading Topographic Maps', '{"text":"Topographic maps use contour lines to show elevation. Each contour line connects points of equal elevation. Lines close together = steep slope. Lines far apart = gentle slope. Closed circles = hilltops. V-shaped contours pointing uphill indicate valleys with streams. The contour interval (elevation difference between lines) is shown in the legend.","items":["Contour lines: connect points of equal elevation","Close together = steep; far apart = flat","Closed circles = peaks or depressions","V-shapes pointing upstream = river valleys","Index contours (thicker lines) are labeled with elevation"]}', 'geography_maps', 9, 12, true, 'type_dependent', 'trail', 8, ARRAY['topography','contour_lines','elevation','maps','terrain'], ARRAY['field_scientist','nature_detective'], ARRAY['Interpret contour lines on topographic maps','Create a basic contour map from field observations'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Contour Map Sketch', 'geography_maps', 'sketch_draw', '{"question":"Find a small hill, slope, or uneven ground near you. Sketch a topographic map of it with at least 5 contour lines. Include: a scale estimate, North arrow, and labels for the highest and lowest points. Mark any steep sections with closely spaced lines.","hints":["Walk the area first to understand the shape","Start with the lowest elevation as your baseline contour","Each line up represents a fixed elevation increase","Close lines = steep, spread out lines = gentle slope"]}', 9, 12, 4, true, 'type_dependent', 'trail', 8, ARRAY['topography','contour','mapping','field_methods'], ARRAY['field_scientist'], ARRAY['Create a contour map from field observation'], 10, u_owner);

  -- G-5: Land Use (6-8, medium, data_collection)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Land Use Patterns', '{"text":"Land use describes how humans use the surface of the Earth. The main categories are: residential (housing), commercial (businesses), industrial (factories), agricultural (farming), recreational (parks), and transportation (roads, railways). Urban geographers study land use patterns to understand how cities grow, change, and function.","items":["Residential: houses, apartments","Commercial: stores, offices, restaurants","Industrial: factories, warehouses","Recreational: parks, sports fields, trails","Transportation: roads, parking, railways","Mixed use: buildings with multiple functions"]}', 'geography_maps', 6, 8, true, 'type_dependent', 'urban', 5, ARRAY['land_use','urban_geography','zoning','city_planning'], ARRAY['urban_explorer'], ARRAY['Classify land use types in an urban area'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Land Use Survey', 'geography_maps', 'data_collection', '{"question":"Look in every direction from where you stand. Classify everything visible into land use categories: Residential, Commercial, Industrial, Recreational, Transportation, or Natural/Undeveloped. Estimate what percentage of the visible area each category covers. Which dominates? Why do you think this area developed this way?","hints":["Roads and parking count as Transportation","Parks and playgrounds are Recreational","Look up too — how many floors of apartments vs offices?","Historical reasons often explain current land use patterns"]}', 6, 8, 2, true, 'type_dependent', 'urban', 5, ARRAY['land_use','survey','urban_geography','data'], ARRAY['urban_explorer'], ARRAY['Survey and classify land use in a real environment'], 8, u_owner);

  -- G-6: Watershed Concepts (3-5, medium, photo_observation)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Where Does Rain Go?', '{"text":"When rain falls, it has to go somewhere. It flows downhill following the shape of the land, collecting in streams, rivers, and eventually oceans. A watershed is all the land that drains into one body of water. You are standing in a watershed right now! Everything that happens on the land — fertilizer, oil, litter — can end up in the water downstream.","items":["Watershed: all land draining to one water body","Rain flows downhill — always","Impervious surfaces (concrete, asphalt) cause faster runoff","Permeable surfaces (grass, soil) absorb water"]}', 'geography_maps', 3, 5, true, 'independent', 'any', 5, ARRAY['watershed','water','runoff','drainage','hydrology'], ARRAY['nature_detective','field_scientist'], ARRAY['Explain what a watershed is','Predict water flow direction from terrain'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Raindrop Race', 'geography_maps', 'photo_observation', '{"question":"If a raindrop fell exactly where you are standing, which direction would it flow? Follow the slope with your eyes as far as you can. Take a photo showing the path water would take (look for existing evidence: water stains, erosion channels, drain grates, puddle marks). Where would the water end up?","hints":["Water always flows to the lowest point","Look for subtle slopes — even parking lots have drainage angles","Stains on concrete show where water regularly flows","Drain grates show where engineers direct water"]}', 3, 5, 2, true, 'independent', 'any', 5, ARRAY['watershed','drainage','observation','hydrology'], ARRAY['nature_detective'], ARRAY['Trace water flow paths in the real environment'], 7, u_owner);

  -- G-7: Human Migration (9-12, hard, creative_writing)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Push and Pull Factors', '{"text":"People migrate for reasons that geographers classify as push factors (reasons to leave: war, famine, persecution, natural disasters) and pull factors (reasons to come: jobs, freedom, safety, education, family). Most migration involves both. The history of any community can be understood through the push-pull lens: why did people originally settle here? What keeps people here now? What makes people leave?","items":["Push: war, poverty, persecution, disasters, lack of opportunity","Pull: jobs, safety, freedom, education, family, climate","Voluntary migration: choice-driven (better job, school)","Forced migration: no choice (refugees, displaced peoples)"]}', 'geography_maps', 9, 12, true, 'independent', 'any', 8, ARRAY['migration','push_pull','human_geography','demographics'], ARRAY['urban_explorer','explorer'], ARRAY['Analyze push and pull factors in migration decisions'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Migration Story', 'geography_maps', 'creative_writing', '{"question":"Look at the community around you. Write a short analysis (5-7 sentences): What push and pull factors likely brought people to THIS specific area? Consider the geography (mountains, water, fertile land), economy (what industries are nearby), and infrastructure (schools, hospitals, transportation). What might push people away from here in the future?","hints":["Original settlers chose locations for water, farmland, or trade routes","Modern pull factors: universities, tech companies, quality of life","Push factors today: cost of living, traffic, natural disaster risk","Consider climate change as a future push/pull factor"]}', 9, 12, 4, true, 'independent', 'any', 8, ARRAY['migration','analysis','community','geography'], ARRAY['urban_explorer'], ARRAY['Analyze push-pull factors in a real community'], 8, u_owner);

  -- G-8: Climate Zones (3-5, medium, audio_response)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Climate Zones of the World', '{"text":"Earth has different climate zones based on temperature and rainfall. Tropical zones near the equator are hot and wet year-round. Temperate zones (like most of the US) have four seasons. Polar zones near the poles are cold year-round. Arid (desert) zones get very little rain. Mountains create their own climate zones — it gets colder as you go higher.","items":["Tropical: hot + wet all year (rainforests)","Temperate: four seasons, moderate rain","Arid: very dry, hot or cold deserts","Polar: cold year-round, little precipitation","Alpine: changes with altitude on mountains"]}', 'geography_maps', 3, 5, true, 'independent', 'any', 4, ARRAY['climate','zones','weather','earth_science'], ARRAY['explorer','field_scientist'], ARRAY['Name the major climate zones','Classify their local climate zone'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Climate Zone Report', 'geography_maps', 'audio_response', '{"question":"Record a 45-second audio report about what climate zone you are in right now. Include: (1) Name the climate zone, (2) Describe today''s weather as evidence, (3) What does this area look like in summer vs winter?, (4) Name one plant or animal adapted to this climate zone.","hints":["Most of the US is in the temperate zone","If you are in Utah: temperate, semi-arid, continental","Describe what you actually see and feel right now","Think about how different this spot looks in January vs July"]}', 3, 5, 2, true, 'independent', 'any', 4, ARRAY['climate','zones','observation','presentation'], ARRAY['explorer'], ARRAY['Identify and describe their local climate zone'], 5, u_owner);

  -- G-9: Map Scale (K-2, easy, sketch_draw)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Maps Are Small Pictures of Big Places', '{"text":"A map is like a tiny picture of a big place, seen from above. Imagine you are a bird looking down — that is what a map shows. A map of your classroom would show desks as small rectangles. A map of your playground would show the slide, swings, and field. Everything is shrunk to fit on paper.","items":["Maps show places from above (bird''s eye view)","Big things in real life = smaller on maps","A building is a rectangle on a map","Trees might be small circles on a map"]}', 'geography_maps', 0, 2, true, 'independent', 'any', 2, ARRAY['maps','scale','bird_eye','spatial'], ARRAY['young_scientist','explorer'], ARRAY['Understand that maps represent real places from above'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Draw Your Spot', 'geography_maps', 'sketch_draw', '{"question":"Pretend you are a bird flying above where you are standing. Draw a map of what you see below. Include at least 3 things: paths, buildings, trees, benches, or anything else you can see. Make big things bigger on your map and small things smaller.","hints":["Look down from above — like a bird!","Draw the ground, not the sky","A tree looks like a circle from above","A path looks like a long thin line from above"]}', 0, 2, 1, true, 'independent', 'any', 2, ARRAY['maps','drawing','spatial','bird_eye'], ARRAY['young_scientist'], ARRAY['Draw a simple bird''s-eye-view map'], 8, u_owner);

  -- G-10: GIS and Spatial Data (9-12, hard, short_text)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Geographic Information Systems', '{"text":"GIS (Geographic Information Systems) layer different types of data on maps. One layer might show roads, another population density, another pollution levels, another flood risk. By stacking layers, analysts find patterns invisible in any single dataset. Your phone is a GIS device — it layers your position, nearby businesses, traffic, and weather on one map.","items":["Layer 1: Base map (roads, buildings, terrain)","Layer 2: Demographic data (population, income)","Layer 3: Environmental data (pollution, vegetation)","Layer 4: Infrastructure (utilities, emergency services)","Spatial analysis: finding patterns by overlapping layers"]}', 'geography_maps', 9, 12, true, 'independent', 'any', 9, ARRAY['gis','spatial_analysis','data_layers','technology'], ARRAY['urban_explorer','field_scientist'], ARRAY['Explain how GIS layers reveal spatial patterns','Identify real-world applications of spatial data'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Mental GIS Layers', 'geography_maps', 'short_text', '{"question":"Imagine you could see 5 invisible data layers overlaid on the view in front of you: (1) underground utilities, (2) property boundaries, (3) noise levels, (4) air quality, (5) historical land use 100 years ago. Pick 2 layers and describe what you think they would reveal at this exact spot. What decisions would this data inform?","correct_answer":null,"hints":["Underground: water pipes, gas lines, internet cables, sewers","Property boundaries: who owns what — often surprising","Noise: traffic, construction, nature — varies by time of day","Historical: this spot likely looked very different 100 years ago"]}', 9, 12, 4, true, 'independent', 'any', 9, ARRAY['gis','spatial_thinking','analysis','data'], ARRAY['urban_explorer'], ARRAY['Apply GIS thinking to analyze a real location'], 5, u_owner);


  -- ═══════════════════════════════════════════════════════════
  -- CRITICAL THINKING (10 pairs)
  -- ═══════════════════════════════════════════════════════════

  -- CT-1: Observation vs Inference (K-2, easy, short_text)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'See It or Think It?', '{"text":"An observation is something you can see, hear, smell, touch, or taste RIGHT NOW. An inference is a guess based on what you observe. Observation: The ground is wet. Inference: It rained. But maybe someone spilled water! Good thinkers keep observations and inferences separate.","items":["Observation: I can see/hear/feel this right now","Inference: I THINK this happened based on clues","Observations are facts; inferences are guesses","Good scientists separate the two"]}', 'critical_thinking', 0, 2, true, 'independent', 'any', 2, ARRAY['observation','inference','thinking','logic'], ARRAY['young_scientist','explorer'], ARRAY['Distinguish observations from inferences'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Observation or Inference?', 'critical_thinking', 'short_text', '{"question":"Look around and write 2 OBSERVATIONS (things you can directly see right now) and 2 INFERENCES (guesses about what you think happened based on what you see). Label each one clearly. Example: Observation: There is a puddle. Inference: It rained recently.","correct_answer":null,"hints":["Observations use your senses: I see, I hear, I smell, I feel","Inferences use your brain: I think, I guess, probably, maybe","Observations are always true; inferences might be wrong","A good scientist always checks their inferences"]}', 0, 2, 1, true, 'independent', 'any', 2, ARRAY['observation','inference','thinking'], ARRAY['young_scientist'], ARRAY['Practice separating observations from inferences'], 5, u_owner);

  -- CT-2: Cause and Effect (3-5, medium, photo_observation)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Cause and Effect Detectives', '{"text":"Everything that happens has a cause (what made it happen) and an effect (what resulted). A cause can have multiple effects, and an effect can have multiple causes. Detectives look at effects (broken window) and work backward to find causes (baseball? storm? age?). Scientists do the same thing — they observe effects in nature and figure out what caused them.","items":["Cause: what made it happen","Effect: what resulted","One cause can have many effects","One effect can have many causes"]}', 'critical_thinking', 3, 5, true, 'independent', 'any', 5, ARRAY['cause_effect','reasoning','analysis','logic'], ARRAY['nature_detective','explorer'], ARRAY['Identify cause-and-effect relationships in the environment'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Cause and Effect Photo', 'critical_thinking', 'photo_observation', '{"question":"Find 2 examples of cause and effect in your surroundings. Take a photo of each EFFECT and describe the CAUSE. Examples: worn path (cause: many people walking), bent tree (cause: wind), crack in sidewalk (cause: tree root or ice). Write the cause for each photo.","hints":["Look for damage, wear, growth patterns, stains","Erosion is caused by water or wind","Paths form where people repeatedly walk","Plants grow toward sunlight (cause: light, effect: bent stem)"]}', 3, 5, 2, true, 'independent', 'any', 5, ARRAY['cause_effect','observation','analysis'], ARRAY['nature_detective'], ARRAY['Identify and photograph cause-effect relationships'], 7, u_owner);

  -- CT-3: Evidence-Based Claims (6-8, medium, short_text)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Making Claims with Evidence', '{"text":"A claim is a statement you believe is true. Evidence is the data that supports your claim. Reasoning explains HOW the evidence supports the claim. This is called CER (Claim-Evidence-Reasoning) — the foundation of scientific argument. Strong claims have multiple pieces of evidence. Weak claims rely on opinion without evidence.","items":["Claim: what you believe is true","Evidence: observable data that supports the claim","Reasoning: explains why the evidence supports the claim","Strong argument = Claim + Evidence + Reasoning (CER)"]}', 'critical_thinking', 6, 8, true, 'independent', 'any', 6, ARRAY['claims','evidence','reasoning','cer','argument'], ARRAY['field_scientist','explorer'], ARRAY['Construct evidence-based claims using the CER framework'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'CER Challenge', 'critical_thinking', 'short_text', '{"question":"Make ONE claim about this location using the CER framework. CLAIM: state something you believe is true about this place. EVIDENCE: list 2-3 things you can observe that support your claim. REASONING: explain why your evidence proves your claim. Example claim: This area is well-maintained.","correct_answer":null,"hints":["Good claims are specific and testable","Evidence must be observable — not opinions","Reasoning connects the dots: evidence → claim","Challenge yourself: can someone argue against your claim?"]}', 6, 8, 3, true, 'independent', 'any', 6, ARRAY['cer','claims','evidence','scientific_argument'], ARRAY['field_scientist'], ARRAY['Apply CER framework to real-world observations'], 5, u_owner);

  -- CT-4: Perspective Taking (3-5, medium, creative_writing)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Seeing Through Other Eyes', '{"text":"Different people see the same place differently. A gardener notices plants. An architect notices buildings. A child notices places to play. A person in a wheelchair notices steps and ramps. Perspective taking means imagining how someone else experiences the world. It is one of the most important thinking skills you can develop.","items":["Your perspective = what YOU notice based on YOUR experience","Others'' perspective = what THEY notice based on THEIR experience","No perspective is wrong — they are just different","Empathy: understanding how someone else feels"]}', 'critical_thinking', 3, 5, true, 'independent', 'any', 5, ARRAY['perspective','empathy','point_of_view','thinking'], ARRAY['explorer','urban_explorer'], ARRAY['Practice perspective-taking by imagining different viewpoints'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Three Perspectives', 'critical_thinking', 'creative_writing', '{"question":"Describe this exact spot from 3 different perspectives: (1) A bird flying overhead, (2) An ant on the ground, (3) A person visiting for the very first time. Write 2 sentences for each perspective. What would each one notice that the others would miss?","hints":["The bird sees the big picture: layout, patterns, movement","The ant sees tiny details: cracks, crumbs, textures, shadows","The first-time visitor notices things you have stopped seeing","Each perspective reveals something the others miss"]}', 3, 5, 2, true, 'independent', 'any', 5, ARRAY['perspective','creative_thinking','empathy','writing'], ARRAY['explorer'], ARRAY['Describe a location from multiple perspectives'], 8, u_owner);

  -- CT-5: Systems Thinking (9-12, hard, data_collection)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Everything Is Connected', '{"text":"Systems thinking means seeing how parts of a system interact and influence each other. A school is a system: students, teachers, buildings, schedules, budgets — change one and the others adjust. Ecosystems, cities, economies, and even your body are systems. Feedback loops (where an output becomes an input) are especially important: positive loops amplify change, negative loops stabilize it.","items":["System: interconnected parts working together","Feedback loop: output feeds back as input","Positive feedback: amplifies (snowball effect)","Negative feedback: stabilizes (thermostat)","Emergent property: behavior that only appears at the system level"]}', 'critical_thinking', 9, 12, true, 'independent', 'any', 9, ARRAY['systems_thinking','feedback_loops','complexity','interdependence'], ARRAY['field_scientist','urban_explorer'], ARRAY['Identify system components and feedback loops','Explain emergent properties'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'System Map', 'critical_thinking', 'data_collection', '{"question":"Identify a system visible from where you stand (a garden, a building, a street intersection, a pond). List at least 6 components of the system and draw arrows showing how they influence each other. Identify ONE feedback loop (positive or negative). What would happen if you removed one component?","hints":["Components can be physical (road, drain) or abstract (traffic flow, rules)","Arrows show influence: A → B means A affects B","A feedback loop goes in a circle: A → B → C → A","Removing a component reveals which others depend on it"]}', 9, 12, 4, true, 'independent', 'any', 9, ARRAY['systems','feedback','analysis','complexity'], ARRAY['field_scientist'], ARRAY['Map system components and identify feedback loops'], 10, u_owner);

  -- CT-6: Bias Detection (6-8, hard, short_text)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Spotting Hidden Bias', '{"text":"Bias is a preference for or against something that is not based on fair reasoning. Confirmation bias: noticing only evidence that supports what you already believe. Selection bias: only looking in places where you expect to find something. Design bias: when the way something is built favors one group over another. Even scientists must guard against bias in their experiments.","items":["Confirmation bias: seeing only what you expect","Selection bias: looking only where you expect to find something","Design bias: built to favor one group","Anchoring bias: over-relying on the first piece of information"]}', 'critical_thinking', 6, 8, true, 'independent', 'any', 7, ARRAY['bias','critical_thinking','reasoning','fairness'], ARRAY['explorer','urban_explorer'], ARRAY['Identify different types of bias','Recognize bias in real-world design'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Bias Spotter', 'critical_thinking', 'short_text', '{"question":"Find ONE example of design bias in your surroundings — something that was designed in a way that works better for some people than others. Describe: (1) What is it? (2) Who does it favor? (3) Who does it disadvantage? (4) How could it be redesigned to be more fair?","correct_answer":null,"hints":["Steps without a ramp = bias against wheelchair users","Signs only in English = bias against non-English speakers","Playground equipment too tall for young children = age bias","Park benches with armrests in the middle = designed to prevent sleeping"]}', 6, 8, 3, true, 'independent', 'any', 7, ARRAY['bias','design','fairness','analysis'], ARRAY['urban_explorer'], ARRAY['Identify and analyze design bias in the built environment'], 5, u_owner);

  -- CT-7: Logical Fallacies (9-12, hard, team_debate)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Common Logical Fallacies', '{"text":"A logical fallacy is an error in reasoning that makes an argument invalid. Ad hominem: attacking the person instead of the argument. Straw man: misrepresenting someone''s argument to make it easier to attack. False dichotomy: presenting only two options when more exist. Appeal to authority: assuming something is true because an authority said it. Recognizing fallacies makes you a stronger critical thinker.","items":["Ad hominem: attacking the person, not the argument","Straw man: misrepresenting the opposing view","False dichotomy: only two options when more exist","Appeal to authority: true because an expert said so","Slippery slope: small step leads to extreme outcome"]}', 'critical_thinking', 9, 12, true, 'independent', 'any', 9, ARRAY['fallacies','logic','argument','reasoning','debate'], ARRAY['explorer'], ARRAY['Identify common logical fallacies','Construct arguments free of fallacies'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Fallacy-Free Debate', 'critical_thinking', 'team_debate', '{"question":"Debate: Should phones be allowed in this outdoor space? Person A argues YES. Person B argues NO. BUT: each debater must identify ONE logical fallacy in the other''s argument. The judge scores based on: (1) strength of evidence, (2) correct fallacy identification, (3) avoiding fallacies in your own argument.","hints":["Listen carefully for: attacking the person not the idea (ad hominem)","Watch for: it is always been this way (appeal to tradition)","Catch: if we allow X then Y will happen (slippery slope without evidence)","Avoid your own fallacies — stick to observable evidence from this location"]}', 9, 12, 4, true, 'independent', 'any', 9, ARRAY['fallacies','debate','logic','argument'], ARRAY['explorer'], ARRAY['Identify fallacies in real-time debate'], 7, u_owner);

  -- CT-8: Question Quality (3-5, easy, audio_response)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Asking Great Questions', '{"text":"Good questions are the superpower of smart thinkers. Closed questions have yes/no answers: Is the sky blue? Open questions invite exploration: Why is the sky blue? The best questions start with WHY, HOW, or WHAT IF. Scientists ask questions they can test. Philosophers ask questions that make you think. Both kinds matter.","items":["Closed question: yes/no answer (Is it raining?)","Open question: requires thinking (Why does it rain more in spring?)","Testable question: you can find the answer (How many birds are here?)","Wonderment question: makes you think deeply (What if trees could talk?)"]}', 'critical_thinking', 3, 5, true, 'independent', 'any', 3, ARRAY['questions','inquiry','thinking','curiosity'], ARRAY['young_scientist','explorer'], ARRAY['Distinguish between closed and open questions','Practice asking testable and wonderment questions'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Question Generator', 'critical_thinking', 'audio_response', '{"question":"Look around for 30 seconds. Then record yourself asking 4 questions about what you see: (1) One CLOSED question (yes/no answer), (2) One OPEN question (requires thinking), (3) One TESTABLE question (you could find the answer), (4) One WONDERMENT question (makes you go hmmmm). Which question is hardest to answer?","hints":["Closed: Is that tree taller than the building?","Open: Why did someone decide to put a bench here?","Testable: How many steps from here to that tree?","Wonderment: What would this place look like with no humans?"]}', 3, 5, 1, true, 'independent', 'any', 3, ARRAY['questions','inquiry','speaking'], ARRAY['young_scientist'], ARRAY['Practice generating different types of questions'], 5, u_owner);

  -- CT-9: Problem Solving Steps (K-2, easy, sorting_ordering)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Steps to Solve a Problem', '{"text":"When you have a problem, follow these steps: (1) STOP and understand the problem. (2) THINK of at least 2 possible solutions. (3) PICK the best solution. (4) TRY it. (5) CHECK — did it work? If not, try another solution. Good problem solvers do not give up after one try!","items":["Stop: what exactly is the problem?","Think: what are my options? (at least 2)","Pick: which option seems best?","Try: do it!","Check: did it work? If not, try again"]}', 'critical_thinking', 0, 2, true, 'independent', 'any', 2, ARRAY['problem_solving','steps','process','thinking'], ARRAY['young_scientist','explorer'], ARRAY['Follow a 5-step problem-solving process'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Problem Solving Steps', 'critical_thinking', 'sorting_ordering', '{"question":"A friend dropped their water bottle and it rolled under a bench that is too low to crawl under. Put these problem-solving steps in the RIGHT order:","items":["STOP: Understand the problem (bottle is stuck under bench)","THINK: Come up with ideas (use a stick? tilt the bench? ask for help?)","PICK: Choose the best idea","TRY: Do your plan","CHECK: Did you get the bottle back?"],"hints":["First you need to understand what happened","Then think of options BEFORE acting","Pick the safest and easiest option","Always check if your solution worked"]}', 0, 2, 1, true, 'independent', 'any', 2, ARRAY['problem_solving','ordering','process'], ARRAY['young_scientist'], ARRAY['Order problem-solving steps correctly'], 5, u_owner);

  -- CT-10: Ethical Reasoning (6-8, hard, creative_writing)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (p, 'Thinking Through Right and Wrong', '{"text":"Ethical reasoning means thinking carefully about right and wrong. Not every decision has a clear right answer. Three ethical frameworks: (1) Consequences: which action produces the best outcome for the most people? (2) Rules: are there rules or principles that apply regardless of outcome? (3) Character: what would a person of good character do? Using all three frameworks helps you make thoughtful decisions.","items":["Consequentialism: focus on outcomes — greatest good for greatest number","Deontology: focus on rules — some actions are right/wrong regardless","Virtue ethics: focus on character — what would a good person do?","Most real dilemmas have valid arguments on multiple sides"]}', 'critical_thinking', 6, 8, true, 'independent', 'any', 8, ARRAY['ethics','reasoning','dilemma','values','philosophy'], ARRAY['explorer','urban_explorer'], ARRAY['Apply three ethical frameworks to a real dilemma'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Ethical Dilemma', 'critical_thinking', 'creative_writing', '{"question":"You find a $20 bill on the ground in this location with no one around. Write your ethical analysis using all 3 frameworks: (1) CONSEQUENCES: what happens if you keep it vs turn it in? Who benefits, who is harmed? (2) RULES: is there a rule about found money? What does the law say? (3) CHARACTER: what would a person you admire do? What is your final decision and why?","hints":["Consequences: consider the person who lost it — what if they really needed it?","Rules: many places have lost-and-found policies","Character: think of someone you respect — what would they do?","There is no single right answer — the quality of your REASONING matters"]}', 6, 8, 4, true, 'independent', 'any', 8, ARRAY['ethics','dilemma','reasoning','writing'], ARRAY['explorer'], ARRAY['Apply ethical frameworks to a personal dilemma'], 8, u_owner);


  -- ═══════════════════════════════════════════════════════════
  -- READING & WRITING (10 pairs) and HISTORY & COMMUNITY (10 pairs)
  -- will be added in a follow-up migration to keep this file manageable
  -- ═══════════════════════════════════════════════════════════

END $$;
