-- ══════════════════════════════════════════════════════════════
-- Migration 026: Standards-driven content generation
--
-- Creates primer+task pairs for each of the 25 education
-- standards that currently have 0 aligned tasks.
-- Each pair is aligned to its target standard via the
-- alignment tables.
-- ══════════════════════════════════════════════════════════════

DO $$
DECLARE
  u_owner UUID;
  p UUID; t UUID; std_id UUID;
BEGIN
  SELECT id INTO u_owner FROM public.users WHERE email = 'mark.keith@gmail.com' LIMIT 1;
  IF u_owner IS NULL THEN
    SELECT id INTO u_owner FROM public.users WHERE role = 'admin' LIMIT 1;
  END IF;


  -- ═══════════════════════════════════════════════════════════
  -- NGSS GAPS (10 standards)
  -- ═══════════════════════════════════════════════════════════

  -- K-ESS2-1: Weather patterns (K, data_collection)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Watching the Weather', '{"text":"Weather is what the sky and air are doing right now. Is it sunny or cloudy? Warm or cold? Windy or still? Scientists watch weather every day and write down what they see. After many days, they can see patterns — like how spring is often rainy and summer is often hot.","items":["Sunny: the sun is shining, few clouds","Cloudy: clouds cover most of the sky","Rainy: water falls from clouds","Windy: you can feel air moving"]}', 'science_nature', 0, 2, true, 'independent', 'any', 2, ARRAY['weather','patterns','observation','K-ESS2-1'], ARRAY['young_scientist'], ARRAY['Observe and describe daily weather conditions','Identify weather patterns over time'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Weather Watch Report', 'science_nature', 'data_collection', '{"question":"Look at the sky and feel the air right now. Record: (1) Is it sunny, partly cloudy, or cloudy? (2) Is it warm, cool, or cold? (3) Is it windy, breezy, or calm? (4) Can you see any rain or snow? Draw a simple picture of today''s weather.","hints":["Look UP at the sky first","Hold your hand out — can you feel wind?","Is the sun making shadows? That means sunny!","Every kind of weather is interesting to a scientist!"]}', 0, 2, 1, true, 'independent', 'any', 2, ARRAY['weather','observation','patterns','K-ESS2-1'], ARRAY['young_scientist'], ARRAY['Record weather observations using multiple senses'], 5, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = 'K-ESS2-1';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- 2-ESS2-3: Where water is found (2, photo_observation)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Water Is Everywhere', '{"text":"Water is found all over Earth — in oceans, rivers, lakes, puddles, clouds, and even underground! Water can be a liquid (in a glass), a solid (ice), or a gas (steam). Most of Earth''s water is in the oceans. Fresh water that we drink comes from rivers, lakes, and underground wells.","items":["Oceans: most of Earth''s water (salty)","Rivers and lakes: fresh water we can see","Underground: water hidden in soil and rocks","Clouds: tiny water droplets floating in air"]}', 'science_nature', 0, 2, true, 'independent', 'any', 2, ARRAY['water','states_of_matter','earth_science','2-ESS2-3'], ARRAY['young_scientist','nature_detective'], ARRAY['Identify places where water is found','Recognize that water can be solid or liquid'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Water Finder', 'science_nature', 'photo_observation', '{"question":"Find 3 different places where you can see water right now (or signs that water has been here). Take a photo of each. Water can be: a puddle, dew on grass, a drinking fountain, a wet spot, a drain, condensation on a window, or even clouds! Is the water liquid, solid (ice), or gas (steam)?","hints":["Look on the ground for puddles or wet spots","Check leaves — do they have water drops?","Is there a fountain, hose, or sprinkler nearby?","Clouds are made of tiny water droplets!"]}', 0, 2, 1, true, 'independent', 'any', 2, ARRAY['water','observation','states_of_matter','2-ESS2-3'], ARRAY['young_scientist'], ARRAY['Find and photograph water in different locations'], 7, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = '2-ESS2-3';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- 3-LS4-3: Habitat survival (3, multiple_choice)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Surviving in a Habitat', '{"text":"Not every organism can survive in every habitat. A cactus thrives in the desert but would rot in a swamp. A fish needs water but would die on land. Organisms survive when their traits match what the habitat provides: the right temperature, food, water, and shelter. When the habitat changes, organisms that cannot adapt may disappear.","items":["Organisms need: food, water, shelter, space","Traits must match the habitat","Desert organisms: thick skin, store water, active at night","Wetland organisms: webbed feet, waterproof feathers, gills"]}', 'science_nature', 3, 5, true, 'independent', 'any', 4, ARRAY['habitats','survival','adaptation','traits','3-LS4-3'], ARRAY['nature_detective'], ARRAY['Explain why some organisms survive in a habitat and others cannot'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Habitat Match Challenge', 'science_nature', 'multiple_choice', '{"question":"Look at your current location. Which of these organisms would survive BEST here?","options":["A polar bear (needs freezing temperatures and ice)","A cactus (needs hot, dry conditions with sandy soil)","A local bird you can actually see or hear right now","A deep-sea fish (needs ocean pressure and darkness)"],"correct_answer":"A local bird you can actually see or hear right now","hints":["Think about the temperature right now — too hot or cold for some","What food and water sources are available here?","Which option is actually adapted to YOUR local environment?","The organism already living here is the best answer!"]}', 3, 5, 2, true, 'independent', 'any', 4, ARRAY['habitats','survival','adaptation','3-LS4-3'], ARRAY['nature_detective'], ARRAY['Identify which organisms suit the current habitat'], 3, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = '3-LS4-3';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- 4-LS1-1: Plant/animal structures (4, sketch_draw)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Structures for Survival', '{"text":"Every plant and animal has structures (body parts) that help it survive. Thorns protect plants from being eaten. Deep roots reach underground water. Wings let birds escape predators. Thick fur keeps mammals warm. These structures developed over millions of years through natural selection — organisms with helpful structures survived and passed them to their offspring.","items":["External structures: thorns, fur, claws, bark, petals","Internal structures: roots, veins, bones, lungs","Protective structures: shells, thorns, camouflage colors","Reproductive structures: flowers, seeds, eggs"]}', 'science_nature', 3, 5, true, 'independent', 'any', 5, ARRAY['structures','survival','plants','animals','4-LS1-1'], ARRAY['nature_detective','field_scientist'], ARRAY['Identify structures that help organisms survive','Explain how structures support specific survival functions'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Survival Structure Sketch', 'science_nature', 'sketch_draw', '{"question":"Find one plant OR one animal near you. Sketch it and label at least 4 structures (body parts) that help it survive. For each structure, write one sentence explaining HOW it helps. Example: Bark → protects the trunk from insects and weather.","hints":["Plants: roots, stems, leaves, bark, thorns, flowers, seeds","Animals: legs, wings, eyes, fur, claws, beak, antennae","Think about protection, getting food, getting water, reproducing","Even a simple weed has survival structures — look closely!"]}', 3, 5, 2, true, 'independent', 'any', 5, ARRAY['structures','survival','observation','sketch','4-LS1-1'], ARRAY['nature_detective'], ARRAY['Identify and illustrate survival structures on a real organism'], 8, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = '4-LS1-1';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- 4-ESS2-2: Earth's features from maps (4, short_text)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Reading Earth''s Surface', '{"text":"Maps reveal patterns in Earth''s features. Mountains line up in ranges. Rivers follow valleys. Coastlines curve where waves erode rock. Volcanoes cluster along plate boundaries. By studying maps, scientists can predict where earthquakes might happen, where floods are likely, and where to find certain minerals. The patterns tell the story of how Earth''s surface formed.","items":["Mountain ranges: form along plate boundaries","River patterns: follow the lowest ground (gravity)","Coastline shapes: carved by waves and currents","Flat plains: often ancient sea floors or flood deposits"]}', 'science_nature', 3, 5, true, 'independent', 'any', 5, ARRAY['earth_features','maps','patterns','geology','4-ESS2-2'], ARRAY['explorer','field_scientist'], ARRAY['Identify patterns in Earth''s surface features','Use observations to describe landscape formation'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Landscape Pattern Finder', 'science_nature', 'short_text', '{"question":"Look at the landscape around you. Describe 2 patterns you can see in Earth''s surface: Are there hills? Flat areas? A valley? Water features? Which direction do slopes point? Write 3 sentences explaining what forces (water, wind, ice, humans) might have shaped this landscape over time.","correct_answer":null,"hints":["Flat areas were often shaped by water (ancient lakes or rivers)","Hills and valleys show where erosion carved the land","Look for evidence of human changes: cuts, fills, leveling","Mountains in the distance show tectonic forces at work"]}', 3, 5, 2, true, 'independent', 'any', 5, ARRAY['earth_features','patterns','landscape','4-ESS2-2'], ARRAY['explorer'], ARRAY['Describe and explain landscape patterns'], 5, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = '4-ESS2-2';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- 5-PS1-1: Matter/particles (5, creative_writing)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'The Invisible World of Particles', '{"text":"Everything around you — rocks, air, water, your own body — is made of particles too small to see. These particles are constantly moving. In solids, particles vibrate in place (that is why rocks feel hard). In liquids, particles slide past each other (that is why water flows). In gases, particles fly freely in all directions (that is why air fills every space). Temperature is really a measure of how fast particles are moving.","items":["Solid: particles packed tight, vibrate in place","Liquid: particles close but slide freely","Gas: particles spread out, move fast in all directions","Temperature = particle speed"]}', 'science_nature', 4, 6, true, 'independent', 'any', 6, ARRAY['matter','particles','states_of_matter','physics','5-PS1-1'], ARRAY['field_scientist'], ARRAY['Describe matter as made of particles too small to see','Explain differences between solid, liquid, and gas at the particle level'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Particle Story', 'science_nature', 'creative_writing', '{"question":"Pick one object you can see (a rock, a puddle, the air, a leaf). Write a short story (5 sentences) from the perspective of ONE particle inside that object. Describe: What are you doing right now? (vibrating, flowing, flying?) Who are your neighbors? What happens when the temperature changes? What would happen if you were heated up or cooled down?","hints":["Rock particles vibrate but stay in place — like shaking in a crowd","Water particles slide past neighbors — like people in a swimming pool","Air particles zoom around freely — like balls bouncing in a room","Heating = moving faster; cooling = slowing down"]}', 4, 6, 3, true, 'independent', 'any', 6, ARRAY['matter','particles','perspective_writing','5-PS1-1'], ARRAY['field_scientist'], ARRAY['Apply particle model through creative perspective-taking'], 8, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = '5-PS1-1';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- 5-LS2-1: Matter movement in ecosystems (5, sketch_draw)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Matter Cycles Through Ecosystems', '{"text":"Matter does not disappear — it cycles. Plants take in CO2 and water to build their bodies (photosynthesis). Animals eat plants and use that matter for energy and growth. When organisms die, decomposers break them down, releasing nutrients back into the soil. Those nutrients feed new plants, and the cycle continues. Nothing is wasted in nature.","items":["Plants: absorb CO2 + water → build body + release O2","Animals: eat plants → use matter for growth + energy","Decomposers: break down dead organisms → nutrients return to soil","Cycle: soil nutrients → plants → animals → decomposers → soil"]}', 'science_nature', 4, 6, true, 'independent', 'any', 6, ARRAY['matter_cycling','ecosystem','decomposition','photosynthesis','5-LS2-1'], ARRAY['field_scientist','nature_detective'], ARRAY['Describe how matter moves among plants, animals, and decomposers'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Matter Cycle Diagram', 'science_nature', 'sketch_draw', '{"question":"Find evidence of the matter cycle at your location. Draw a diagram showing how matter moves from soil → plant → animal → decomposer → back to soil. Use REAL organisms you can see or find evidence of. Draw arrows showing the direction matter flows. Label at least one example of each: producer, consumer, decomposer.","hints":["Plants pull matter from soil through roots (producer)","An insect eating a leaf is a consumer","Mushrooms, mold, or rotting leaves show decomposition","Dead leaves on the ground are matter returning to the soil"]}', 4, 6, 3, true, 'independent', 'any', 6, ARRAY['matter_cycling','diagram','ecosystem','5-LS2-1'], ARRAY['field_scientist'], ARRAY['Diagram the cycling of matter through a real ecosystem'], 8, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = '5-LS2-1';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- 5-ESS2-1: Geosphere/biosphere interactions (5, data_collection)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Earth''s Systems Work Together', '{"text":"Earth has four interconnected systems: the geosphere (rocks, soil, land), hydrosphere (water), atmosphere (air), and biosphere (living things). They constantly interact. Rain (atmosphere) erodes rock (geosphere), carrying sediment to rivers (hydrosphere), which creates habitat for fish (biosphere). A volcanic eruption (geosphere) puts ash into the atmosphere, which affects climate and living things.","items":["Geosphere: rocks, soil, mountains, continents","Hydrosphere: oceans, rivers, lakes, groundwater, ice","Atmosphere: air, weather, climate","Biosphere: all living organisms"]}', 'science_nature', 4, 6, true, 'independent', 'any', 6, ARRAY['earth_systems','geosphere','biosphere','hydrosphere','atmosphere','5-ESS2-1'], ARRAY['field_scientist'], ARRAY['Describe how Earth''s four systems interact'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Earth Systems Interaction Hunt', 'science_nature', 'data_collection', '{"question":"Find ONE example of each of Earth''s four systems at your location: (1) Geosphere — a rock, soil, or landform, (2) Hydrosphere — water in any form, (3) Atmosphere — evidence of weather or air, (4) Biosphere — a living organism. Then describe ONE interaction between two of them. Example: rain (atmosphere) eroded this rock (geosphere).","hints":["Geosphere: look at the ground — soil, rocks, pavement (made from rock)","Hydrosphere: puddles, dew, wet soil, clouds, a drinking fountain","Atmosphere: feel the wind, notice temperature, look at clouds","Biosphere: any plant, animal, fungus, or evidence of one"]}', 4, 6, 3, true, 'independent', 'any', 6, ARRAY['earth_systems','interaction','observation','5-ESS2-1'], ARRAY['field_scientist'], ARRAY['Identify and connect Earth''s four systems at a real location'], 8, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = '5-ESS2-1';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- MS-ESS2-2: Geoscience processes (6-8, short_text)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Forces That Shape the Surface', '{"text":"Earth''s surface is constantly being reshaped by two types of forces. Constructive forces build up the surface: volcanic eruptions create new land, tectonic plates push mountains upward, and sediment deposits build deltas. Destructive forces wear it down: weathering breaks rock apart, erosion carries sediment away, and landslides move soil downhill. The landscape you see is the result of millions of years of these competing forces.","items":["Constructive: volcanism, mountain building, deposition","Destructive: weathering, erosion, landslides","Chemical weathering: water dissolves rock over time","Physical weathering: freeze-thaw cycles crack rock"]}', 'science_nature', 6, 8, true, 'independent', 'any', 6, ARRAY['geoscience','erosion','weathering','tectonics','MS-ESS2-2'], ARRAY['field_scientist'], ARRAY['Explain how constructive and destructive forces shape Earth''s surface'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Surface Change Evidence', 'science_nature', 'short_text', '{"question":"Find evidence of EITHER a constructive force (building up) OR a destructive force (wearing down) at your location. Describe: (1) What do you see? (2) Is it constructive or destructive? (3) What force caused it? (4) How long do you think this process took? Write 4-5 sentences with specific evidence.","correct_answer":null,"hints":["Erosion: worn paths, exposed roots, gullies, smooth rocks","Deposition: sediment piles, sand bars, alluvial fans","Weathering: cracked rocks, potholes, stained stone","Human-made changes count too: cuts, fills, retaining walls"]}', 6, 8, 3, true, 'independent', 'any', 6, ARRAY['geoscience','erosion','evidence','MS-ESS2-2'], ARRAY['field_scientist'], ARRAY['Identify and explain evidence of geoscience processes'], 5, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = 'MS-ESS2-2';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- MS-ESS3-3: Monitoring human impact (6-8, data_collection)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Measuring Our Footprint', '{"text":"Humans impact the environment in measurable ways: air and water pollution, habitat destruction, soil erosion from construction, light pollution, noise pollution, and waste accumulation. Scientists monitor these impacts by collecting data over time. The first step to solving environmental problems is measuring them accurately. If you can''t measure it, you can''t manage it.","items":["Air quality: particulates, CO2, ozone levels","Water quality: pH, dissolved oxygen, turbidity","Habitat: species counts before and after development","Waste: volume of litter per area, recycling rates"]}', 'science_nature', 6, 8, true, 'independent', 'any', 7, ARRAY['human_impact','environment','monitoring','sustainability','MS-ESS3-3'], ARRAY['field_scientist','urban_explorer'], ARRAY['Design a method for monitoring human environmental impact'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Human Impact Audit', 'science_nature', 'data_collection', '{"question":"Conduct a human impact audit of your immediate area (50m radius). Record: (1) Litter count: how many pieces visible? (2) Impervious surface: estimate % covered by concrete/asphalt vs natural ground, (3) Noise level 1-5, (4) Light pollution potential 1-5 (how many artificial lights visible?), (5) Evidence of habitat modification (paved over, landscaped, natural?). Score the area 1-10 for environmental health. What ONE change would improve it most?","hints":["Count litter carefully — small pieces count","Impervious surfaces prevent water absorption","More lights = more light pollution for nocturnal animals","Compare: what was this land before humans modified it?"]}', 6, 8, 3, true, 'independent', 'any', 7, ARRAY['human_impact','audit','data','environment','MS-ESS3-3'], ARRAY['field_scientist'], ARRAY['Collect data to assess human environmental impact'], 10, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = 'MS-ESS3-3';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;


  -- ═══════════════════════════════════════════════════════════
  -- CCSS-M GAPS (4 standards)
  -- ═══════════════════════════════════════════════════════════

  -- 2.G.A.1: Shape attributes (2, sorting_ordering)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Shapes Have Special Features', '{"text":"Every shape has attributes — special features that make it what it is. A triangle has 3 sides and 3 corners (angles). A rectangle has 4 sides and 4 right angles (square corners). A circle has no sides and no corners — it curves all the way around. When you know a shape''s attributes, you can find it anywhere!","items":["Triangle: 3 sides, 3 angles","Rectangle: 4 sides, 4 right angles","Square: 4 equal sides, 4 right angles","Circle: 0 sides, 0 angles, curves all around"]}', 'math_real_world', 0, 2, true, 'independent', 'any', 2, ARRAY['shapes','geometry','attributes','2.G.A.1'], ARRAY['young_scientist','explorer'], ARRAY['Identify shapes by their attributes (sides and angles)'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Shape Attribute Sort', 'math_real_world', 'sorting_ordering', '{"question":"Find 4 different shapes in the world around you (a window, a sign, a wheel, a roof). For each shape, count the number of sides and the number of corners (angles). Sort your shapes from fewest sides to most sides.","items":["Circle (0 sides, 0 corners)","Triangle (3 sides, 3 corners)","Rectangle/Square (4 sides, 4 corners)","Pentagon or other (5+ sides)"],"hints":["A circle has 0 sides and 0 corners","Count each straight edge as one side","Each point where sides meet is a corner (angle)","A stop sign is an octagon — 8 sides!"]}', 0, 2, 1, true, 'independent', 'any', 2, ARRAY['shapes','geometry','sorting','attributes','2.G.A.1'], ARRAY['young_scientist'], ARRAY['Sort real-world shapes by number of sides and angles'], 5, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = '2.G.A.1';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- 4.G.A.1: Lines, angles, shape classification (4, sketch_draw)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Lines and Angles Everywhere', '{"text":"Lines and angles are the building blocks of every structure. Parallel lines never meet (railroad tracks). Perpendicular lines meet at right angles (a plus sign). Acute angles are less than 90° (a partly open book). Obtuse angles are more than 90° (a reclining chair). Right angles are exactly 90° (a corner of a book). Architects use these to create stable, beautiful buildings.","items":["Parallel: lines that never meet (= symbol)","Perpendicular: lines meeting at 90° (+ symbol)","Acute angle: less than 90° (sharp)","Right angle: exactly 90° (square corner)","Obtuse angle: more than 90° (wide)"]}', 'math_real_world', 3, 5, true, 'independent', 'any', 5, ARRAY['lines','angles','geometry','classification','4.G.A.1'], ARRAY['explorer','urban_explorer'], ARRAY['Identify parallel, perpendicular lines and classify angles'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Angle and Line Spotter', 'math_real_world', 'sketch_draw', '{"question":"In the structures around you, find and sketch: (1) One pair of PARALLEL lines, (2) One pair of PERPENDICULAR lines, (3) One ACUTE angle, (4) One RIGHT angle, (5) One OBTUSE angle. Label each one and estimate the angle in degrees.","hints":["Parallel: look at fence rails, window frames, road lanes","Perpendicular: where a wall meets the floor, a T-intersection","Acute: rooflines, partly open doors, letter V","Obtuse: reclining benches, wide road forks, open scissors"]}', 3, 5, 2, true, 'independent', 'any', 5, ARRAY['lines','angles','sketch','geometry','4.G.A.1'], ARRAY['explorer'], ARRAY['Find and classify lines and angles in real structures'], 8, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = '4.G.A.1';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- HSN.Q.A.1: Units in problem solving (9-12, numeric_entry)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Units Tell the Story', '{"text":"Units are not just labels — they are essential to understanding a problem. Speed in km/h vs m/s gives completely different numbers for the same motion. Dimensional analysis (tracking units through calculations) catches errors before they matter. NASA lost a $125 million Mars orbiter because one team used metric units and another used imperial. Always track your units.","items":["Every measurement has a number AND a unit","Units must be consistent throughout a calculation","Dimensional analysis: multiply by conversion factors (1 = km/1000m)","Wrong units → wrong answer, even if the math is perfect"]}', 'math_real_world', 9, 12, true, 'independent', 'any', 8, ARRAY['units','dimensional_analysis','measurement','HSN.Q.A.1'], ARRAY['field_scientist'], ARRAY['Use units to guide problem solving and check answers'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Unit Conversion Challenge', 'math_real_world', 'numeric_entry', '{"question":"Measure the length of a nearby object in two different units: (1) your hand spans, (2) your foot lengths. Convert both to centimeters using: 1 hand span ≈ 20 cm, 1 foot length ≈ 27 cm. Do both conversions give approximately the same answer? Calculate the percentage difference between them. Which unit gave a more precise measurement?","unit":"cm (average of both methods)","hints":["Hand span: spread your hand from thumb to pinky","Measure the same object with both methods","Convert: count × conversion factor = cm","% difference = |method1 - method2| / average × 100"]}', 9, 12, 4, true, 'independent', 'any', 8, ARRAY['units','conversion','measurement','precision','HSN.Q.A.1'], ARRAY['field_scientist'], ARRAY['Apply unit conversion and assess measurement precision'], 5, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = 'HSN.Q.A.1';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- HSS.ID.A.1: Data representation (9-12, data_collection)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Visualizing Data', '{"text":"Raw numbers are hard to understand. Data visualization transforms numbers into pictures that reveal patterns. Dot plots show individual values. Histograms show the distribution (shape) of data. Box plots show the center, spread, and outliers. Choosing the right visualization depends on your data and what question you are trying to answer.","items":["Dot plot: each dot = one value, shows individual data points","Histogram: bars show frequency of ranges (bins)","Box plot: shows median, quartiles, min, max, outliers","The shape of the distribution tells a story"]}', 'math_real_world', 9, 12, true, 'independent', 'any', 8, ARRAY['statistics','data_visualization','histogram','box_plot','HSS.ID.A.1'], ARRAY['field_scientist'], ARRAY['Choose appropriate data visualizations','Create visual representations of collected data'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Field Data Visualization', 'math_real_world', 'data_collection', '{"question":"Collect a dataset of at least 15 measurements from your environment. Choose ONE: (A) Leaf lengths from one tree, (B) Distances between fence posts/light poles, (C) Heights of people walking by, or (D) Time between passing vehicles. Then create TWO visualizations: a dot plot (every value as a dot on a number line) and describe what a histogram would look like (which range has the most values?). What is the shape: symmetric, left-skewed, or right-skewed?","hints":["Dot plot: draw a number line, place one dot per value","Histogram: group values into ranges (bins) of equal width","Symmetric: both sides look similar (bell shape)","Skewed: one tail is longer than the other"]}', 9, 12, 4, true, 'independent', 'any', 8, ARRAY['statistics','visualization','data_collection','HSS.ID.A.1'], ARRAY['field_scientist'], ARRAY['Collect field data and create appropriate visualizations'], 10, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = 'HSS.ID.A.1';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;


  -- ═══════════════════════════════════════════════════════════
  -- C3 GAPS (6 standards)
  -- ═══════════════════════════════════════════════════════════

  -- D2.Geo.4.3-5: Culture and environment (3-5, short_text)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'How Culture Shapes Place', '{"text":"Culture influences how people use and change their environment. Farmers clear forests for fields. City builders pave land for roads. Different cultures build different types of homes, gardens, and public spaces. Even the names of places reflect the culture of the people who named them. When you look at any landscape, you are seeing the result of cultural choices.","items":["Agriculture: clears land, creates irrigation, changes ecosystems","Architecture: reflects climate, materials, and cultural values","Land use: parks, roads, farms — all cultural decisions","Place names: reveal who was here first and what they valued"]}', 'geography_maps', 3, 5, true, 'independent', 'any', 5, ARRAY['culture','environment','land_use','human_geography','D2.Geo.4.3-5'], ARRAY['urban_explorer','explorer'], ARRAY['Explain how culture influences environmental modification'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Cultural Landscape Reading', 'geography_maps', 'short_text', '{"question":"Look around your location. Find 3 examples of how PEOPLE (culture) have changed the ENVIRONMENT. For each example, describe: (1) What was changed, (2) Why you think it was changed, (3) What might have been here before. Examples: a sidewalk (changed natural ground for walking), a garden (changed wild land for beauty).","correct_answer":null,"hints":["Buildings replaced natural land — what grew here before?","Roads and paths show how people want to move through space","Gardens and landscaping show cultural ideas about beauty","Signs and markers show what the community values"]}', 3, 5, 2, true, 'independent', 'any', 5, ARRAY['culture','environment','observation','D2.Geo.4.3-5'], ARRAY['urban_explorer'], ARRAY['Identify cultural modifications to the environment'], 5, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = 'D2.Geo.4.3-5';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- D2.His.1.3-5: Chronological sequences (3-5, sorting_ordering)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Putting History in Order', '{"text":"History is the study of the past in the order it happened — chronological order. A timeline shows events from earliest to latest. Clues in buildings, streets, and landscapes tell you what came first. Older buildings have different styles than newer ones. Roads that curve often follow old paths; straight roads were planned later. Reading these clues is like being a time detective.","items":["Chronological: arranged by time (earliest first)","Timeline: a line with dates and events in order","Relative dating: this came BEFORE that (even without exact dates)","Clues: building materials, styles, and condition show age"]}', 'history_community', 3, 5, true, 'independent', 'any', 4, ARRAY['chronology','timeline','history','sequence','D2.His.1.3-5'], ARRAY['explorer','urban_explorer'], ARRAY['Create chronological sequences from environmental evidence'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Timeline Detective', 'history_community', 'sorting_ordering', '{"question":"Find 4 things at your location that were created at different times. Sort them from OLDEST to NEWEST. For each, explain your evidence for its age. Examples: an old tree (thick trunk), a new building (modern materials), a worn path (years of foot traffic), a fresh sign.","items":["Very old (50+ years): weathered stone, mature trees, old-style architecture","Old (20-50 years): established plants, worn concrete, faded paint","Recent (5-20 years): modern materials, good condition","New (less than 5 years): fresh paint, new plantings, clean materials"],"hints":["Older trees have thicker trunks and more branches","Weathered stone and faded paint suggest age","Modern materials (glass, steel, plastic) suggest newer construction","Nature reclaims human structures over time — more plants = older"]}', 3, 5, 2, true, 'independent', 'any', 4, ARRAY['chronology','sorting','history','evidence','D2.His.1.3-5'], ARRAY['urban_explorer'], ARRAY['Sort features by estimated age using evidence'], 7, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = 'D2.His.1.3-5';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- D2.His.3.3-5: Historical change (3-5, creative_writing)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'People Who Changed Things', '{"text":"History is shaped by individuals and groups who saw a problem and worked to fix it. Community leaders built schools and parks. Activists fought for equal rights. Engineers designed roads and bridges. Scientists discovered how to clean water. Every place you visit was shaped by people who decided to make a change. Asking WHO changed this and WHY is the heart of historical thinking.","items":["Who built this? Someone made a decision","Why was it built? A need or problem was identified","What changed because of it? Communities were affected","What might change next? History is still being made"]}', 'history_community', 3, 5, true, 'independent', 'any', 4, ARRAY['historical_change','individuals','community','D2.His.3.3-5'], ARRAY['explorer','urban_explorer'], ARRAY['Generate questions about people who shaped historical change'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Historical Change Interview', 'history_community', 'creative_writing', '{"question":"Choose one feature of your location (a building, road, park, statue, or sign). Write 5 interview questions you would ask the person who created it. Include: Why did you build this? What was here before? What problem did it solve? How has it changed the community? What do you hope it looks like in 50 years? Then write what you THINK their answers might be.","hints":["Think about the PURPOSE of what you chose — why does it exist?","Every structure replaced something that was here before","Consider the community impact — who benefits?","Imagine the future — will this still be here in 50 years?"]}', 3, 5, 2, true, 'independent', 'any', 4, ARRAY['historical_change','questions','interview','D2.His.3.3-5'], ARRAY['explorer'], ARRAY['Generate questions about individuals who shaped community change'], 8, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = 'D2.His.3.3-5';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- D2.His.1.6-8: Historical connections (6-8, team_debate)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Connecting Past and Present', '{"text":"Historical events do not happen in isolation — they connect to broader patterns. The neighborhood you stand in was shaped by transportation technology (horse → car → train). Its architecture reflects economic booms and busts. Its demographics reflect immigration patterns and housing policies. To understand any place, you must trace its connections to national and global history.","items":["Transportation: shaped settlement patterns","Economy: booms build, busts leave vacancies","Demographics: migration patterns shape communities","Policy: zoning laws, redlining, and public investment"]}', 'history_community', 6, 8, true, 'independent', 'any', 7, ARRAY['historical_connections','context','community','D2.His.1.6-8'], ARRAY['urban_explorer'], ARRAY['Analyze connections between local events and broader historical contexts'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Past and Present Debate', 'history_community', 'team_debate', '{"question":"Look at this area and debate: Is this place BETTER or WORSE than it was 50 years ago? Person A argues BETTER (more services, better infrastructure, progress). Person B argues WORSE (lost character, environmental impact, displacement). Person C judges based on the strength of historical evidence visible right now. Each side gets 2 minutes.","hints":["BETTER evidence: modern buildings, clean water, accessibility, technology","WORSE evidence: loss of green space, generic architecture, traffic, pollution","Consider: better for WHOM? Progress helps some and hurts others","Use visible evidence from this specific location, not general opinions"]}', 6, 8, 3, true, 'independent', 'any', 7, ARRAY['history','debate','change','D2.His.1.6-8'], ARRAY['urban_explorer'], ARRAY['Debate historical change using visible evidence'], 7, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = 'D2.His.1.6-8';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- D2.Civ.7.3-5: Civic participation (3-5, audio_response)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Being a Good Community Member', '{"text":"Civic virtue means caring about your community and taking action to make it better. It includes: respecting shared spaces, helping others, following rules that protect everyone, speaking up when something is unfair, and participating in community decisions. Even small actions matter — picking up litter, being kind, and listening to different viewpoints are all civic virtues.","items":["Respect: treating shared spaces and other people well","Responsibility: doing your part for the community","Participation: voting, attending meetings, volunteering","Fairness: standing up for what is right, even when hard"]}', 'history_community', 3, 5, true, 'independent', 'any', 3, ARRAY['civic','community','participation','virtue','D2.Civ.7.3-5'], ARRAY['explorer','urban_explorer'], ARRAY['Apply civic virtues in community settings'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Community Improvement Pitch', 'history_community', 'audio_response', '{"question":"Record a 60-second speech to your community about ONE improvement you would make to this location. Include: (1) What is the problem you see? (2) What is your solution? (3) Who would it help? (4) How could the community work together to make it happen? Use your best public speaking voice!","hints":["Start with: I would like to propose an improvement to our community...","Be specific about the problem — describe what you see","Be specific about the solution — what exactly would change?","End with a call to action: Together we can..."]}', 3, 5, 1, true, 'independent', 'any', 3, ARRAY['civic','community','speaking','proposal','D2.Civ.7.3-5'], ARRAY['explorer'], ARRAY['Propose community improvements using civic participation skills'], 5, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = 'D2.Civ.7.3-5';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- D2.His.14.9-12: Multiple causes/effects (9-12, short_text)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Causes and Effects Are Complex', '{"text":"Historical events rarely have a single cause or a single effect. The development of any neighborhood involved economic forces, political decisions, technological changes, demographic shifts, and cultural values — all interacting simultaneously. Historians must trace MULTIPLE causes (what led to this?) and MULTIPLE effects (what resulted from it?) to understand change. Simple explanations are almost always incomplete.","items":["Proximate cause: the immediate trigger","Distal cause: the deeper, underlying conditions","Intended effects: what people hoped would happen","Unintended effects: consequences nobody predicted"]}', 'history_community', 9, 12, true, 'independent', 'any', 9, ARRAY['causation','complexity','historical_analysis','D2.His.14.9-12'], ARRAY['urban_explorer'], ARRAY['Analyze multiple and complex causes and effects of historical events'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Causal Complexity Analysis', 'history_community', 'short_text', '{"question":"Choose one significant feature at your location (a major road, a large building, a park, a monument). Analyze it using the multiple-causation framework: (1) Name 2 proximate causes (immediate decisions that led to it), (2) Name 2 distal causes (deeper historical/economic/cultural forces), (3) Name 1 intended effect and 1 unintended effect. Write 5-7 sentences.","correct_answer":null,"hints":["Proximate: who signed the contract? who approved the zoning?","Distal: what economic conditions made it possible? what cultural values?","Intended: what was the stated purpose? (housing, commerce, recreation)","Unintended: what changed that nobody planned? (traffic, gentrification, wildlife displacement)"]}', 9, 12, 4, true, 'independent', 'any', 9, ARRAY['causation','analysis','history','complexity','D2.His.14.9-12'], ARRAY['urban_explorer'], ARRAY['Analyze multiple causes and unintended effects of historical developments'], 5, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = 'D2.His.14.9-12';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;


  -- ═══════════════════════════════════════════════════════════
  -- CCSS-ELA GAP (1 standard)
  -- ═══════════════════════════════════════════════════════════

  -- RI.4.7: Interpret visual/quantitative info (4, photo_observation)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Reading Signs and Displays', '{"text":"Information is presented in many ways beyond text: signs use symbols, maps use colors and lines, charts use bars and numbers, and infographics combine text with images. Being able to read and interpret all these forms of information is a key literacy skill. When you see a sign, ask: What information is it presenting? Who is the audience? What would happen if this sign were not here?","items":["Text signs: rules, directions, names","Symbol signs: no words needed (restroom, parking, warning)","Data displays: charts, graphs, tables, maps","Infographics: text + images together for quick understanding"]}', 'reading_writing', 3, 5, true, 'independent', 'any', 4, ARRAY['visual_literacy','signs','interpretation','information','RI.4.7'], ARRAY['explorer','urban_explorer'], ARRAY['Interpret information presented visually and quantitatively'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Sign and Display Reader', 'reading_writing', 'photo_observation', '{"question":"Find 3 different signs or information displays in your area. Take a photo of each. For each one, write: (1) What TYPE of information does it present? (text, symbols, numbers, map, chart), (2) Who is the AUDIENCE? (drivers, pedestrians, children, employees), (3) What is the MAIN MESSAGE? (4) How does the visual design help communicate it?","hints":["Look for: road signs, building signs, information boards, maps","Notice WHO the sign is aimed at — size and placement give clues","Symbols work across languages — that is why they are used","Consider: what would happen if this sign were removed?"]}', 3, 5, 2, true, 'independent', 'any', 4, ARRAY['visual_literacy','signs','analysis','RI.4.7'], ARRAY['explorer'], ARRAY['Analyze how visual and quantitative information is presented'], 7, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = 'RI.4.7';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;


  -- ═══════════════════════════════════════════════════════════
  -- UTAH SEEd GAPS (4 standards)
  -- These are closely aligned to NGSS, so we create tasks that
  -- also reference the Utah-specific framing.
  -- ═══════════════════════════════════════════════════════════

  -- 3.1.1: Forces — balanced/unbalanced (3, numeric_entry)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Push, Pull, Balance', '{"text":"Forces are pushes and pulls that make things move, stop, or change direction. When forces are balanced (equal in opposite directions), nothing moves — like a book sitting on a table. When forces are unbalanced (one is stronger), things move — like pushing a swing. Gravity always pulls things down. Friction pushes back against movement. Understanding forces helps us explain why everything moves (or doesn''t).","items":["Force: a push or pull on an object","Balanced forces: equal and opposite → no movement","Unbalanced forces: one is stronger → movement","Gravity: always pulls toward Earth''s center"]}', 'science_nature', 3, 5, true, 'independent', 'any', 4, ARRAY['forces','push','pull','balance','3.1.1'], ARRAY['field_scientist','young_scientist'], ARRAY['Identify balanced and unbalanced forces','Predict motion from force analysis'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Force Finder', 'science_nature', 'numeric_entry', '{"question":"Find a flat surface (sidewalk, table, bench). Place a small object (rock, leaf, pen) on it. (1) Is the object moving? What balanced forces keep it still? (2) Give it a gentle push. How many centimeters does it slide? (3) Now push harder. How far does it go this time? (4) Which surface nearby would create the most friction (rough) vs least friction (smooth)? Compare slide distances.","unit":"cm (hard push distance)","hints":["Balanced forces: gravity pulls down, the surface pushes up","Your push creates an unbalanced force → the object moves","Friction is the force that slows it down","Rougher surfaces = more friction = shorter slide"]}', 3, 5, 2, true, 'independent', 'any', 4, ARRAY['forces','friction','measurement','3.1.1'], ARRAY['field_scientist'], ARRAY['Investigate balanced and unbalanced forces through measurement'], 5, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = '3.1.1';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- 4.1.1: Light and vision (4, multiple_choice)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'How We See Things', '{"text":"You see objects because light bounces off them and enters your eyes. The sun or a lamp produces light. That light hits an object and reflects (bounces) in all directions. Some of that reflected light enters your eyes, which send a signal to your brain. Without light, you cannot see anything — that is why dark rooms are dark. The color you see depends on which wavelengths of light the object reflects vs absorbs.","items":["Light source: produces light (sun, lamp, screen)","Reflection: light bounces off objects","Your eye: receives reflected light","Your brain: interprets the signals as images"]}', 'science_nature', 3, 5, true, 'independent', 'any', 4, ARRAY['light','vision','reflection','physics','4.1.1'], ARRAY['field_scientist'], ARRAY['Explain that we see objects because reflected light enters our eyes'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Light Path Tracer', 'science_nature', 'multiple_choice', '{"question":"You can see a tree in front of you. What is the correct order of events that lets you see it?","options":["Sunlight hits the tree → light reflects off the tree → reflected light enters your eyes → your brain creates an image","Your eyes send light to the tree → the tree glows → you see it","The tree produces its own light → the light enters your eyes","Your brain imagines the tree → your eyes confirm it"],"correct_answer":"Sunlight hits the tree → light reflects off the tree → reflected light enters your eyes → your brain creates an image","hints":["Objects do NOT produce their own light (unless they glow)","Light always travels FROM a source TO objects TO your eyes","Your eyes RECEIVE light, they do not SEND it","The brain processes the signals — vision happens in the brain, not the eyes"]}', 3, 5, 2, true, 'independent', 'any', 4, ARRAY['light','vision','reflection','sequence','4.1.1'], ARRAY['field_scientist'], ARRAY['Identify the correct sequence of light reflection and vision'], 3, u_owner);
  SELECT id INTO std_id FROM public.education_standards WHERE code = '4.1.1';
  IF std_id IS NOT NULL THEN
    INSERT INTO public.task_standard_alignments (task_id, standard_id, alignment_strength) VALUES (t, std_id, 'primary') ON CONFLICT DO NOTHING;
    INSERT INTO public.primer_standard_alignments (primer_id, standard_id, alignment_strength) VALUES (p, std_id, 'primary') ON CONFLICT DO NOTHING;
  END IF;

  -- 5.1.1: Earth's features patterns (5) — similar to 4-ESS2-2, cross-align
  -- 6.4.1: Environmental factors (6) — similar to MS-LS2-1, cross-align
  -- These Utah standards closely mirror NGSS standards already covered above.
  -- We'll cross-align them in migration 027 rather than creating duplicate content.

END $$;
