-- ══════════════════════════════════════════════════════════════
-- Migration 028: Reading & Writing + History & Community
--
-- Completes the remaining 2 subjects from migration 022.
-- 10 primer+task pairs per subject = 20 total.
-- All with full metadata and is_library=true.
-- ══════════════════════════════════════════════════════════════

DO $$
DECLARE
  u_owner UUID;
  p UUID; t UUID;
BEGIN
  SELECT id INTO u_owner FROM public.users WHERE email = 'mark.keith@gmail.com' LIMIT 1;
  IF u_owner IS NULL THEN
    SELECT id INTO u_owner FROM public.users WHERE role = 'admin' LIMIT 1;
  END IF;

  -- ═══════════════════════════════════════════════════════════
  -- READING & WRITING (10 pairs)
  -- ═══════════════════════════════════════════════════════════

  -- RW-1: Letter Sounds in Nature (K-2, easy, audio_response)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Sounds and Letters Outside', '{"text":"Every sound you hear can be written with letters. The wind makes a whoooosh. A bird goes tweet tweet. Water goes splash. When you write sounds using letters, it is called onomatopoeia. Listening carefully and writing what you hear helps you become a better writer.","items":["Onomatopoeia: words that sound like the sound (buzz, hiss, crack)","Listen quietly for 10 seconds before writing","Nature has more sounds than you think","Every sound can become a word"]}', 'reading_writing', 0, 2, true, 'independent', 'any', 2, ARRAY['sounds','letters','onomatopoeia','phonics','listening'], ARRAY['young_scientist','explorer'], ARRAY['Identify sounds in nature and represent them with letters','Practice onomatopoeia in descriptive writing'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Sound Collector', 'reading_writing', 'audio_response', '{"question":"Close your eyes and listen for 15 seconds. Then record yourself naming 3 sounds you heard and spelling out what they sound like. Example: I heard wind — it goes whoooosh. I heard a bird — it goes chirp chirp. Try to use sound words (onomatopoeia)!","hints":["Listen for: wind, birds, insects, people, cars, water","Say the sound out loud — then try to spell it","Whoosh, buzz, chirp, splash, crunch, rustle are all sound words","It is okay to make up your own sound spelling!"]}', 0, 2, 1, true, 'independent', 'any', 2, ARRAY['sounds','phonics','speaking','onomatopoeia'], ARRAY['young_scientist'], ARRAY['Practice identifying and articulating environmental sounds'], 5, u_owner);

  -- RW-2: Descriptive Writing: 5 Senses (K-2, easy, creative_writing)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Writing with Your Senses', '{"text":"Good writers use their 5 senses to describe the world: sight (what you see), hearing (what you hear), touch (what you feel), smell (what you smell), and taste (only if safe!). When you include senses in your writing, the reader can imagine being right where you are.","items":["Sight: colors, shapes, sizes, movement","Hearing: loud, soft, high, low sounds","Touch: rough, smooth, warm, cold, wet, dry","Smell: sweet, earthy, fresh, smoky"]}', 'reading_writing', 0, 2, true, 'independent', 'any', 2, ARRAY['descriptive_writing','senses','observation','vocabulary'], ARRAY['young_scientist','explorer'], ARRAY['Use sensory details in descriptive writing'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Five Senses Paragraph', 'reading_writing', 'creative_writing', '{"question":"Write 5 sentences about where you are right now — one sentence for each sense. Start each sentence with: I see... I hear... I feel... I smell... I wonder... (Use wonder instead of taste since we do not taste things outside!) Make each sentence as detailed as you can.","hints":["I see: describe colors and shapes you notice","I hear: describe sounds near and far","I feel: what does the air feel like on your skin?","I smell: take a deep breath — earthy? fresh? nothing?"]}', 0, 2, 1, true, 'independent', 'any', 2, ARRAY['descriptive_writing','senses','paragraph'], ARRAY['young_scientist'], ARRAY['Write sensory descriptions of a real environment'], 8, u_owner);

  -- RW-3: Summarizing What You See (3-5, medium, short_text)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'The Art of Summarizing', '{"text":"A summary captures the most important information in fewer words. Good summaries answer: Who or what? Where? When? What is happening? Why does it matter? Scientists write summaries of their field observations. Journalists summarize events. The skill of saying a lot with a little is one of the most valuable writing skills you can develop.","items":["Include: who/what, where, when, what happened","Leave out: minor details, opinions, repetition","Use your own words — do not copy","Aim for 3-5 sentences maximum"]}', 'reading_writing', 3, 5, true, 'independent', 'any', 5, ARRAY['summarizing','main_idea','informational_writing'], ARRAY['explorer'], ARRAY['Summarize observations concisely','Distinguish main ideas from supporting details'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Field Summary', 'reading_writing', 'short_text', '{"question":"Observe your surroundings for 60 seconds. Then write a 3-sentence summary that answers: (1) Where are you? (2) What is the most important or interesting thing happening here? (3) Why would someone else want to visit this spot? Challenge: keep it under 50 words total.","correct_answer":null,"hints":["Start with the location — name or describe it","Pick ONE thing that stands out most","Why does it matter? What makes it interesting?","Read it back — can you cut any words without losing meaning?"]}', 3, 5, 2, true, 'independent', 'any', 5, ARRAY['summarizing','concise_writing','observation'], ARRAY['explorer'], ARRAY['Write concise field summaries under word constraints'], 5, u_owner);

  -- RW-4: Persuasive Letter to City Council (3-5, medium, creative_writing)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Writing to Persuade', '{"text":"Persuasive writing tries to convince the reader to agree with you or take action. A good persuasive letter has: (1) a clear opinion statement, (2) reasons supported by evidence, (3) a response to the other side, and (4) a call to action. When you write to your city council, you are practicing civic engagement — using your voice to improve your community.","items":["Opinion: I believe... / I think we should...","Evidence: I noticed... / The data shows...","Counterargument: Some might say... but...","Call to action: I ask that you... / Please consider..."]}', 'reading_writing', 3, 5, true, 'independent', 'any', 5, ARRAY['persuasive_writing','civic','letter','argument'], ARRAY['urban_explorer','explorer'], ARRAY['Write a persuasive letter with evidence-based arguments'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Letter to City Council', 'reading_writing', 'creative_writing', '{"question":"Look around and find ONE thing that could be improved at this location (a broken bench, missing trash can, need for a crosswalk, more trees, better lighting). Write a short persuasive letter to your city council. Include: (1) Dear City Council, (2) State the problem you observed, (3) Give 2 reasons why it should be fixed, (4) Suggest a specific solution, (5) Sign your name.","hints":["Be specific: where exactly is the problem?","Use evidence: I counted... I noticed... I observed...","Be respectful — council members respond better to polite letters","End with a clear ask: I request that you..."]}', 3, 5, 2, true, 'independent', 'any', 5, ARRAY['persuasive_writing','civic','letter','community'], ARRAY['urban_explorer'], ARRAY['Write a persuasive civic letter based on real observations'], 8, u_owner);

  -- RW-5: Field Notes: Scientific Journaling (3-5, medium, creative_writing)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Writing Like a Scientist', '{"text":"Scientists keep field notebooks to record exactly what they observe. Good field notes include: date, time, location, weather, and detailed observations. They separate FACTS (what they see) from INTERPRETATIONS (what they think it means). Field notes are written in present tense: The bird IS sitting, not The bird WAS sitting. This discipline makes observations more accurate and useful.","items":["Always record: date, time, location, weather","Facts first: describe exactly what you see","Then interpret: what do you think it means?","Use present tense: the plant IS... the rock HAS..."]}', 'reading_writing', 3, 5, true, 'independent', 'any', 5, ARRAY['field_notes','scientific_writing','journaling','observation'], ARRAY['field_scientist','nature_detective'], ARRAY['Write structured scientific field notes','Separate observations from interpretations'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Scientific Field Notes', 'reading_writing', 'creative_writing', '{"question":"Write a scientific field note entry for this location. Include: (1) Date and time, (2) Location description, (3) Weather conditions, (4) 3 OBSERVATIONS (facts you can see), (5) 2 INTERPRETATIONS (what you think the observations mean). Use present tense and be specific.","hints":["Date: today''s date. Time: right now. Weather: look up and around","Observation example: Three pigeons are eating crumbs near the bench","Interpretation example: The pigeons may gather here because people eat lunch here","Keep facts and interpretations clearly separated"]}', 3, 5, 2, true, 'independent', 'any', 5, ARRAY['field_notes','scientific_writing','observation'], ARRAY['field_scientist'], ARRAY['Practice structured scientific field note writing'], 8, u_owner);

  -- RW-6: Compare and Contrast Two Locations (6-8, medium, short_text)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Comparing and Contrasting', '{"text":"Compare means finding similarities. Contrast means finding differences. Strong writers do both to give readers a complete picture. Use signal words: Similarly, both, likewise (comparing) vs However, unlike, whereas, on the other hand (contrasting). A Venn diagram helps organize your thinking before writing.","items":["Compare signal words: both, similarly, likewise, also","Contrast signal words: however, unlike, whereas, but","Organize: similarities in the middle, differences on sides","Strong analysis explains WHY things are similar or different"]}', 'reading_writing', 6, 8, true, 'independent', 'any', 6, ARRAY['compare_contrast','analytical_writing','signal_words'], ARRAY['explorer'], ARRAY['Write compare-contrast analysis using signal words'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Location Comparison', 'reading_writing', 'short_text', '{"question":"Choose two distinct areas you can see from where you stand (e.g., a paved area vs a grassy area, a shady spot vs a sunny spot, a maintained area vs an unmaintained one). Write a compare-contrast paragraph (5-7 sentences) using at least 3 signal words (similarly, however, both, unlike, whereas). Explain why the differences exist.","correct_answer":null,"hints":["Pick two areas that are clearly different","Start with similarities — what do they have in common?","Then contrast — what makes them different?","Explain the WHY: Why is one paved and the other not? Human choices?"]}', 6, 8, 3, true, 'independent', 'any', 6, ARRAY['compare_contrast','analytical_writing','paragraph'], ARRAY['explorer'], ARRAY['Write analytical compare-contrast paragraphs'], 5, u_owner);

  -- RW-7: Argumentative Writing: Land Use (6-8, hard, creative_writing)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Building an Argument', '{"text":"An argument is not a fight — it is a structured case for a position. Academic arguments follow a pattern: claim (your position), evidence (facts that support it), reasoning (how the evidence supports the claim), and counterclaim (acknowledging the other side). The strongest arguments address counterarguments directly instead of ignoring them.","items":["Claim: your position stated clearly","Evidence: specific, observable facts","Reasoning: how the evidence supports the claim","Counterclaim: the strongest opposing argument","Rebuttal: why your position is still stronger"]}', 'reading_writing', 6, 8, true, 'independent', 'any', 7, ARRAY['argumentative_writing','claim','evidence','reasoning'], ARRAY['urban_explorer','explorer'], ARRAY['Construct evidence-based arguments with counterclaims'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Land Use Argument', 'reading_writing', 'creative_writing', '{"question":"Look at the land around you. Write a 5-paragraph argumentative essay outline (1 sentence per paragraph) arguing for either MORE development or MORE green space at this location. Include: (1) Claim with your position, (2) Evidence #1 from what you observe, (3) Evidence #2 from what you observe, (4) Counterclaim and rebuttal, (5) Conclusion restating your position.","hints":["Claim: This area should/should not have more development because...","Evidence: use specific observations — count trees, buildings, open space","Counterclaim: The other side would say... but...","Conclusion: tie back to your strongest evidence"]}', 6, 8, 3, true, 'independent', 'any', 7, ARRAY['argumentative_writing','land_use','evidence'], ARRAY['urban_explorer'], ARRAY['Write structured arguments using environmental evidence'], 8, u_owner);

  -- RW-8: Public Speaking: Tour Guide (6-8, medium, audio_response)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Speaking to an Audience', '{"text":"Public speaking follows different rules than writing. Speak clearly and at a natural pace — not too fast, not too slow. Use pauses for emphasis. Make your opening interesting to hook the listener. Organize your points logically. End with something memorable. A tour guide combines factual knowledge with storytelling to make places come alive.","items":["Hook: start with something interesting or surprising","Pace: speak slower than you think you need to","Pauses: silence is powerful — use it after key points","Close: end with something the listener will remember"]}', 'reading_writing', 6, 8, true, 'independent', 'any', 5, ARRAY['public_speaking','presentation','tour_guide','oral_communication'], ARRAY['explorer','urban_explorer'], ARRAY['Practice structured public speaking','Organize oral presentations logically'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Tour Guide Recording', 'reading_writing', 'audio_response', '{"question":"Record a 60-90 second tour guide narration for this location. Structure: (1) Welcome and introduce the location by name, (2) Describe 2-3 interesting features a visitor should notice, (3) Share one historical or scientific fact about the area, (4) End with a recommendation for what to do next. Use your best tour guide voice!","hints":["Start with: Welcome to... Today I am going to show you...","Point out things the listener should look at: Notice the... Look to your left...","Include at least one fact: This area was built in... / This species is...","End with: Before you leave, make sure to..."]}', 6, 8, 2, true, 'independent', 'any', 5, ARRAY['public_speaking','tour_guide','recording'], ARRAY['explorer'], ARRAY['Deliver a structured oral presentation about a real location'], 5, u_owner);

  -- RW-9: Research Report: Local Ecosystem (9-12, hard, creative_writing)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Writing a Research Report', '{"text":"A research report synthesizes observations and external knowledge into a structured document. It follows a standard format: introduction (context and research question), methods (what you did), results (what you found), and discussion (what it means). Even a brief field report can follow this structure. The key difference between a report and a story: reports prioritize evidence over narrative.","items":["Introduction: what question are you investigating?","Methods: how did you collect data?","Results: what did you observe? (facts only)","Discussion: what do the results mean? (interpretation)"]}', 'reading_writing', 9, 12, true, 'independent', 'any', 8, ARRAY['research_report','academic_writing','IMRAD','formal_writing'], ARRAY['field_scientist'], ARRAY['Write structured research reports using IMRAD format'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Mini Field Report', 'reading_writing', 'creative_writing', '{"question":"Write a mini research report about this location using the IMRAD format. (1) INTRODUCTION: What ecosystem type is this? What question are you investigating? (2) METHODS: How did you observe? How long? What did you measure? (3) RESULTS: List 3-5 specific observations with details. (4) DISCUSSION: What do your observations suggest about ecosystem health, human impact, or biodiversity? Keep each section to 2-3 sentences.","hints":["Introduction: State the ecosystem type and your focus question","Methods: Be specific — I observed for 5 minutes within a 10m radius","Results: Numbers and specifics — I counted 4 species, 2 showed signs of...","Discussion: Connect your results to broader concepts — this suggests..."]}', 9, 12, 4, true, 'independent', 'any', 8, ARRAY['research_report','academic_writing','field_report'], ARRAY['field_scientist'], ARRAY['Apply IMRAD format to field observations'], 10, u_owner);

  -- RW-10: Rhetorical Analysis of Public Signage (9-12, hard, short_text)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Rhetoric Is Everywhere', '{"text":"Rhetoric is the art of persuasion through language and design. Every public sign, poster, and display uses rhetorical strategies: ethos (credibility — who is saying this?), pathos (emotion — how does it make you feel?), and logos (logic — what evidence or reasoning is presented?). Analyzing rhetoric means looking beyond WHAT a text says to HOW and WHY it says it.","items":["Ethos: authority, credentials, trustworthiness","Pathos: emotional appeal, imagery, word choice","Logos: facts, statistics, logical reasoning","Kairos: timing and context — why NOW?"]}', 'reading_writing', 9, 12, true, 'independent', 'any', 9, ARRAY['rhetoric','analysis','persuasion','critical_literacy'], ARRAY['urban_explorer'], ARRAY['Analyze rhetorical strategies in public texts','Identify ethos, pathos, and logos in real-world communication'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Rhetoric in the Wild', 'reading_writing', 'short_text', '{"question":"Find a public sign, poster, advertisement, or display near you. Analyze its rhetoric: (1) What is the main message? (2) Who is the audience? (3) Identify ONE example of ethos (credibility appeal), (4) ONE example of pathos (emotional appeal), and (5) ONE example of logos (logical appeal). If any are missing, explain why the creator might have omitted it.","correct_answer":null,"hints":["Ethos: Does it cite an authority? Use an official logo? Reference expertise?","Pathos: Does it use emotional language, images, or stories?","Logos: Does it use numbers, facts, or logical arguments?","Not all texts use all three — the absence is worth analyzing too"]}', 9, 12, 4, true, 'independent', 'any', 9, ARRAY['rhetoric','analysis','ethos_pathos_logos'], ARRAY['urban_explorer'], ARRAY['Conduct rhetorical analysis of authentic public texts'], 5, u_owner);


  -- ═══════════════════════════════════════════════════════════
  -- HISTORY & COMMUNITY (10 pairs)
  -- ═══════════════════════════════════════════════════════════

  -- HC-1: My Neighborhood Map (K-2, easy, sketch_draw)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'My Community', '{"text":"A community is a group of people who live, work, and play in the same area. Your neighborhood is a community. It has homes where people live, stores where people shop, schools where people learn, and parks where people play. Every community looks different because different people need different things.","items":["Homes: where people live (houses, apartments)","Stores: where people buy things they need","Schools: where people learn","Parks: where people play and relax"]}', 'history_community', 0, 2, true, 'independent', 'any', 2, ARRAY['community','neighborhood','places','mapping'], ARRAY['young_scientist','explorer'], ARRAY['Identify key places in a community','Create a simple map of a familiar area'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'My Community Map', 'history_community', 'sketch_draw', '{"question":"Draw a simple map of what you can see around you. Include at least 4 things: a building, a road or path, something natural (tree, grass, water), and one more thing you choose. Label each thing with its name. Draw a star where YOU are standing!","hints":["Look around in every direction — what do you see?","Draw big things bigger and small things smaller","A road is a long line, a building is a rectangle","Put a big star or X to show where you are"]}', 0, 2, 1, true, 'independent', 'any', 2, ARRAY['community','mapping','spatial'], ARRAY['young_scientist'], ARRAY['Draw a labeled map of the immediate community'], 8, u_owner);

  -- HC-2: Then and Now: What Changed? (K-2, easy, photo_observation)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Things Change Over Time', '{"text":"Everything changes over time. Trees grow bigger. Buildings get older. Roads get repaired. New things are built and old things are removed. When we compare how a place looks NOW to how it looked BEFORE, we learn about history. Even without old photos, we can find clues about what changed.","items":["New things: fresh paint, smooth concrete, young trees","Old things: worn stone, cracked pavement, big old trees","Clues about change: patches, repairs, different materials","Every place has a story of change"]}', 'history_community', 0, 2, true, 'independent', 'any', 2, ARRAY['change','time','history','observation','then_and_now'], ARRAY['explorer','young_scientist'], ARRAY['Identify evidence of change over time in the environment'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Change Detective', 'history_community', 'photo_observation', '{"question":"Find 2 things near you: one that looks OLD and one that looks NEW. Take a photo of each. For the old thing: how do you know it is old? (worn, cracked, faded?) For the new thing: how do you know it is new? (smooth, bright, clean?) What do you think was here BEFORE the new thing was built?","hints":["Old clues: cracks, rust, faded colors, worn edges, moss or lichen","New clues: bright colors, smooth surfaces, clean edges, no wear","A big tree is old; a small planted tree is new","What was here before? Maybe grass, maybe an older building"]}', 0, 2, 1, true, 'independent', 'any', 2, ARRAY['change','observation','history','evidence'], ARRAY['explorer'], ARRAY['Identify and photograph evidence of change over time'], 7, u_owner);

  -- HC-3: Community Helpers Around Us (3-5, easy, data_collection)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'People Who Help Our Community', '{"text":"Communities work because people fill different roles. Teachers educate. Police officers protect. Mail carriers deliver. Construction workers build. Maintenance workers keep things clean and working. Business owners provide goods and services. Every person you see is contributing something to the community, even if you cannot always tell how.","items":["Essential services: police, fire, medical, sanitation","Education: teachers, librarians, coaches","Business: store owners, restaurant workers, delivery drivers","Maintenance: groundskeepers, custodians, road crews"]}', 'history_community', 3, 5, true, 'independent', 'any', 3, ARRAY['community_helpers','roles','services','civic'], ARRAY['explorer','urban_explorer'], ARRAY['Identify community helpers and their contributions'], 3, true, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Community Helper Survey', 'history_community', 'data_collection', '{"question":"In 5 minutes of observation, find evidence of at least 4 different community helpers who work in this area (even if you do not see the people themselves). Record: (1) The helper role, (2) Evidence you found (a mail truck, a clean sidewalk, a police car, a maintained garden), (3) How this helper makes the community better. Which role do you think is most important? Why?","hints":["Look for vehicles: mail trucks, police cars, delivery vans, buses","Look for maintained spaces: someone mows, someone cleans, someone paints","Look for infrastructure: someone built the road, the building, the lights","Even a trash can means someone collects the trash!"]}', 3, 5, 1, true, 'independent', 'any', 3, ARRAY['community_helpers','observation','data','civic'], ARRAY['explorer'], ARRAY['Identify evidence of community helpers through environmental observation'], 8, u_owner);

  -- HC-4: Reading Historical Markers (3-5, medium, short_text)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Stories Written in Stone', '{"text":"Historical markers, plaques, and cornerstones tell the stories of places. A cornerstone shows when a building was built. A plaque might honor someone important. A historical marker explains what happened at a specific spot. These texts are primary sources — they were written by people who were there or knew the history firsthand. Reading them connects you to the past.","items":["Cornerstone: shows the year a building was built","Plaque: honors a person, event, or achievement","Historical marker: explains what happened at a spot","Memorial: remembers people or events from the past"]}', 'history_community', 3, 5, true, 'independent', 'any', 5, ARRAY['historical_markers','primary_sources','reading','local_history'], ARRAY['urban_explorer','explorer'], ARRAY['Read and interpret historical markers and plaques','Identify primary sources in the environment'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Marker Reader', 'history_community', 'short_text', '{"question":"Find a plaque, cornerstone, sign, or marker that tells you something about the history of this place. Read it carefully. Write: (1) What type of marker is it? (2) What year or time period does it reference? (3) What does it tell you about the history of this location? (4) What question does it make you want to ask? If you cannot find a historical marker, read a building name or street sign and explain what it might mean.","correct_answer":null,"hints":["Check building entrances for cornerstones or dedication plaques","Look for bronze or stone markers near sidewalks","Building names often honor important people","Street names can tell history: why was this street named this?"]}', 3, 5, 2, true, 'independent', 'any', 5, ARRAY['historical_markers','reading','interpretation','local_history'], ARRAY['urban_explorer'], ARRAY['Interpret historical markers and generate historical questions'], 5, u_owner);

  -- HC-5: Oral History Interview Questions (3-5, medium, creative_writing)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Listening to History', '{"text":"Oral history is history told through people''s stories. Before writing, all history was oral — passed from person to person through speaking and listening. Historians interview people who lived through events to capture their memories. Good interview questions are open-ended (not yes/no) and ask about feelings, experiences, and details that only someone who was there would know.","items":["Open-ended: What was it like when...? Tell me about...","Avoid yes/no: not Did you like it? but What did you enjoy most?","Follow-up: You mentioned... can you tell me more?","Always: What do you wish people today understood about that time?"]}', 'history_community', 3, 5, true, 'independent', 'any', 5, ARRAY['oral_history','interview','questions','primary_sources'], ARRAY['explorer'], ARRAY['Write open-ended interview questions about local history'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'History Interview Prep', 'history_community', 'creative_writing', '{"question":"Imagine you could interview someone who lived in this area 50 years ago. Write 5 open-ended interview questions that would help you understand how this place has changed. At least 2 questions should be about what you can see right now (e.g., Was this building here? What was on this corner?). Make sure none of your questions can be answered with just yes or no.","hints":["Start with: What do you remember about...","Ask about senses: What did this place sound/smell/look like?","Ask about feelings: How did you feel about...","Ask about change: What is the biggest difference between then and now?"]}', 3, 5, 2, true, 'independent', 'any', 5, ARRAY['oral_history','interview','questions','writing'], ARRAY['explorer'], ARRAY['Compose open-ended historical interview questions'], 8, u_owner);

  -- HC-6: Primary vs Secondary Sources (6-8, medium, sorting_ordering)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Sources: Primary vs Secondary', '{"text":"Primary sources are created by people who were there: letters, photos, diaries, official records, buildings, artifacts. Secondary sources are created later by people who studied the primary sources: textbooks, documentaries, articles, Wikipedia. Historians value primary sources because they are closest to the actual events. But secondary sources help us understand the bigger picture.","items":["Primary: original, firsthand — created at the time","Secondary: analysis, interpretation — created later","Primary examples: the building itself, a cornerstone, a diary entry","Secondary examples: a textbook description, a Wikipedia article"]}', 'history_community', 6, 8, true, 'independent', 'any', 6, ARRAY['primary_sources','secondary_sources','evidence','historical_thinking'], ARRAY['explorer','urban_explorer'], ARRAY['Distinguish primary from secondary historical sources'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Source Sort', 'history_community', 'sorting_ordering', '{"question":"Find 4 things at your location that could be historical sources. Sort them into PRIMARY sources (created at the time, firsthand) and SECONDARY sources (created later, interpretation). For each, explain WHY it fits that category.","items":["Primary: the building itself — it was built at a specific time","Primary: a cornerstone or plaque — placed when building was dedicated","Secondary: a modern information sign about the history — written later","Secondary: your textbook or a website description of this place"],"hints":["The physical building is a primary source — it IS the history","A plaque from the year the building opened = primary","A modern sign explaining the building''s history = secondary","Your phone''s description of this place = secondary"]}', 6, 8, 2, true, 'independent', 'any', 6, ARRAY['primary_sources','secondary_sources','sorting','evidence'], ARRAY['urban_explorer'], ARRAY['Classify real-world items as primary or secondary sources'], 7, u_owner);

  -- HC-7: Architecture Tells History (6-8, medium, photo_observation)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Buildings as Historical Documents', '{"text":"Every building is a historical document. Its materials tell you what was available and affordable when it was built. Its style tells you what people valued aesthetically. Its size tells you about economic conditions. Renovations show how needs changed over time. An architect from 1900 made different choices than one from 2020, and those differences reveal social, economic, and technological history.","items":["Materials: wood → brick → concrete → steel/glass (technology timeline)","Style: ornate (pre-1930) → simple (mid-century) → glass/steel (modern)","Size: reflects economic conditions and population","Renovations: visible patches, additions, updated materials"]}', 'history_community', 6, 8, true, 'type_dependent', 'urban', 6, ARRAY['architecture','history','buildings','change_over_time'], ARRAY['urban_explorer'], ARRAY['Read architectural features as historical evidence'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Building Biography', 'history_community', 'photo_observation', '{"question":"Choose one building you can see. Take a photo and write its biography — the story its physical features tell. Include: (1) Estimated age and your evidence, (2) Original purpose (what was it built for?), (3) Has it been renovated? How can you tell? (4) What does it reveal about the community when it was built?","hints":["Age clues: materials, style, condition, cornerstone dates","Purpose clues: door size, window patterns, loading docks, signage","Renovation clues: different materials on different sections, modern additions","Community clues: was this a wealthy area? A commercial district? Residential?"]}', 6, 8, 2, true, 'type_dependent', 'urban', 6, ARRAY['architecture','history','analysis','observation'], ARRAY['urban_explorer'], ARRAY['Analyze architectural features as historical evidence'], 7, u_owner);

  -- HC-8: Local Government Services Audit (6-8, hard, data_collection)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Government Services Around You', '{"text":"Local government provides services you use every day but rarely think about: roads, sidewalks, street lights, traffic signals, water, sewers, parks, libraries, fire stations, and waste collection. These services are paid for by taxes. Some areas receive better services than others — this inequality is a civic issue worth investigating. Auditing services means checking: what is provided, what is missing, and what could be improved.","items":["Infrastructure: roads, sidewalks, bridges, utilities","Safety: street lights, traffic signals, crosswalks, fire hydrants","Maintenance: road repair, mowing, snow removal, tree trimming","Public spaces: parks, libraries, community centers, playgrounds"]}', 'history_community', 6, 8, true, 'independent', 'any', 7, ARRAY['government','services','civic','audit','infrastructure'], ARRAY['urban_explorer'], ARRAY['Audit local government services','Identify service gaps and inequities'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Government Services Audit', 'history_community', 'data_collection', '{"question":"Audit the government services visible at your location. Rate each 1-5 (1=poor, 5=excellent): (1) Road/sidewalk condition, (2) Street lighting, (3) Crosswalk safety, (4) Park/green space quality, (5) Trash collection (any overflowing bins?), (6) Public signage clarity. Calculate the average score. What is the biggest service gap? Write a 2-sentence recommendation for improvement.","hints":["Walk the block and look at pavement — cracks, potholes, uneven surfaces","Count street lights — are there dark spots at night?","Check crosswalks — are they marked? Do signals work?","Compare this area to your home neighborhood — equal quality?"]}', 6, 8, 3, true, 'independent', 'any', 7, ARRAY['government','audit','data','civic','services'], ARRAY['urban_explorer'], ARRAY['Systematically audit and rate government services'], 10, u_owner);

  -- HC-9: Historical Preservation Debate (9-12, hard, team_debate)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Preserve or Progress?', '{"text":"Historical preservation means protecting old buildings, landscapes, and cultural sites from demolition or alteration. Supporters argue it maintains community identity, cultural heritage, and architectural beauty. Critics argue it prevents needed development, increases housing costs, and can freeze inequality in place. This tension between preservation and progress plays out in every community. There is no universal right answer — context matters.","items":["Pro-preservation: heritage, identity, tourism, beauty","Anti-preservation: housing need, economic growth, adaptation","Compromise: adaptive reuse (keep the shell, modernize the interior)","Key question: who benefits and who is harmed by preservation?"]}', 'history_community', 9, 12, true, 'independent', 'any', 9, ARRAY['preservation','debate','development','heritage','civic'], ARRAY['urban_explorer'], ARRAY['Evaluate arguments for and against historical preservation'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Preservation Debate', 'history_community', 'team_debate', '{"question":"Choose an older structure or area visible from where you stand. Debate: Should this be preserved as-is, or should it be demolished/redeveloped for modern use? Person A argues PRESERVE (history, character, community identity). Person B argues DEVELOP (housing need, economic growth, safety). Person C judges based on strength of evidence. Each side must cite at least 2 pieces of visible evidence.","hints":["Preservation evidence: unique architecture, historical significance, community attachment","Development evidence: disrepair, unmet modern needs, better land use potential","Consider: who benefits from preservation? who benefits from development?","Compromise position: adaptive reuse — keep the exterior, modernize the interior"]}', 9, 12, 4, true, 'independent', 'any', 9, ARRAY['preservation','debate','evidence','civic'], ARRAY['urban_explorer'], ARRAY['Debate historical preservation using on-site evidence'], 7, u_owner);

  -- HC-10: Gentrification Analysis (9-12, hard, short_text)
  p := gen_random_uuid(); t := gen_random_uuid();
  INSERT INTO public.primers (id, title, content, subject_domain, grade_range_min, grade_range_max, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, primer_reveals_location, created_by) VALUES
    (p, 'Understanding Gentrification', '{"text":"Gentrification is the process by which wealthier people move into a lower-income neighborhood, changing its character and raising costs. Signs include: new construction alongside old buildings, trendy businesses replacing longtime shops, rising rents, and demographic shifts. Gentrification is controversial: it can bring investment and reduce crime, but it can also displace longtime residents and erase cultural identity. Analyzing it requires looking at who benefits and who is harmed.","items":["Physical signs: new construction, renovated facades, coffee shops, boutiques","Economic signs: rising property values, higher rents, new chain stores","Social signs: demographic change, cultural shift, displacement","Key question: improvement for whom?"]}', 'history_community', 9, 12, true, 'type_dependent', 'urban', 9, ARRAY['gentrification','urban_change','equity','displacement','economics'], ARRAY['urban_explorer'], ARRAY['Analyze visible signs of gentrification','Evaluate who benefits and who is harmed by neighborhood change'], 3, false, u_owner);
  INSERT INTO public.tasks (id, title, subject_domain, challenge_type, content, grade_range_min, grade_range_max, difficulty_level, is_library, location_dependency, location_type, difficulty_rating, tags, themes, learning_objectives, estimated_minutes, created_by) VALUES
    (t, 'Neighborhood Change Analysis', 'history_community', 'short_text', '{"question":"Analyze this area for signs of gentrification or neighborhood change. Write a 5-7 sentence analysis covering: (1) What physical evidence of change do you see? (new vs old buildings, types of businesses), (2) Who seems to be the current target demographic? (look at store types, price levels, signage language), (3) What might have been here 20 years ago?, (4) Who benefits from the changes you observe? Who might be harmed? Use specific evidence from what you can see.","correct_answer":null,"hints":["New construction next to old buildings = transitioning area","Boutique shops replacing hardware stores or laundromats = gentrification sign","Mixed signage languages may indicate demographic diversity or change","Consider: could longtime residents afford the new businesses?"]}', 9, 12, 4, true, 'type_dependent', 'urban', 9, ARRAY['gentrification','analysis','evidence','urban_change'], ARRAY['urban_explorer'], ARRAY['Analyze visible evidence of neighborhood change and its impacts'], 5, u_owner);


END $$;
